if(EXISTS "/Users/mitsuruk/devs/@Projects/@Stat/statcpp/build-ja/test/statcpp_tests[1]_tests.cmake")
  include("/Users/mitsuruk/devs/@Projects/@Stat/statcpp/build-ja/test/statcpp_tests[1]_tests.cmake")
else()
  add_test(statcpp_tests_NOT_BUILT statcpp_tests_NOT_BUILT)
endif()
