/**
 * @file r_reference_nan.hpp
 * @brief R reference values for inputs containing missing values (NaN policy).
 *
 * Generated by generate_r_reference.R against R 4.4.2.
 * Do not edit by hand: re-run the script instead.
 *
 * Values are C++17 hexadecimal floating-point literals and are therefore
 * bit-identical to the values R produced.
 */

#pragma once

#include <cstddef>

#include "r_compare.hpp"

namespace statcpp_test::r_ref {

/**
 * @brief R: t.test(x, mu = 5.0) with NA in x (NA removed)
 */
struct NaTTestOneSample {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, ::statcpp_test::kNaN, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, ::statcpp_test::kNaN, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kMu0 = 0x1.4p+2;
    static constexpr double kStatistic = 0x1.424942a3932dp-1;
    static constexpr double kDf = 0x1.cp+2;
    static constexpr double kPValue = 0x1.191a5f63dc0b5p-1;
};

/**
 * @brief R: t.test(x, y, var.equal = TRUE) with NA in both samples
 */
struct NaTTestTwoSample {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, ::statcpp_test::kNaN, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, ::statcpp_test::kNaN, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kY[] = {0x1.2p+2, 0x1.2cccccccccccdp+2, ::statcpp_test::kNaN, 0x1.1333333333333p+2, 0x1.2666666666666p+2, 0x1.199999999999ap+2, 0x1.3333333333333p+2, 0x1.0cccccccccccdp+2};
    static constexpr double kStatistic = 0x1.5a5b6baa04468p+2;
    static constexpr double kDf = 0x1.ap+3;
    static constexpr double kPValue = 0x1.f1ebd39a47135p-14;
};

/**
 * @brief R: t.test(x, y) with NA in both samples
 */
struct NaTTestWelch {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, ::statcpp_test::kNaN, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, ::statcpp_test::kNaN, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kY[] = {0x1.2p+2, 0x1.2cccccccccccdp+2, ::statcpp_test::kNaN, 0x1.1333333333333p+2, 0x1.2666666666666p+2, 0x1.199999999999ap+2, 0x1.3333333333333p+2, 0x1.0cccccccccccdp+2};
    static constexpr double kStatistic = 0x1.545902434ffb8p+2;
    static constexpr double kDf = 0x1.6aba5ae558d86p+3;
    static constexpr double kPValue = 0x1.d13ef95f0685cp-13;
};

/**
 * @brief R: t.test(x, y, paired = TRUE); a pair with NA on either side is removed
 */
struct NaTTestPaired {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, ::statcpp_test::kNaN, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, 0x1.4cccccccccccdp+2};
    static constexpr double kY[] = {0x1.6p+2, 0x1.4cccccccccccdp+2, 0x1.6666666666666p+2, ::statcpp_test::kNaN, 0x1.4666666666666p+2, 0x1.599999999999ap+2, 0x1.6666666666666p+2};
    static constexpr double kStatistic = -0x1.bc2c9470ceefdp+1;
    static constexpr double kDf = 0x1p+2;
    static constexpr double kPValue = 0x1.a31eae144827cp-6;
};

/**
 * @brief R: var.test(x, y) with NA in both samples
 */
struct NaFTest {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, ::statcpp_test::kNaN, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, ::statcpp_test::kNaN, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kY[] = {0x1.2p+2, 0x1.2cccccccccccdp+2, ::statcpp_test::kNaN, 0x1.1333333333333p+2, 0x1.2666666666666p+2, 0x1.199999999999ap+2, 0x1.3333333333333p+2, 0x1.0cccccccccccdp+2};
    static constexpr double kStatistic = 0x1.37829cbc14e5bp-1;
    static constexpr std::size_t kDf = 7;
    static constexpr std::size_t kDf2 = 6;
    static constexpr double kPValue = 0x1.0efe51266a0b2p-1;
};

/**
 * @brief R: wilcox.test(x, mu = 4.95, exact = FALSE) with NA in x
 */
struct NaWilcoxonSignedRank {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, ::statcpp_test::kNaN, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, ::statcpp_test::kNaN, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kMu0 = 0x1.3cccccccccccdp+2;
    static constexpr double kStatistic = 0x1.ap+4;
    static constexpr double kPValue = 0x1.299f2d478621cp-2;
};

/**
 * @brief R: wilcox.test(x, y, exact = FALSE) with NA in both samples
 */
struct NaMannWhitneyU {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, ::statcpp_test::kNaN, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, ::statcpp_test::kNaN, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kY[] = {0x1.2p+2, 0x1.2cccccccccccdp+2, ::statcpp_test::kNaN, 0x1.1333333333333p+2, 0x1.2666666666666p+2, 0x1.199999999999ap+2, 0x1.3333333333333p+2, 0x1.0cccccccccccdp+2};
    static constexpr double kStatistic = 0x1.bcp+5;
    static constexpr double kPValue = 0x1.c583d1bbf925p-10;
};

/**
 * @brief R: kruskal.test(groups) with NA in every group
 */
struct NaKruskalWallis {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kGroupsFlat[] = {0x1.7333333333333p+1, 0x1.8p+1, ::statcpp_test::kNaN, 0x1.4p+1, 0x1.4cccccccccccdp+1, 0x1.999999999999ap+1, 0x1.e666666666666p+1, 0x1.599999999999ap+1, 0x1p+2, 0x1.3333333333333p+1, ::statcpp_test::kNaN, 0x1.6666666666666p+1, 0x1.b333333333333p+1, 0x1.d99999999999ap+1, ::statcpp_test::kNaN, 0x1.199999999999ap+1, 0x1p+1};
    static constexpr std::size_t kGroupsSizes[] = {6, 5, 6};
    static constexpr std::size_t kGroupsCount = 3;
    static constexpr double kStatistic = 0x1.8af8af8af8bp-1;
    static constexpr std::size_t kDf = 2;
    static constexpr double kPValue = 0x1.5c2457c1e8232p-1;
};

/**
 * @brief R: shapiro.test(x) with NA in x (NA removed)
 *
 * statcpp and R use different Shapiro-Wilk approximations; only agreement to a few percent is
 * expected.
 */
struct NaShapiroWilk {
    static constexpr double kRtol = 1e-06;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 0.05;
    static constexpr double kX[] = {0x1.4666666666666p+2, ::statcpp_test::kNaN, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, ::statcpp_test::kNaN, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kStatistic = 0x1.ee6a92f7dab3bp-1;
    static constexpr double kPValue = 0x1.b94da3f6cd6bp-1;
};

/**
 * @brief R: summary(aov(y ~ g)) with NA in every group (na.omit)
 */
struct NaOneWayAnova {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kGroupsFlat[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, ::statcpp_test::kNaN, 0x1.5333333333333p+2, 0x1.4p+2, 0x1.2p+2, 0x1.2cccccccccccdp+2, 0x1.1333333333333p+2, ::statcpp_test::kNaN, 0x1.2666666666666p+2, 0x1.6666666666666p+2, ::statcpp_test::kNaN, 0x1.799999999999ap+2, 0x1.599999999999ap+2, 0x1.7333333333333p+2};
    static constexpr std::size_t kGroupsSizes[] = {5, 5, 5};
    static constexpr std::size_t kGroupsCount = 3;
    static constexpr double kFStatistic = 0x1.27711dc47711dp+5;
    static constexpr double kPValue = 0x1.80c8f073ef24cp-15;
    static constexpr double kDfBetween = 0x1p+1;
    static constexpr double kDfWithin = 0x1.2p+3;
    static constexpr double kSsBetween = 0x1.52c5f92c5f92ep+1;
    static constexpr double kSsWithin = 0x1.4a3d70a3d70a6p-2;
};

/**
 * @brief R: survfit(Surv(time, event) ~ 1); observations with NA time are removed
 */
struct NaKaplanMeier {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kTimes[] = {0x1.8p+2, 0x1.cp+2, ::statcpp_test::kNaN, 0x1.4p+3, 0x1.ep+3, 0x1.3p+4, 0x1.9p+4, ::statcpp_test::kNaN, 0x1p+5, 0x1.1p+5};
    static constexpr double kEvents[] = {0x1p+0, 0x0p+0, 0x1p+0, 0x1p+0, 0x0p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x0p+0, 0x1p+0};
    static constexpr double kEventTimes[] = {0x0p+0, 0x1.8p+2, 0x1.4p+3, 0x1.3p+4, 0x1.9p+4, 0x1.1p+5};
    static constexpr double kSurvival[] = {0x1p+0, 0x1.cp-1, 0x1.7555555555556p-1, 0x1.18p-1, 0x1.7555555555555p-2, 0x0p+0};
};

/**
 * @brief R: mean, var, sd, median and diff(range(x)) are NA when x contains NA
 */
struct NaDescriptive {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, ::statcpp_test::kNaN, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, ::statcpp_test::kNaN, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kMean = ::statcpp_test::kNaN;
    static constexpr double kVariance = ::statcpp_test::kNaN;
    static constexpr double kStddev = ::statcpp_test::kNaN;
    static constexpr double kMedian = ::statcpp_test::kNaN;
    static constexpr double kRange = ::statcpp_test::kNaN;
};

/**
 * @brief R: cor(x, y, method) is NA when either input contains NA
 */
struct NaCorrelation {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.3333333333333p+0, 0x1.2666666666666p+1, ::statcpp_test::kNaN, 0x1.0666666666666p+2, 0x1.4p+2, 0x1.8cccccccccccdp+2};
    static constexpr double kY[] = {0x1p+1, 0x1.7333333333333p+1, 0x1.e666666666666p+1, 0x1.199999999999ap+2, 0x1.4666666666666p+2, 0x1.b99999999999ap+2};
    static constexpr double kPearson = ::statcpp_test::kNaN;
    static constexpr double kSpearman = ::statcpp_test::kNaN;
    static constexpr double kKendall = ::statcpp_test::kNaN;
};

/**
 * @brief R: p.adjust(p, method) counts only the non-NA p-values; NA stays NA
 */
struct NaPAdjust {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kPValues[] = {0x1.47ae147ae147bp-7, ::statcpp_test::kNaN, 0x1.47ae147ae147bp-5, 0x1.eb851eb851eb8p-6, ::statcpp_test::kNaN, 0x1.999999999999ap-3, 0x1.47ae147ae147bp-8};
    static constexpr double kBonferroni[] = {0x1.999999999999ap-5, ::statcpp_test::kNaN, 0x1.999999999999ap-3, 0x1.3333333333333p-3, ::statcpp_test::kNaN, 0x1p+0, 0x1.999999999999ap-6};
    static constexpr double kHolm[] = {0x1.47ae147ae147bp-5, ::statcpp_test::kNaN, 0x1.70a3d70a3d70ap-4, 0x1.70a3d70a3d70ap-4, ::statcpp_test::kNaN, 0x1.999999999999ap-3, 0x1.999999999999ap-6};
    static constexpr double kBh[] = {0x1.999999999999ap-6, ::statcpp_test::kNaN, 0x1.999999999999ap-5, 0x1.999999999999ap-5, ::statcpp_test::kNaN, 0x1.999999999999ap-3, 0x1.999999999999ap-6};
};

/**
 * @brief R: scale(x); column statistics use the non-NA values, the NA cell stays NA
 *
 * No column contains its own mean, so every non-NA reference value is nonzero.
 */
struct NaScale {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kXFlat[] = {0x1p+0, 0x1.4p+1, 0x1p+1, 0x1p+0, ::statcpp_test::kNaN, 0x1p+2, 0x1p+2, 0x1.8p+1, 0x1.4p+2, 0x1.6p+2};
    static constexpr std::size_t kXRows = 5;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kScaledFlat[] = {-0x1.186f174f88472p+0, -0x1.aa7864392d36p-2, -0x1.186f174f88472p-1, -0x1.4f1573517ef38p+0, ::statcpp_test::kNaN, 0x1.e76504d3a162p-2, 0x1.186f174f88472p-1, -0x1.e76504d3a162ap-4, 0x1.186f174f88472p+0, 0x1.5e509b781bfe8p+0};
    static constexpr std::size_t kScaledRows = 5;
    static constexpr std::size_t kScaledCols = 2;
};

/**
 * @brief R: stats::filter(x, rep(1 / w, w), sides = 1) without the w - 1 leading NA
 */
struct NaMovingAverage {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.8p+0, 0x1p+1, ::statcpp_test::kNaN, 0x1.2p+2, 0x1.4p+2, 0x1.ap+2, 0x1.cp+2, 0x1.1p+3};
    static constexpr std::size_t kWindow = 3;
    static constexpr double kAverage[] = {::statcpp_test::kNaN, ::statcpp_test::kNaN, ::statcpp_test::kNaN, 0x1.5555555555555p+2, 0x1.8aaaaaaaaaaaap+2, 0x1.d555555555554p+2};
};

/**
 * @brief R: dist(rbind(a, b), method); NA coordinates are skipped and the sum is scaled by n / n_used
 */
struct NaDistance {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kA[] = {0x1p+0, 0x1p+1, ::statcpp_test::kNaN, 0x1p+2, 0x1.8p+2, 0x1.cp+1};
    static constexpr double kB[] = {0x1p+1, ::statcpp_test::kNaN, 0x1p+0, 0x1p+0, 0x1.8p+1, 0x1.4p+2};
    static constexpr double kP = 0x1.8p+1;
    static constexpr double kEuclidean = 0x1.6954b41cd4293p+2;
    static constexpr double kManhattan = 0x1.98p+3;
    static constexpr double kMinkowski = 0x1.1c3268f980ddbp+2;
};

/**
 * @brief R: lm(y ~ x) with NA in x and y (na.omit)
 */
struct NaSimpleLinearRegression {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1p+0, 0x1p+1, ::statcpp_test::kNaN, 0x1p+2, 0x1.4p+2, 0x1.8p+2, 0x1.cp+2, 0x1p+3, 0x1.2p+3};
    static constexpr double kY[] = {0x1.0cccccccccccdp+1, 0x1.f333333333333p+1, 0x1.8cccccccccccdp+2, 0x1.0333333333333p+3, 0x1.399999999999ap+3, 0x1.8666666666666p+3, ::statcpp_test::kNaN, 0x1.019999999999ap+4, 0x1.24ccccccccccdp+4};
    static constexpr double kIntercept = -0x1.2a32a32a329f9p-4;
    static constexpr double kSlope = 0x1.03b13b13b13b1p+1;
    static constexpr double kRSquared = 0x1.ffafd1cd70ef1p-1;
    static constexpr double kResidualSe = 0x1.4b84c3f60251dp-3;
    static constexpr std::size_t kDfResidual = 5;
};

/**
 * @brief R: lm(y ~ X) with NA in X and y (na.omit)
 */
struct NaMultipleLinearRegression {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kXFlat[] = {0x1p+0, 0x1p+1, 0x1p+1, 0x1p+0, 0x1.8p+1, ::statcpp_test::kNaN, 0x1p+2, 0x1.8p+1, 0x1.4p+2, 0x1.8p+2, 0x1.8p+2, 0x1.4p+2, 0x1.cp+2, 0x1p+3, 0x1p+3, 0x1.2p+3, 0x1.2p+3, 0x1.cp+2, 0x1.4p+3, 0x1.6p+3};
    static constexpr std::size_t kXRows = 10;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kY[] = {0x1.8cccccccccccdp+1, 0x1.f333333333333p+1, 0x1.0666666666666p+3, 0x1.f333333333333p+2, 0x1.8333333333333p+3, ::statcpp_test::kNaN, 0x1.04ccccccccccdp+4, 0x1.199999999999ap+4, 0x1.119999999999ap+4, 0x1.6666666666666p+4};
    static constexpr double kCoefficients[] = {0x1.b28343b1a75f4p-2, 0x1.1fd4041f9d093p+0, 0x1.ec3dda338b2abp-1};
    static constexpr double kRSquared = 0x1.ff027022fd7f9p-1;
    static constexpr std::size_t kDfResidual = 5;
};

/**
 * @brief R: glm(y ~ x, family = binomial()) with NA in x and y (na.omit)
 */
struct NaLogisticRegression {
    static constexpr double kRtol = 1e-07;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kXFlat[] = {0x1p-1, 0x1.3333333333333p+0, ::statcpp_test::kNaN, 0x1.6666666666666p+1, 0x1.8cccccccccccdp+1, 0x1p+2, 0x1.199999999999ap+2, 0x1.6666666666666p+2, 0x1.8666666666666p+2, 0x1.d333333333333p+2, 0x1.199999999999ap+1, 0x1.4p+2};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 1;
    static constexpr double kY[] = {0x0p+0, 0x0p+0, 0x1p+0, 0x0p+0, 0x1p+0, 0x0p+0, 0x1p+0, 0x1p+0, ::statcpp_test::kNaN, 0x1p+0, 0x0p+0, 0x1p+0};
    static constexpr double kCoefficients[] = {-0x1.990d5d27fd04fp+2, 0x1.ca4ea4631f779p+0};
    static constexpr double kResidualDeviance = 0x1.7da625d65b338p+2;
    static constexpr std::size_t kDfResidual = 8;
};

/**
 * @brief R: glm(y ~ x, family = poisson()) with NA in x and y (na.omit)
 */
struct NaPoissonRegression {
    static constexpr double kRtol = 1e-07;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kXFlat[] = {0x1p-1, 0x1p+0, 0x1.8p+0, ::statcpp_test::kNaN, 0x1.4p+1, 0x1.8p+1, 0x1.cp+1, 0x1p+2, 0x1.2p+2, 0x1.4p+2};
    static constexpr std::size_t kXRows = 10;
    static constexpr std::size_t kXCols = 1;
    static constexpr double kY[] = {0x1p+0, 0x0p+0, 0x1p+1, 0x1.8p+1, ::statcpp_test::kNaN, 0x1.4p+2, 0x1p+2, 0x1.cp+2, 0x1.2p+3, 0x1p+3};
    static constexpr double kCoefficients[] = {-0x1.3373e03133d9bp-2, 0x1.0c0bad8f50064p-1};
    static constexpr double kResidualDeviance = 0x1.0048ac3006c71p+2;
    static constexpr std::size_t kDfResidual = 6;
};

/**
 * @brief R: sort drops NA, order puts NA last, rank(na.last = "keep") keeps NA
 *
 * Indices are zero-based in C++ and one-based in R; the two ties at 1.5 keep their original
 * order in R, which statcpp's argsort does not promise, so order is compared on the values it
 * selects.
 */
struct NaSortOrder {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.8p+1, ::statcpp_test::kNaN, 0x1p+0, 0x1p+2, 0x1.8p+0, ::statcpp_test::kNaN, 0x1.2p+3, 0x1p+1, 0x1.8p+2, 0x1.8p+0};
    static constexpr double kSorted[] = {0x1p+0, 0x1.8p+0, 0x1.8p+0, 0x1p+1, 0x1.8p+1, 0x1p+2, 0x1.8p+2, 0x1.2p+3};
    static constexpr double kSortedDecreasing[] = {0x1.2p+3, 0x1.8p+2, 0x1p+2, 0x1.8p+1, 0x1p+1, 0x1.8p+0, 0x1.8p+0, 0x1p+0};
    static constexpr double kOrder[] = {0x1p+1, 0x1p+2, 0x1.2p+3, 0x1.cp+2, 0x0p+0, 0x1.8p+1, 0x1p+3, 0x1.8p+2, 0x1p+0, 0x1.4p+2};
    static constexpr double kOrderDecreasing[] = {0x1.8p+2, 0x1p+3, 0x1.8p+1, 0x0p+0, 0x1.cp+2, 0x1p+2, 0x1.2p+3, 0x1p+1, 0x1p+0, 0x1.4p+2};
    static constexpr double kRank[] = {0x1.4p+2, ::statcpp_test::kNaN, 0x1p+0, 0x1.8p+2, 0x1.4p+1, ::statcpp_test::kNaN, 0x1p+3, 0x1p+2, 0x1.cp+2, 0x1.4p+1};
};

/**
 * @brief R: unique(x) treats every NA as one value
 */
struct NaUnique {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1p+0, ::statcpp_test::kNaN, 0x1p+1, ::statcpp_test::kNaN, 0x1p+0, 0x1.cp+1};
    static constexpr double kUnique[] = {0x1p+0, ::statcpp_test::kNaN, 0x1p+1, 0x1.cp+1};
};

}  // namespace statcpp_test::r_ref
