/**
 * @file r_reference_crossval.hpp
 * @brief R reference values for cross-validation with deterministic folds.
 *
 * Generated by generate_r_reference.R against R 4.4.2.
 * Do not edit by hand: re-run the script instead.
 *
 * Values are C++17 hexadecimal floating-point literals and are therefore
 * bit-identical to the values R produced.
 */

#pragma once

#include <cstddef>

#include "r_compare.hpp"

namespace statcpp_test::r_ref {

/**
 * @brief R: contiguous k-fold split reproduced, with lm refitted on each training set
 *
 * Reproducible only because shuffle = false is passed; the default shuffles with the global
 * random engine.
 */
struct CrossValidateLinear {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-09;
    static constexpr double kXFlat[] = {0x1.0cccccccccccdp+1, 0x1.6p+2, 0x1.b333333333333p+1, 0x1.0666666666666p+2, 0x1.ccccccccccccdp+0, 0x1.b333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.999999999999ap+1, 0x1.2666666666666p+2, 0x1.399999999999ap+2, 0x1.b99999999999ap+2, 0x1.4cccccccccccdp+1, 0x1.a666666666666p+1, 0x1.4666666666666p+2, 0x1.c666666666666p+2, 0x1.199999999999ap+1, 0x1.7333333333333p+2, 0x1.d99999999999ap+1, 0x1.0cccccccccccdp+3, 0x1.e666666666666p+0, 0x1.8cccccccccccdp+2, 0x1.b333333333333p+1, 0x1.2333333333333p+3, 0x1.6666666666666p+0};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kY[] = {0x1.a333333333333p+3, 0x1.c666666666666p+3, 0x1.799999999999ap+3, 0x1.2666666666666p+4, 0x1.2p+4, 0x1.64ccccccccccdp+4, 0x1.dcccccccccccdp+3, 0x1.9666666666666p+4, 0x1.399999999999ap+4, 0x1.c8p+4, 0x1.6333333333333p+4, 0x1.cb33333333333p+4};
    static constexpr std::size_t kK = 4;
    static constexpr double kFoldErrors[] = {0x1.d404022b76003p+0, 0x1.58ee8e5665041p+0, 0x1.c32ab83527718p+0, 0x1.cc201bcaf607ap+0};
    static constexpr double kMeanError = 0x1.af0f59207e1f6p+0;
    static constexpr double kSeError = 0x1.cea37608b2361p-4;
};

/**
 * @brief R: ridge closed form refitted on each contiguous fold
 *
 * statcpp solves each ridge fit by coordinate descent with the API default tol = 1e-6, so the
 * fold errors agree with the closed form to about that precision.
 */
struct CvRidge {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 0.0001;
    static constexpr double kXFlat[] = {0x1.0cccccccccccdp+1, 0x1.6p+2, 0x1.b333333333333p+1, 0x1.0666666666666p+2, 0x1.ccccccccccccdp+0, 0x1.b333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.999999999999ap+1, 0x1.2666666666666p+2, 0x1.399999999999ap+2, 0x1.b99999999999ap+2, 0x1.4cccccccccccdp+1, 0x1.a666666666666p+1, 0x1.4666666666666p+2, 0x1.c666666666666p+2, 0x1.199999999999ap+1, 0x1.7333333333333p+2, 0x1.d99999999999ap+1, 0x1.0cccccccccccdp+3, 0x1.e666666666666p+0, 0x1.8cccccccccccdp+2, 0x1.b333333333333p+1, 0x1.2333333333333p+3, 0x1.6666666666666p+0};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kY[] = {0x1.a333333333333p+3, 0x1.c666666666666p+3, 0x1.799999999999ap+3, 0x1.2666666666666p+4, 0x1.2p+4, 0x1.64ccccccccccdp+4, 0x1.dcccccccccccdp+3, 0x1.9666666666666p+4, 0x1.399999999999ap+4, 0x1.c8p+4, 0x1.6333333333333p+4, 0x1.cb33333333333p+4};
    static constexpr std::size_t kK = 4;
    static constexpr double kLambdaGrid[] = {0x1.999999999999ap-4, 0x1p+0, 0x1.4p+2, 0x1.4p+4};
    static constexpr double kCvErrors[] = {0x1.c07f9d3105393p+0, 0x1.4e4761bb69c4dp+1, 0x1.62da01cfcd9bp+2, 0x1.087abaf4765d1p+4};
    static constexpr double kBestLambda = 0x1.999999999999ap-4;
};

/**
 * @brief R: lasso coordinate descent refitted on each contiguous fold
 */
struct CvLasso {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 0.0001;
    static constexpr double kXFlat[] = {0x1.0cccccccccccdp+1, 0x1.6p+2, 0x1.b333333333333p+1, 0x1.0666666666666p+2, 0x1.ccccccccccccdp+0, 0x1.b333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.999999999999ap+1, 0x1.2666666666666p+2, 0x1.399999999999ap+2, 0x1.b99999999999ap+2, 0x1.4cccccccccccdp+1, 0x1.a666666666666p+1, 0x1.4666666666666p+2, 0x1.c666666666666p+2, 0x1.199999999999ap+1, 0x1.7333333333333p+2, 0x1.d99999999999ap+1, 0x1.0cccccccccccdp+3, 0x1.e666666666666p+0, 0x1.8cccccccccccdp+2, 0x1.b333333333333p+1, 0x1.2333333333333p+3, 0x1.6666666666666p+0};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kY[] = {0x1.a333333333333p+3, 0x1.c666666666666p+3, 0x1.799999999999ap+3, 0x1.2666666666666p+4, 0x1.2p+4, 0x1.64ccccccccccdp+4, 0x1.dcccccccccccdp+3, 0x1.9666666666666p+4, 0x1.399999999999ap+4, 0x1.c8p+4, 0x1.6333333333333p+4, 0x1.cb33333333333p+4};
    static constexpr std::size_t kK = 4;
    static constexpr double kLambdaGrid[] = {0x1.999999999999ap-4, 0x1p+0, 0x1.4p+2, 0x1.4p+4};
    static constexpr double kCvErrors[] = {0x1.b56875fded895p+0, 0x1.a3d1885cc48aap+0, 0x1.2ac37db1a79e6p+1, 0x1.af564594a389ep+3};
    static constexpr double kBestLambda = 0x1p+0;
};

/**
 * @brief R: contiguous k-fold index blocks, the first (n mod k) folds taking one extra observation
 *
 * Indices are zero-based in C++ and one-based in R.
 */
struct CreateCvFolds {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr std::size_t kN = 12;
    static constexpr std::size_t kK = 4;
    static constexpr double kFoldSizes[] = {0x1.8p+1, 0x1.8p+1, 0x1.8p+1, 0x1.8p+1};
    static constexpr double kFirstIndices[] = {0x0p+0, 0x1.8p+1, 0x1.8p+2, 0x1.2p+3};
    static constexpr double kFlatIndices[] = {0x0p+0, 0x1p+0, 0x1p+1, 0x1.8p+1, 0x1p+2, 0x1.4p+2, 0x1.8p+2, 0x1.cp+2, 0x1p+3, 0x1.2p+3, 0x1.4p+3, 0x1.6p+3};
};

}  // namespace statcpp_test::r_ref
