/**
 * @file r_reference_hypothesis.hpp
 * @brief R reference values for hypothesis tests (parametric, nonparametric, ANOVA).
 *
 * Generated by generate_r_reference.R against R 4.4.2.
 * Do not edit by hand: re-run the script instead.
 *
 * Values are C++17 hexadecimal floating-point literals and are therefore
 * bit-identical to the values R produced.
 */

#pragma once

#include <cstddef>

#include "r_compare.hpp"

namespace statcpp_test::r_ref {

/**
 * @brief R: t.test(x, mu = 5.0)
 */
struct TTestOneSample {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kMu0 = 0x1.4p+2;
    static constexpr double kStatistic = 0x1.424942a3932dp-1;
    static constexpr double kDf = 0x1.cp+2;
    static constexpr double kPValue = 0x1.191a5f63dc0b5p-1;
};

/**
 * @brief R: t.test(x, mu = 4.9, alternative = "greater")
 */
struct TTestOneSampleGreater {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kMu0 = 0x1.399999999999ap+2;
    static constexpr double kStatistic = 0x1.276dd26b46eaap+1;
    static constexpr double kDf = 0x1.cp+2;
    static constexpr double kPValue = 0x1.bd2eba2df9b2cp-6;
};

/**
 * @brief R: t.test(x, y, var.equal = TRUE)
 */
struct TTestTwoSample {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2};
    static constexpr double kY[] = {0x1.2p+2, 0x1.2cccccccccccdp+2, 0x1.1333333333333p+2, 0x1.2666666666666p+2, 0x1.199999999999ap+2};
    static constexpr double kStatistic = 0x1.33e28c20c28b2p+2;
    static constexpr double kDf = 0x1p+3;
    static constexpr double kPValue = 0x1.5e856f5ada672p-10;
};

/**
 * @brief R: t.test(x, y)
 */
struct TTestWelch {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2};
    static constexpr double kY[] = {0x1.2p+2, 0x1.2cccccccccccdp+2, 0x1.1333333333333p+2, 0x1.2666666666666p+2, 0x1.199999999999ap+2};
    static constexpr double kStatistic = 0x1.33e28c20c28b2p+2;
    static constexpr double kDf = 0x1.eb16e3e9ba76bp+2;
    static constexpr double kPValue = 0x1.8a08e8554a6fp-10;
};

/**
 * @brief R: t.test(x, y, paired = TRUE)
 */
struct TTestPaired {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, 0x1.4cccccccccccdp+2};
    static constexpr double kY[] = {0x1.6p+2, 0x1.4cccccccccccdp+2, 0x1.6666666666666p+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.599999999999ap+2};
    static constexpr double kStatistic = -0x1.2706821902e9ap+3;
    static constexpr double kDf = 0x1.4p+2;
    static constexpr double kPValue = 0x1.084f8568c32a3p-12;
};

/**
 * @brief R: manual, z = (mean(x) - mu0) / (sigma / sqrt(n)), p = 2 * pnorm(-|z|)
 */
struct ZTest {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kMu0 = 0x1.4p+2;
    static constexpr double kSigma = 0x1.999999999999ap-3;
    static constexpr double kStatistic = 0x1.0f876ccdf6cacp-1;
    static constexpr double kPValue = 0x1.311796a46f084p-1;
    static constexpr double kDf = ::statcpp_test::kInf;
};

/**
 * @brief R: var.test(x, y)
 */
struct FTest {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2};
    static constexpr double kY[] = {0x1.2p+2, 0x1.2cccccccccccdp+2, 0x1.1333333333333p+2, 0x1.2666666666666p+2, 0x1.199999999999ap+2};
    static constexpr double kStatistic = 0x1.851eb851eb84ap+0;
    static constexpr std::size_t kDf = 4;
    static constexpr std::size_t kDf2 = 4;
    static constexpr double kPValue = 0x1.63c5ead78ce6ap-1;
};

/**
 * @brief R: chisq.test(observed, p = rep(1/6, 6))
 */
struct ChisqTestGof {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kObserved[] = {0x1p+4, 0x1.2p+4, 0x1p+4, 0x1.cp+3, 0x1.8p+3, 0x1.8p+3};
    static constexpr double kExpected[] = {0x1.d555555555555p+3, 0x1.d555555555555p+3, 0x1.d555555555555p+3, 0x1.d555555555555p+3, 0x1.d555555555555p+3, 0x1.d555555555555p+3};
    static constexpr double kStatistic = 0x1p+1;
    static constexpr double kDf = 0x1.4p+2;
    static constexpr double kPValue = 0x1.b2c3235f16995p-1;
};

/**
 * @brief R: chisq.test(observed)
 */
struct ChisqTestGofUniform {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kObserved[] = {0x1p+4, 0x1.2p+4, 0x1p+4, 0x1.cp+3, 0x1.8p+3, 0x1.8p+3};
    static constexpr double kStatistic = 0x1p+1;
    static constexpr double kDf = 0x1.4p+2;
    static constexpr double kPValue = 0x1.b2c3235f16995p-1;
};

/**
 * @brief R: chisq.test(table, correct = FALSE)
 */
struct ChisqTestIndependence {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kTableFlat[] = {0x1.ep+4, 0x1.4p+4, 0x1.ep+3, 0x1.9p+4, 0x1.18p+5, 0x1.4p+4};
    static constexpr std::size_t kTableRows = 2;
    static constexpr std::size_t kTableCols = 3;
    static constexpr double kStatistic = 0x1.dfc29f12ab593p+1;
    static constexpr std::size_t kDf = 2;
    static constexpr double kPValue = 0x1.3a5d81802f6aap-3;
};

/**
 * @brief R: manual, z = (p_hat - p0) / sqrt(p0 (1 - p0) / n); z^2 equals prop.test(correct = FALSE)
 */
struct ZTestProportion {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr std::size_t kSuccesses = 45;
    static constexpr std::size_t kTrials = 100;
    static constexpr double kP0 = 0x1p-1;
    static constexpr double kStatistic = -0x1.ffffffffffffep-1;
    static constexpr double kPValue = 0x1.44ed0bb7cb20fp-2;
    static constexpr double kChisqCrossCheck = 0x1p+0;
};

/**
 * @brief R: manual, pooled-proportion two-sample z; z^2 equals prop.test(correct = FALSE)
 */
struct ZTestProportionTwoSample {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr std::size_t kSuccesses1 = 45;
    static constexpr std::size_t kTrials1 = 100;
    static constexpr std::size_t kSuccesses2 = 30;
    static constexpr std::size_t kTrials2 = 90;
    static constexpr double kStatistic = 0x1.a489bb368dc53p+0;
    static constexpr double kPValue = 0x1.9b6675a96bb93p-4;
    static constexpr double kChisqCrossCheck = 0x1.596a1c32753dbp+1;
};

/**
 * @brief R: p.adjust(p, method = "bonferroni")
 */
struct BonferroniCorrection {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kPValues[] = {0x1.47ae147ae147bp-7, 0x1.47ae147ae147bp-5, 0x1.eb851eb851eb8p-6, 0x1.999999999999ap-3, 0x1.47ae147ae147bp-8};
    static constexpr double kAdjusted[] = {0x1.999999999999ap-5, 0x1.999999999999ap-3, 0x1.3333333333333p-3, 0x1p+0, 0x1.999999999999ap-6};
};

/**
 * @brief R: p.adjust(p, method = "holm")
 */
struct HolmCorrection {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kPValues[] = {0x1.47ae147ae147bp-7, 0x1.47ae147ae147bp-5, 0x1.eb851eb851eb8p-6, 0x1.999999999999ap-3, 0x1.47ae147ae147bp-8};
    static constexpr double kAdjusted[] = {0x1.47ae147ae147bp-5, 0x1.70a3d70a3d70ap-4, 0x1.70a3d70a3d70ap-4, 0x1.999999999999ap-3, 0x1.999999999999ap-6};
};

/**
 * @brief R: p.adjust(p, method = "BH")
 */
struct BenjaminiHochbergCorrection {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kPValues[] = {0x1.47ae147ae147bp-7, 0x1.47ae147ae147bp-5, 0x1.eb851eb851eb8p-6, 0x1.999999999999ap-3, 0x1.47ae147ae147bp-8};
    static constexpr double kAdjusted[] = {0x1.999999999999ap-6, 0x1.999999999999ap-5, 0x1.999999999999ap-5, 0x1.999999999999ap-3, 0x1.999999999999ap-6};
};

/**
 * @brief R: wilcox.test(x, mu = 13.5, exact = FALSE, correct = TRUE)
 */
struct WilcoxonSignedRank {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.8p+3, 0x1.ep+3, 0x1.6p+3, 0x1.2p+4, 0x1.cp+3, 0x1p+4, 0x1.ap+3, 0x1.1p+4};
    static constexpr double kMu0 = 0x1.bp+3;
    static constexpr double kStatistic = 0x1.98p+4;
    static constexpr double kPValue = 0x1.4d0251f6be1fep-2;
};

/**
 * @brief R: wilcox.test(x, y, exact = FALSE, correct = TRUE)
 */
struct MannWhitneyU {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.8p+3, 0x1.ep+3, 0x1.6p+3, 0x1.2p+4, 0x1.cp+3};
    static constexpr double kY[] = {0x1.4p+4, 0x1.1p+4, 0x1.6p+4, 0x1.3p+4, 0x1p+4};
    static constexpr double kStatistic = 0x1p+1;
    static constexpr double kPValue = 0x1.2cc2898c69503p-5;
};

/**
 * @brief R: kruskal.test(groups)
 */
struct KruskalWallis {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kGroupsFlat[] = {0x1.7p+4, 0x1.9p+4, 0x1.6p+4, 0x1.bp+4, 0x1.8p+4, 0x1.ep+4, 0x1.cp+4, 0x1.08p+5, 0x1.fp+4, 0x1.dp+4, 0x1.5p+4, 0x1.3p+4, 0x1.8p+4, 0x1.6p+4, 0x1.4p+4};
    static constexpr std::size_t kGroupsSizes[] = {5, 5, 5};
    static constexpr std::size_t kGroupsCount = 3;
    static constexpr double kStatistic = 0x1.670ad3c602917p+3;
    static constexpr std::size_t kDf = 2;
    static constexpr double kPValue = 0x1.dfd8b328b519cp-9;
};

/**
 * @brief R: shapiro.test(x)
 *
 * statcpp and R use different Shapiro-Wilk approximations; only agreement to a few percent is
 * expected.
 */
struct ShapiroWilk {
    static constexpr double kRtol = 1e-06;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 0.05;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kStatistic = 0x1.ee6a92f7dab3bp-1;
    static constexpr double kPValue = 0x1.b94da3f6cd6bp-1;
};

/**
 * @brief R: nortest::lillie.test(x), p ~ 0.002 (inside the published range)
 */
struct LillieforsTest {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+1, 0x1p+1, 0x1.8p+1, 0x1.4p+2, 0x1.2p+3, 0x1.4p+4, 0x1.68p+5};
    static constexpr double kStatistic = 0x1.484db23b82578p-2;
    static constexpr double kPValue = 0x1.37345584f0a3p-9;
};

/**
 * @brief R: nortest::lillie.test(x), p ~ 0.028 (just below the 0.05 level)
 */
struct LillieforsTestNearAlpha {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.999999999999ap-5, 0x1.1eb851eb851ecp-3, 0x1.25c28f5c28f5cp+2, 0x1.3851eb851eb85p-1, 0x1.6666666666666p-2, 0x1.bd70a3d70a3d7p-1, 0x1.4666666666666p+1, 0x1.2e147ae147ae1p+0, 0x1.570a3d70a3d71p-1};
    static constexpr double kStatistic = 0x1.28828282719fdp-2;
    static constexpr double kPValue = 0x1.d223c9e3ad35fp-6;
};

/**
 * @brief R: nortest::lillie.test(x), p ~ 0.73; D statistic only
 *
 * The Dallal-Wilkinson approximation is published only for p <= 0.10, so above that level
 * statcpp reports a value that indicates consistency with normality rather than an accurate
 * p-value. Only the D statistic is compared here. Every conventional significance level lies
 * inside the published range, which the two cases above cover.
 */
struct LillieforsTestUpperRange {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2};
    static constexpr double kStatistic = 0x1.578f8708e03a6p-3;
};

/**
 * @brief R: nortest::lillie.test(x) (ks_test_normal forwards to lilliefors_test)
 */
struct KsTestNormal {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+1, 0x1p+1, 0x1.8p+1, 0x1.4p+2, 0x1.2p+3, 0x1.4p+4, 0x1.68p+5};
    static constexpr double kStatistic = 0x1.484db23b82578p-2;
    static constexpr double kPValue = 0x1.37345584f0a3p-9;
};

/**
 * @brief R: bartlett.test(groups)
 */
struct BartlettTest {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kGroupsFlat[] = {0x1.4p+3, 0x1.5p+3, 0x1.3p+3, 0x1.4666666666666p+3, 0x1.399999999999ap+3, 0x1p+2, 0x1p+4, 0x1p+3, 0x1.8p+3, 0x1.4p+4, 0x1.6p+3, 0x1.2p+3, 0x1.ap+3, 0x1.cp+2, 0x1.ep+3};
    static constexpr std::size_t kGroupsSizes[] = {5, 5, 5};
    static constexpr std::size_t kGroupsCount = 3;
    static constexpr double kStatistic = 0x1.f98d7089e206dp+3;
    static constexpr double kDf = 0x1p+1;
    static constexpr double kPValue = 0x1.850a9aac8080dp-12;
};

/**
 * @brief R: car::leveneTest(y, group, center = median)
 */
struct LeveneTest {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kGroupsFlat[] = {0x1.4p+3, 0x1.5p+3, 0x1.3p+3, 0x1.4666666666666p+3, 0x1.399999999999ap+3, 0x1p+2, 0x1p+4, 0x1p+3, 0x1.8p+3, 0x1.4p+4, 0x1.6p+3, 0x1.2p+3, 0x1.ap+3, 0x1.cp+2, 0x1.ep+3};
    static constexpr std::size_t kGroupsSizes[] = {5, 5, 5};
    static constexpr std::size_t kGroupsCount = 3;
    static constexpr double kStatistic = 0x1.5d82942a5a935p+2;
    static constexpr double kPValue = 0x1.5143be739ef89p-6;
};

/**
 * @brief R: fisher.test(matrix(c(a, b, c, d), nrow = 2, byrow = TRUE))
 */
struct FisherExactTest {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr std::size_t kA = 8;
    static constexpr std::size_t kB = 2;
    static constexpr std::size_t kC = 1;
    static constexpr std::size_t kD = 5;
    static constexpr double kPValue = 0x1.1e6efe35b4cfap-5;
};

/**
 * @brief R: rank(x, ties.method = "average")
 */
struct ComputeRanksWithTies {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.8p+1, 0x1p+0, 0x1p+2, 0x1p+0, 0x1.4p+2, 0x1.2p+3, 0x1p+1, 0x1.8p+2, 0x1.4p+2, 0x1.8p+1};
    static constexpr double kRanks[] = {0x1.2p+2, 0x1.8p+0, 0x1.8p+2, 0x1.8p+0, 0x1.ep+2, 0x1.4p+3, 0x1.8p+1, 0x1.2p+3, 0x1.ep+2, 0x1.2p+2};
};

/**
 * @brief R: summary(aov(y ~ g)); eta^2, omega^2 and Cohen's f from the standard closed forms
 */
struct OneWayAnova {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kGroupsFlat[] = {0x1.7p+4, 0x1.9p+4, 0x1.6p+4, 0x1.bp+4, 0x1.8p+4, 0x1.ep+4, 0x1.cp+4, 0x1.08p+5, 0x1.fp+4, 0x1.dp+4, 0x1.5p+4, 0x1.3p+4, 0x1.8p+4, 0x1.6p+4, 0x1.4p+4};
    static constexpr std::size_t kGroupsSizes[] = {5, 5, 5};
    static constexpr std::size_t kGroupsCount = 3;
    static constexpr double kFStatistic = 0x1.c60dd67c8a60bp+4;
    static constexpr double kPValue = 0x1.da2635bc8cd88p-16;
    static constexpr double kSsBetween = 0x1.a400000000003p+7;
    static constexpr double kDfBetween = 0x1p+1;
    static constexpr double kMsBetween = 0x1.a400000000003p+6;
    static constexpr double kSsWithin = 0x1.6333333333338p+5;
    static constexpr double kDfWithin = 0x1.8p+3;
    static constexpr double kMsWithin = 0x1.d9999999999ap+1;
    static constexpr double kSsTotal = 0x1.fccccccccccd1p+7;
    static constexpr double kEtaSquared = 0x1.a6a439f656f18p-1;
    static constexpr double kOmegaSquared = 0x1.91e73412a5a41p-1;
    static constexpr double kCohensF = 0x1.165fa7dd78d9bp+1;
};

/**
 * @brief R: TukeyHSD(aov(y ~ g))
 *
 * Sign flipped and bounds swapped relative to R: TukeyHSD reports mean[j] - mean[i]. The
 * studentized range distribution is evaluated by different approximations, hence the looser
 * tolerance.
 */
struct TukeyHsd {
    static constexpr double kRtol = 1e-06;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kGroupsFlat[] = {0x1.7p+4, 0x1.9p+4, 0x1.6p+4, 0x1.bp+4, 0x1.8p+4, 0x1.ep+4, 0x1.cp+4, 0x1.08p+5, 0x1.fp+4, 0x1.dp+4, 0x1.5p+4, 0x1.3p+4, 0x1.8p+4, 0x1.6p+4, 0x1.4p+4};
    static constexpr std::size_t kGroupsSizes[] = {5, 5, 5};
    static constexpr std::size_t kGroupsCount = 3;
    static constexpr double kMeanDiff[] = {-0x1.8000000000004p+2, 0x1.7fffffffffff8p+1, 0x1.2p+3};
    static constexpr double kPValue[] = {0x1.e9ace2446a4p-11, 0x1.2322188047128p-4, 0x1.8111857758p-16};
    static constexpr double kLower[] = {-0x1.27dbec963a439p+3, -0x1.f6fb258e90e3p-3, 0x1.704826d38b792p+2};
    static constexpr double kUpper[] = {-0x1.60904da716f2dp+1, 0x1.8fb7d92c7486ap+2, 0x1.87dbec963a437p+3};
};

/**
 * @brief R: manual, pooled-MSE t statistic with Bonferroni adjustment (matches pairwise.t.test)
 */
struct BonferroniPosthoc {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kGroupsFlat[] = {0x1.7p+4, 0x1.9p+4, 0x1.6p+4, 0x1.bp+4, 0x1.8p+4, 0x1.ep+4, 0x1.cp+4, 0x1.08p+5, 0x1.fp+4, 0x1.dp+4, 0x1.5p+4, 0x1.3p+4, 0x1.8p+4, 0x1.6p+4, 0x1.4p+4};
    static constexpr std::size_t kGroupsSizes[] = {5, 5, 5};
    static constexpr std::size_t kGroupsCount = 3;
    static constexpr double kMeanDiff[] = {-0x1.8p+2, 0x1.8p+1, 0x1.2p+3};
    static constexpr double kStatistic[] = {-0x1.3ba563e6ca4b6p+2, 0x1.3ba563e6ca4b6p+1, 0x1.d97815da2f712p+2};
    static constexpr double kPValue[] = {0x1.10b051be9f4p-10, 0x1.6d1731a474e4p-4, 0x1.a19f9d2bap-16};
    static constexpr double kCrossCheck[] = {0x1.10b051be9f189p-10, 0x1.6d1731a474e4ep-4, 0x1.a19f9d2b9cfd4p-16};
};

/**
 * @brief R: manual, Scheffe F = t^2 / df_between, p = 1 - pf(F, df_between, df_error)
 *
 * statcpp stores the signed t statistic in posthoc_comparison::statistic and uses F = t^2 /
 * df_between only to obtain the p-value.
 */
struct ScheffePosthoc {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kGroupsFlat[] = {0x1.7p+4, 0x1.9p+4, 0x1.6p+4, 0x1.bp+4, 0x1.8p+4, 0x1.ep+4, 0x1.cp+4, 0x1.08p+5, 0x1.fp+4, 0x1.dp+4, 0x1.5p+4, 0x1.3p+4, 0x1.8p+4, 0x1.6p+4, 0x1.4p+4};
    static constexpr std::size_t kGroupsSizes[] = {5, 5, 5};
    static constexpr std::size_t kGroupsCount = 3;
    static constexpr double kMeanDiff[] = {-0x1.8p+2, 0x1.8p+1, 0x1.2p+3};
    static constexpr double kStatistic[] = {-0x1.3ba563e6ca4b6p+2, 0x1.3ba563e6ca4b6p+1, 0x1.d97815da2f712p+2};
    static constexpr double kFStatistic[] = {0x1.85306eb3e4529p+3, 0x1.85306eb3e4529p+1, 0x1.b5d67c8a60ddp+4};
    static constexpr double kPValue[] = {0x1.54c14230ce8p-10, 0x1.5e06cfebf0b5p-4, 0x1.1bb38235fcp-15};
};

/**
 * @brief R: manual, Bonferroni-adjusted t against the control group
 *
 * statcpp's dunnett_posthoc applies a Bonferroni approximation, not the classical Dunnett
 * procedure based on the multivariate t distribution. It therefore does not match
 * multcomp::glht(..., mcp(g = "Dunnett")) and is compared against the closed form statcpp
 * implements.
 */
struct DunnettPosthoc {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kGroupsFlat[] = {0x1.7p+4, 0x1.9p+4, 0x1.6p+4, 0x1.bp+4, 0x1.8p+4, 0x1.ep+4, 0x1.cp+4, 0x1.08p+5, 0x1.fp+4, 0x1.dp+4, 0x1.5p+4, 0x1.3p+4, 0x1.8p+4, 0x1.6p+4, 0x1.4p+4};
    static constexpr std::size_t kGroupsSizes[] = {5, 5, 5};
    static constexpr std::size_t kGroupsCount = 3;
    static constexpr std::size_t kControlGroup = 0;
    static constexpr double kMeanDiff[] = {0x1.8p+2, -0x1.8p+1};
    static constexpr double kStatistic[] = {0x1.3ba563e6ca4b6p+2, -0x1.3ba563e6ca4b6p+1};
    static constexpr double kPValue[] = {0x1.6b95c2537fp-11, 0x1.e6c99785f13p-5};
};

/**
 * @brief R: summary(aov(y ~ a * b)); partial eta^2 = SS_effect / (SS_effect + SS_error)
 */
struct TwoWayAnova {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kValues[] = {0x1.cp+3, 0x1p+4, 0x1.ep+3, 0x1.2p+4, 0x1.4p+4, 0x1.3p+4, 0x1.6p+4, 0x1.5p+4, 0x1.7p+4, 0x1.6p+3, 0x1.ap+3, 0x1.8p+3, 0x1.5p+4, 0x1.4p+4, 0x1.6p+4, 0x1.ep+3, 0x1p+4, 0x1.cp+3};
    static constexpr std::size_t kLevelsA = 2;
    static constexpr std::size_t kLevelsB = 3;
    static constexpr std::size_t kReps = 3;
    static constexpr double kFA = 0x1.ffffffffffff4p+4;
    static constexpr double kPA = 0x1.bd1ba4f84c803p-14;
    static constexpr double kFB = 0x1.15ffffffffffdp+6;
    static constexpr double kPB = 0x1.0e795db92a43p-22;
    static constexpr double kFInteraction = 0x1.e7ffffffffff5p+4;
    static constexpr double kPInteraction = 0x1.4b083cd1f03dcp-16;
    static constexpr double kSsA = 0x1.ffffffffffffep+4;
    static constexpr double kSsB = 0x1.1600000000002p+7;
    static constexpr double kSsInteraction = 0x1.e7fffffffffffp+5;
    static constexpr double kSsError = 0x1.8000000000008p+3;
    static constexpr double kPartialEtaSquaredA = 0x1.745d1745d1743p-1;
    static constexpr double kPartialEtaSquaredB = 0x1.d74fae9f5d3ecp-1;
    static constexpr double kPartialEtaSquaredInteraction = 0x1.abd5eaf57abd5p-1;
};

/**
 * @brief R: car::Anova(lm(y ~ x + g), type = 2) (partial / type II sums of squares)
 *
 * statcpp uses partial (type II) sums of squares. Comparing against R's sequential
 * summary(aov(y ~ x + g)) would mismatch on the covariate row.
 */
struct OneWayAncova {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kYFlat[] = {0x1.7p+4, 0x1.9p+4, 0x1.6p+4, 0x1.bp+4, 0x1.8p+4, 0x1.ep+4, 0x1.cp+4, 0x1.08p+5, 0x1.fp+4, 0x1.dp+4, 0x1.5p+4, 0x1.3p+4, 0x1.8p+4, 0x1.6p+4, 0x1.4p+4};
    static constexpr std::size_t kYSizes[] = {5, 5, 5};
    static constexpr std::size_t kYCount = 3;
    static constexpr double kXFlat[] = {0x1.4p+3, 0x1.8p+3, 0x1.2p+3, 0x1.ep+3, 0x1.6p+3, 0x1.ep+3, 0x1.ap+3, 0x1.2p+4, 0x1p+4, 0x1.8p+3, 0x1p+3, 0x1.8p+2, 0x1.8p+3, 0x1.2p+3, 0x1.cp+2};
    static constexpr std::size_t kXSizes[] = {5, 5, 5};
    static constexpr std::size_t kXCount = 3;
    static constexpr double kSsCovariate = 0x1.50e72f6e40b5p+5;
    static constexpr double kDfCovariate = 0x1p+0;
    static constexpr double kFCovariate = 0x1.9516860afcb43p+7;
    static constexpr double kPCovariate = 0x1.541287f41cea9p-26;
    static constexpr double kSsTreatment = 0x1.3cc93e0eba8e7p+4;
    static constexpr double kDfTreatment = 0x1p+1;
    static constexpr double kFTreatment = 0x1.7ce64c2989b87p+5;
    static constexpr double kPTreatment = 0x1.0127a8d3be478p-18;
    static constexpr double kSsError = 0x1.24c03c4f27e47p+1;
    static constexpr double kDfError = 0x1.6p+3;
};

}  // namespace statcpp_test::r_ref
