/**
 * @file r_reference_conditional.hpp
 * @brief R reference values for functions that require glmnet, mice or naniar.
 *
 * Generated by generate_r_reference.R against R 4.4.2.
 * Do not edit by hand: re-run the script instead.
 *
 * Values are C++17 hexadecimal floating-point literals and are therefore
 * bit-identical to the values R produced.
 */

#pragma once

#include <cstddef>

#include "r_compare.hpp"

namespace statcpp_test::r_ref {

/**
 * @brief R: glmnet(alpha = 1, lambda = lambda / n, standardize = TRUE)
 *
 * glmnet scales the residual sum of squares by 1/(2n) while statcpp scales it by 1/2, so the
 * penalty maps as s = lambda / n. Both standardise predictors with the population standard
 * deviation.
 */
struct LassoRegression {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-05;
    static constexpr double kXFlat[] = {0x1.0cccccccccccdp+1, 0x1.6p+2, 0x1.b333333333333p+1, 0x1.0666666666666p+2, 0x1.ccccccccccccdp+0, 0x1.b333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.999999999999ap+1, 0x1.2666666666666p+2, 0x1.399999999999ap+2, 0x1.b99999999999ap+2, 0x1.4cccccccccccdp+1, 0x1.a666666666666p+1, 0x1.4666666666666p+2, 0x1.c666666666666p+2, 0x1.199999999999ap+1, 0x1.7333333333333p+2, 0x1.d99999999999ap+1, 0x1.0cccccccccccdp+3, 0x1.e666666666666p+0, 0x1.8cccccccccccdp+2, 0x1.b333333333333p+1, 0x1.2333333333333p+3, 0x1.6666666666666p+0};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kY[] = {0x1.a333333333333p+3, 0x1.c666666666666p+3, 0x1.799999999999ap+3, 0x1.2666666666666p+4, 0x1.2p+4, 0x1.64ccccccccccdp+4, 0x1.dcccccccccccdp+3, 0x1.9666666666666p+4, 0x1.399999999999ap+4, 0x1.c8p+4, 0x1.6333333333333p+4, 0x1.cb33333333333p+4};
    static constexpr double kLambda = 0x1.4p+2;
    static constexpr double kCoefficients[] = {0x1.f9ebc620fa63ap+2, 0x1.1cecc1341d59ap+1, 0x0p+0};
    static constexpr double kMse = 0x1.0d1244f2f3806p+0;
};

/**
 * @brief R: independent coordinate descent on statcpp's objective, (1/2) RSS + a*lam |b|_1 + (1-a)*lam/2 |b|_2^2
 *
 * Unlike the lasso, statcpp's elastic net does not coincide with glmnet under s = lambda / n:
 * its ridge term is applied on a different scale. glmnet_contrast records what glmnet returns
 * so the size of the gap is visible; it is NOT expected to match.
 */
struct ElasticNetRegression {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-05;
    static constexpr double kXFlat[] = {0x1.0cccccccccccdp+1, 0x1.6p+2, 0x1.b333333333333p+1, 0x1.0666666666666p+2, 0x1.ccccccccccccdp+0, 0x1.b333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.999999999999ap+1, 0x1.2666666666666p+2, 0x1.399999999999ap+2, 0x1.b99999999999ap+2, 0x1.4cccccccccccdp+1, 0x1.a666666666666p+1, 0x1.4666666666666p+2, 0x1.c666666666666p+2, 0x1.199999999999ap+1, 0x1.7333333333333p+2, 0x1.d99999999999ap+1, 0x1.0cccccccccccdp+3, 0x1.e666666666666p+0, 0x1.8cccccccccccdp+2, 0x1.b333333333333p+1, 0x1.2333333333333p+3, 0x1.6666666666666p+0};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kY[] = {0x1.a333333333333p+3, 0x1.c666666666666p+3, 0x1.799999999999ap+3, 0x1.2666666666666p+4, 0x1.2p+4, 0x1.64ccccccccccdp+4, 0x1.dcccccccccccdp+3, 0x1.9666666666666p+4, 0x1.399999999999ap+4, 0x1.c8p+4, 0x1.6333333333333p+4, 0x1.cb33333333333p+4};
    static constexpr double kLambda = 0x1.4p+2;
    static constexpr double kAlpha = 0x1p-1;
    static constexpr double kCoefficients[] = {0x1.0f2bb8151e97ep+4, 0x1.50715ead74f81p+0, -0x1.1f2f5b6559613p+0};
    static constexpr double kMse = 0x1.052f29cfffbb1p+1;
    static constexpr double kGlmnetContrast[] = {0x1.62197475feb4dp+3, 0x1.f32f0df99cca5p+0, -0x1.cfbb38413a4f6p-2};
};

/**
 * @brief R: colMeans(is.na), table of the missingness patterns, cross-checked with mice::md.pattern
 *
 * pattern_counts is compared as a sorted vector: statcpp and R enumerate the patterns in
 * different orders. mice_n_patterns cross-checks the pattern count against mice::md.pattern.
 */
struct MissingPatterns {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kXFlat[] = {0x1.3333333333333p+0, 0x1.3333333333333p+2, 0x1.8cccccccccccdp+1, 0x1.2p+2, ::statcpp_test::kNaN, 0x1.acccccccccccdp+2, 0x1.d333333333333p+2, 0x1.2333333333333p+3, ::statcpp_test::kNaN, ::statcpp_test::kNaN, 0x1.7333333333333p+3, 0x1.9cccccccccccdp+3, 0x1.a333333333333p+3, 0x1.0cccccccccccdp+3, 0x1.6p+2, 0x1.0cccccccccccdp+4, ::statcpp_test::kNaN, ::statcpp_test::kNaN, 0x1.3666666666666p+4, 0x1.9666666666666p+3, 0x1.54ccccccccccdp+4, 0x1.699999999999ap+4, 0x1.7e66666666666p+4, 0x1.199999999999ap+3, ::statcpp_test::kNaN, 0x1.8cccccccccccdp+2, 0x1.c333333333333p+3, 0x1.3666666666666p+3, 0x1.e99999999999ap+3, 0x1.6666666666666p+3};
    static constexpr std::size_t kXRows = 10;
    static constexpr std::size_t kXCols = 3;
    static constexpr double kMissingRates[] = {0x1.999999999999ap-3, 0x1.999999999999ap-3, 0x1.999999999999ap-3};
    static constexpr double kOverallMissingRate = 0x1.999999999999ap-3;
    static constexpr double kNCompleteCases = 0x1.4p+2;
    static constexpr double kNPatterns = 0x1.4p+2;
    static constexpr double kPatternCounts[] = {0x1.4p+2, 0x1p+1, 0x1p+0, 0x1p+0, 0x1p+0};
    static constexpr double kMiceNPatterns = 0x1.4p+2;
};

/**
 * @brief R: reproduction of statcpp's pairwise Welch accumulation with the Wilson-Hilferty p-value
 *
 * statcpp's test_mcar_simple is not Little's MCAR test. naniar_contrast records what
 * naniar::mcar_test reports for the same data; it is NOT expected to match, and the reference
 * reproduces the heuristic statcpp actually implements.
 */
struct McarSimple {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-09;
    static constexpr double kXFlat[] = {0x1.3333333333333p+0, 0x1.3333333333333p+2, 0x1.8cccccccccccdp+1, 0x1.2p+2, ::statcpp_test::kNaN, 0x1.acccccccccccdp+2, 0x1.d333333333333p+2, 0x1.2333333333333p+3, ::statcpp_test::kNaN, ::statcpp_test::kNaN, 0x1.7333333333333p+3, 0x1.9cccccccccccdp+3, 0x1.a333333333333p+3, 0x1.0cccccccccccdp+3, 0x1.6p+2, 0x1.0cccccccccccdp+4, ::statcpp_test::kNaN, ::statcpp_test::kNaN, 0x1.3666666666666p+4, 0x1.9666666666666p+3, 0x1.54ccccccccccdp+4, 0x1.699999999999ap+4, 0x1.7e66666666666p+4, 0x1.199999999999ap+3, ::statcpp_test::kNaN, 0x1.8cccccccccccdp+2, 0x1.c333333333333p+3, 0x1.3666666666666p+3, 0x1.e99999999999ap+3, 0x1.6666666666666p+3};
    static constexpr std::size_t kXRows = 10;
    static constexpr std::size_t kXCols = 3;
    static constexpr double kChiSquare = 0x1.91d1567969c61p+1;
    static constexpr double kDf = 0x1p+2;
    static constexpr double kPValue = 0x1.13133567b08adp-1;
    static constexpr double kNaniarContrast = 0x1.7dfb89e9139bep-1;
};

}  // namespace statcpp_test::r_ref
