/**
 * @file r_reference_regression.hpp
 * @brief R reference values for linear regression, GLM and model selection.
 *
 * Generated by generate_r_reference.R against R 4.4.2.
 * Do not edit by hand: re-run the script instead.
 *
 * Values are C++17 hexadecimal floating-point literals and are therefore
 * bit-identical to the values R produced.
 */

#pragma once

#include <cstddef>

#include "r_compare.hpp"

namespace statcpp_test::r_ref {

/**
 * @brief R: lm(y ~ x) and summary(lm)
 *
 * Measured worst-case agreement on the p-values is 1.9e-08 relative; they pass through
 * statcpp's own incomplete beta function.
 */
struct SimpleLinearRegression {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-07;
    static constexpr double kX[] = {0x1.3333333333333p+0, 0x1.4p+1, 0x1.8cccccccccccdp+1, 0x1.3333333333333p+2, 0x1.5333333333333p+2, 0x1.acccccccccccdp+2, 0x1.ccccccccccccdp+2, 0x1.1cccccccccccdp+3, 0x1.2cccccccccccdp+3, 0x1.4333333333333p+3, 0x1.7333333333333p+3, 0x1.899999999999ap+3};
    static constexpr double kY[] = {0x1.e666666666666p+1, 0x1.399999999999ap+2, 0x1.ccccccccccccdp+2, 0x1.1333333333333p+3, 0x1.8333333333333p+3, 0x1.8cccccccccccdp+3, 0x1p+4, 0x1.1333333333333p+4, 0x1.2666666666666p+4, 0x1.5e66666666666p+4, 0x1.619999999999ap+4, 0x1.a4ccccccccccdp+4};
    static constexpr double kIntercept = 0x1.260bc30ebd1abp-1;
    static constexpr double kSlope = 0x1.f93f892cd64ffp+0;
    static constexpr double kInterceptSe = 0x1.9805fdbbf53cbp-1;
    static constexpr double kSlopeSe = 0x1.a53b71d4658c1p-4;
    static constexpr double kInterceptT = 0x1.70fa487adb89ep-1;
    static constexpr double kSlopeT = 0x1.330f583c2e34bp+4;
    static constexpr double kInterceptP = 0x1.f3538df13675cp-2;
    static constexpr double kSlopeP = 0x1.b969c771e8a58p-29;
    static constexpr double kRSquared = 0x1.f27745c96dea3p-1;
    static constexpr double kAdjRSquared = 0x1.f11cccc3f8e8p-1;
    static constexpr double kResidualSe = 0x1.3d27319443ee9p+0;
    static constexpr double kFStatistic = 0x1.704dce8bcc491p+8;
    static constexpr double kFPValue = 0x1.b969c771e8a58p-29;
    static constexpr double kDfRegression = 0x1p+0;
    static constexpr double kDfResidual = 0x1.4p+3;
    static constexpr double kSsTotal = 0x1.2250888888888p+9;
    static constexpr double kSsRegression = 0x1.1aa3f61699df7p+9;
    static constexpr double kSsResidual = 0x1.eb249c7baa449p+3;
    static constexpr double kPredictAt = 0x1.ep+2;
    static constexpr double kPredictValue = 0x1.ec0c4ccaf4bcap+3;
    static constexpr double kRSquaredFn = 0x1.f27745c96dea3p-1;
    static constexpr double kAdjustedRSquaredFn = 0x1.f11cccc3f8e8p-1;
    static constexpr double kPress = 0x1.67a482c3953p+4;
    static constexpr double kAicLinear = 0x1.580fa4ba113d5p+5;
    static constexpr double kBicLinear = 0x1.63b2e8f08c18cp+5;
    static constexpr std::size_t kN = 12;
};

/**
 * @brief R: predict(lm, interval = "confidence") and interval = "prediction"
 */
struct RegressionIntervals {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.3333333333333p+0, 0x1.4p+1, 0x1.8cccccccccccdp+1, 0x1.3333333333333p+2, 0x1.5333333333333p+2, 0x1.acccccccccccdp+2, 0x1.ccccccccccccdp+2, 0x1.1cccccccccccdp+3, 0x1.2cccccccccccdp+3, 0x1.4333333333333p+3, 0x1.7333333333333p+3, 0x1.899999999999ap+3};
    static constexpr double kY[] = {0x1.e666666666666p+1, 0x1.399999999999ap+2, 0x1.ccccccccccccdp+2, 0x1.1333333333333p+3, 0x1.8333333333333p+3, 0x1.8cccccccccccdp+3, 0x1p+4, 0x1.1333333333333p+4, 0x1.2666666666666p+4, 0x1.5e66666666666p+4, 0x1.619999999999ap+4, 0x1.a4ccccccccccdp+4};
    static constexpr double kXNew = 0x1.ep+2;
    static constexpr double kConfidence = 0x1.e666666666666p-1;
    static constexpr double kCiFit = 0x1.ec0c4ccaf4bcap+3;
    static constexpr double kCiLower = 0x1.d233d02cd322ep+3;
    static constexpr double kCiUpper = 0x1.02f264b48b2b3p+4;
    static constexpr double kPiFit = 0x1.ec0c4ccaf4bcap+3;
    static constexpr double kPiLower = 0x1.90030b7115683p+3;
    static constexpr double kPiUpper = 0x1.240ac7126a089p+4;
};

/**
 * @brief R: residuals, residuals/sigma, rstandard, hatvalues, cooks.distance and Durbin-Watson
 *
 * statcpp's standardized_residuals is e/sigma; its studentized_residuals is R's rstandard.
 * rstudent_r records R's externally studentized residual, which statcpp does not provide.
 */
struct ResidualDiagnostics {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.3333333333333p+0, 0x1.4p+1, 0x1.8cccccccccccdp+1, 0x1.3333333333333p+2, 0x1.5333333333333p+2, 0x1.acccccccccccdp+2, 0x1.ccccccccccccdp+2, 0x1.1cccccccccccdp+3, 0x1.2cccccccccccdp+3, 0x1.4333333333333p+3, 0x1.7333333333333p+3, 0x1.899999999999ap+3};
    static constexpr double kY[] = {0x1.e666666666666p+1, 0x1.399999999999ap+2, 0x1.ccccccccccccdp+2, 0x1.1333333333333p+3, 0x1.8333333333333p+3, 0x1.8cccccccccccdp+3, 0x1p+4, 0x1.1333333333333p+4, 0x1.2666666666666p+4, 0x1.5e66666666666p+4, 0x1.619999999999ap+4, 0x1.a4ccccccccccdp+4};
    static constexpr double kResiduals[] = {0x1.b6f55a1f40889p-1, -0x1.377ca4221fe09p-1, 0x1.03d0b741abc0fp-1, -0x1.729d40c4fcda7p+0, 0x1.10c2faa497fdap+0, -0x1.65c92bcd60d87p+0, 0x1.3730a935cd99p+0, -0x1.e1104cc670aaap-1, -0x1.73e96f8ce094dp-1, 0x1.645ece9a2ce4ap+0, -0x1.5e4d4bf5e15f4p+0, 0x1.73396d9def022p+0};
    static constexpr double kStandardized[] = {0x1.6251a66909401p-1, -0x1.f6da486113c5p-2, 0x1.a36f9e81f1e68p-2, -0x1.2b272101c94b6p+0, 0x1.b8560a6aaf5c4p-1, -0x1.20cc47ac178fap+0, 0x1.f65f9f8aefc4ap-1, -0x1.844e36a355a85p-1, -0x1.2c3342b4ed639p-1, 0x1.1fa7c95a46795p+0, -0x1.1ac1d282c9241p+0, 0x1.2ba530caf952ep+0};
    static constexpr double kStudentized[] = {0x1.aa4c0c4339f4fp-1, -0x1.1c5dee9fb20b6p-1, 0x1.d05da9fa46594p-2, -0x1.3de5a1739841cp+0, 0x1.d08cc10b62d92p-1, -0x1.2db27205ed15ep+0, 0x1.066e3d51f70dcp+0, -0x1.9ba6e5ab79fccp-1, -0x1.4106f97dd5206p-1, 0x1.3885441a0b54cp+0, -0x1.430ede65d9fd2p+0, 0x1.61ba61720f215p+0};
    static constexpr double kRstudentR[] = {0x1.a336704167435p-1, -0x1.1208abba67be2p-1, 0x1.bd230ff4c00dbp-2, -0x1.47ecd127c64ebp+0, 0x1.cc0dd1134864fp-1, -0x1.346f1d0728496p+0, 0x1.072ce9e082442p+0, -0x1.93cbefa6b8706p-1, -0x1.36b8e50915bfp-1, 0x1.4165dd9c1d3ecp+0, -0x1.4e3f71ff8d17ep+0, 0x1.751326894036cp+0};
    static constexpr double kHatValues[] = {0x1.3c9a07696f35cp-2, 0x1.befe1f6e98de6p-3, 0x1.79231f8d145cp-3, 0x1.d4c8c69214ff1p-4, 0x1.9fdd0c7aa1185p-4, 0x1.56c31f38c855dp-4, 0x1.5777c22133b19p-4, 0x1.c36d1f095d924p-4, 0x1.011ce0eb583f4p-3, 0x1.38ed36eeeab7fp-3, 0x1.df1913bdadb02p-3, 0x1.21304e70bded6p-2};
    static constexpr double kCooks[] = {0x1.3db652f2f632cp-3, 0x1.60c3cac503a84p-5, 0x1.7c3fff191ae0cp-6, 0x1.98270df3f5879p-4, 0x1.7d0a70e6d0357p-5, 0x1.03c396857e515p-4, 0x1.89fa0fa5095d7p-5, 0x1.47f5aca34c22dp-5, 0x1.ce5e9ed54875ep-6, 0x1.133be00bdebc3p-3, 0x1.f1fa3e85e07a6p-3, 0x1.80b5feea3d68cp-2};
    static constexpr double kDurbinWatson = 0x1.aabd4b672da1dp+1;
};

/**
 * @brief R: lm(y ~ x1 + x2) and summary(lm)
 *
 * loocv_mse uses the algebraic shortcut for leave-one-out cross-validation, which is exact for
 * linear models.
 */
struct MultipleLinearRegression {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kXFlat[] = {0x1.0cccccccccccdp+1, 0x1.6p+2, 0x1.b333333333333p+1, 0x1.0666666666666p+2, 0x1.ccccccccccccdp+0, 0x1.b333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.999999999999ap+1, 0x1.2666666666666p+2, 0x1.399999999999ap+2, 0x1.b99999999999ap+2, 0x1.4cccccccccccdp+1, 0x1.a666666666666p+1, 0x1.4666666666666p+2, 0x1.c666666666666p+2, 0x1.199999999999ap+1, 0x1.7333333333333p+2, 0x1.d99999999999ap+1, 0x1.0cccccccccccdp+3, 0x1.e666666666666p+0, 0x1.8cccccccccccdp+2, 0x1.b333333333333p+1, 0x1.2333333333333p+3, 0x1.6666666666666p+0};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kY[] = {0x1.a333333333333p+3, 0x1.c666666666666p+3, 0x1.799999999999ap+3, 0x1.2666666666666p+4, 0x1.2p+4, 0x1.64ccccccccccdp+4, 0x1.dcccccccccccdp+3, 0x1.9666666666666p+4, 0x1.399999999999ap+4, 0x1.c8p+4, 0x1.6333333333333p+4, 0x1.cb33333333333p+4};
    static constexpr double kXNew[] = {0x1.4p+2, 0x1p+2};
    static constexpr double kCoefficients[] = {0x1.07c884a25c956p+2, 0x1.54eb7cf5345cep+1, 0x1.8eca1eda3494ap-2};
    static constexpr double kCoefficientSe[] = {0x1.2e50afece04e2p+2, 0x1.c4e6630531bcep-2, 0x1.4b5776fd233bep-1};
    static constexpr double kTStatistics[] = {0x1.bebe1361ca577p-1, 0x1.816849251f3f3p+2, 0x1.341c805a5219p-1};
    static constexpr double kPValues[] = {0x1.9f528be667d3p-2, 0x1.9d62a396485p-13, 0x1.1fd4ebfa9eccap-1};
    static constexpr double kRSquared = 0x1.f1e85061d2d06p-1;
    static constexpr double kAdjRSquared = 0x1.eec69b223a8cep-1;
    static constexpr double kResidualSe = 0x1.0f7d75be240cfp+0;
    static constexpr double kFStatistic = 0x1.3dfb5d56d301ep+7;
    static constexpr double kFPValue = 0x1.98f90d3e6088ap-24;
    static constexpr double kDfRegression = 0x1p+1;
    static constexpr double kDfResidual = 0x1.2p+3;
    static constexpr double kSsTotal = 0x1.6fbfc962fc964p+8;
    static constexpr double kSsRegression = 0x1.65a087a011c2cp+8;
    static constexpr double kSsResidual = 0x1.43e8385d5a6f4p+3;
    static constexpr double kPredictValue = 0x1.2ff1f12f7b28bp+4;
    static constexpr double kAicLinear = 0x1.40192e613ed5bp+5;
    static constexpr double kBicLinear = 0x1.4f9d89548d4fap+5;
    static constexpr std::size_t kN = 12;
    static constexpr double kVif[] = {0x1.564f51aea2e99p+3, 0x1.564f51aea2e99p+3};
    static constexpr double kCorDeterminant = 0x1.7ee7917d79655p-4;
    static constexpr double kLoocvMse = 0x1.611a917963f0ap+0;
};

/**
 * @brief R: glm(y ~ x1 + x2, family = binomial())
 *
 * Measured agreement with R: deviance and AIC to 1.5e-16, coefficients to 1.5e-08, odds ratios
 * to 2.4e-09, but standard errors only to 3.2e-05. statcpp's IRLS stops on the deviance, which
 * is flat at the optimum, so the coefficients settle around sqrt(machine epsilon) and
 * inverting X'WX amplifies that into the standard errors. odds_ratios and odds_ratios_ci
 * exclude the intercept, so the reference drops the first coefficient. statcpp inverts X'WX
 * explicitly, which is more sensitive to the conditioning of the design than R's QR-based
 * covariance.
 */
struct LogisticRegression {
    static constexpr double kRtol = 1e-07;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 0.0001;
    static constexpr double kXFlat[] = {-0x1.ep+2, -0x1.999999999999ap+0, -0x1.ap+2, -0x1.2666666666666p+1, -0x1.6p+2, -0x1.999999999999ap-3, -0x1.2p+2, -0x1.e666666666666p+0, -0x1.cp+1, 0x1p-1, -0x1.4p+1, -0x1p+0, -0x1.8p+0, 0x1.4cccccccccccdp+0, -0x1p-1, -0x1.999999999999ap-4, 0x1p-1, 0x1.0cccccccccccdp+1, 0x1.8p+0, 0x1p+0, 0x1.4p+1, 0x1.999999999999ap+1, 0x1.cp+1, 0x1.e666666666666p+0, 0x1.2p+2, 0x1.3333333333333p-2, 0x1.6p+2, 0x1.ccccccccccccdp+0, 0x1.ap+2, -0x1p-1, 0x1.ep+2, 0x1.599999999999ap+1};
    static constexpr std::size_t kXRows = 16;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kY[] = {0x0p+0, 0x0p+0, 0x1p+0, 0x0p+0, 0x0p+0, 0x1p+0, 0x0p+0, 0x1p+0, 0x1p+0, 0x0p+0, 0x1p+0, 0x1p+0, 0x0p+0, 0x1p+0, 0x1p+0, 0x1p+0};
    static constexpr double kXNew[] = {0x1.ap+2, 0x1.0cccccccccccdp+2};
    static constexpr double kCoefficients[] = {0x1.14b9098c393fp-3, 0x1.43f94667e3016p-3, 0x1.8cfbe8dba304p-2};
    static constexpr double kCoefficientSe[] = {0x1.40d2b48108593p-1, 0x1.6001990d7423p-3, 0x1.03eb8fd063ffep-1};
    static constexpr double kZStatistics[] = {0x1.b99edf823da1fp-3, 0x1.d739e5b6ea648p-1, 0x1.86ff23946f8abp-1};
    static constexpr double kPValues[] = {0x1.a8965e8975381p-1, 0x1.6df5c0be55807p-2, 0x1.c7bf920a880fp-2};
    static constexpr double kNullDeviance = 0x1.5ee180f7791d8p+4;
    static constexpr double kResidualDeviance = 0x1.15f9bd404cab9p+4;
    static constexpr std::size_t kDfNull = 15;
    static constexpr std::size_t kDfResidual = 13;
    static constexpr double kAic = 0x1.75f9bd404cabap+4;
    static constexpr double kLogLikelihood = -0x1.15f9bd404cabap+3;
    static constexpr double kNullLogLikelihood = -0x1.5ee180f7791d8p+3;
    static constexpr double kOddsRatios[] = {0x1.2be027ba07638p+0, 0x1.793b14834da07p+0};
    static constexpr double kOrCiLower[] = {0x1.ac38a7bb9942dp-1, 0x1.16f1ffdda9d45p-1};
    static constexpr double kOrCiUpper[] = {0x1.a3feb0984f851p+0, 0x1.fe2595e7f8d7p+1};
    static constexpr double kPredictProbability = 0x1.e26ac2cf1b4fcp-1;
    static constexpr double kMcfadden = 0x1.a987849160dc4p-3;
    static constexpr double kNagelkerke = 0x1.5427785980763p-2;
    static constexpr double kDevianceResiduals[] = {-0x1.2c7e4d7730889p-1, -0x1.1d35381e4b74ap-1, 0x1.893a3eaf82fe1p+0, -0x1.615e3a3cce132p-1, -0x1.1566a6100e7bcp+0, 0x1.76479a9dad546p+0, -0x1.5a24017f2d649p+0, 0x1.2b8b1869b27b3p+0, 0x1.905af6c0b7b01p-1, -0x1.832efaa51992dp+0, 0x1.1f02c2bfb05e9p-1, 0x1.50173fc33dce6p-1, -0x1.9aa5881117c13p+0, 0x1.282fc1b18791dp-1, 0x1.9a979189ae307p-1, 0x1.b144f7ed05c34p-2};
    static constexpr double kPearsonResiduals[] = {-0x1.bbeeda7d9eb72p-2, -0x1.a381df03c13ccp-2, 0x1.804b6b3197907p+0, -0x1.098311ee89525p-1, -0x1.c996b6ec0a9b3p-1, 0x1.61f6d87e9b7ffp+0, -0x1.38f69854a202cp+0, 0x1.fb9a03194852cp-1, 0x1.322c95825488cp-1, -0x1.765c4b48b41abp+0, 0x1.a65f4e2d3c56p-2, 0x1.f6179ae541f0ep-2, -0x1.9e64d355ad4ffp+0, 0x1.b504f406b73c6p-2, 0x1.3b50359faf426p-1, 0x1.395a71c37bc7ap-2};
    static constexpr double kResponseResiduals[] = {-0x1.4404612017ed3p-3, -0x1.26535d600dbccp-3, 0x1.62a0f7583fd1cp-1, -0x1.b208802ceb4a6p-3, -0x1.c6b7370e01809p-2, 0x1.5029ac7f48bdep-1, -0x1.32c063e35b29ap-1, 0x1.fb952d02e4d6ap-2, 0x1.0dba42f9c25a6p-2, -0x1.5cdcc75c7d6d2p-1, 0x1.29c5e287ecb9p-3, 0x1.8cf1972e8aa6cp-3, -0x1.729300df43775p-1, 0x1.3b8bd8c9e21e4p-3, 0x1.199395dd618ecp-2, 0x1.5eb6e17e3e1p-4};
};

/**
 * @brief R: glm(y ~ x1 + x2, family = poisson())
 *
 * The intercept p-value is about 1.3e-117. In the extreme tail a p-value is exponentially
 * sensitive to its z statistic, so the 2.5e-09 difference in z becomes 5.9e-08 in p; that sets
 * the tolerance here. Poisson agreement is otherwise far tighter than logistic: coefficients
 * to 4.3e-15 and standard errors to 1.1e-10. incidence_rate_ratios excludes the intercept, so
 * the reference drops the first coefficient. overdispersion is the Pearson chi-square divided
 * by the residual degrees of freedom.
 */
struct PoissonRegression {
    static constexpr double kRtol = 1e-08;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-07;
    static constexpr double kXFlat[] = {-0x1.6p+2, -0x1.b333333333333p+0, -0x1.2p+2, -0x1p+0, -0x1.cp+1, -0x1.6666666666666p+0, -0x1.4p+1, -0x1.3333333333333p-2, -0x1.8p+0, -0x1.199999999999ap+0, -0x1p-1, 0x1.999999999999ap-3, 0x1p-1, -0x1.3333333333333p-1, 0x1.8p+0, 0x1.6666666666666p-1, 0x1.4p+1, -0x1.999999999999ap-4, 0x1.cp+1, 0x1.3333333333333p+0, 0x1.2p+2, 0x1.999999999999ap-2, 0x1.6p+2, 0x1.b333333333333p+0};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kY[] = {0x1p+1, 0x1.8p+1, 0x1p+2, 0x1.8p+2, 0x1.cp+2, 0x1.6p+3, 0x1.8p+3, 0x1.2p+4, 0x1.4p+4, 0x1.bp+4, 0x1.ep+4, 0x1.48p+5};
    static constexpr double kXNew[] = {0x1.ap+2, 0x1.b333333333333p+0};
    static constexpr double kCoefficients[] = {0x1.31d84c4fe266cp+1, 0x1.c5fa1858d0beep-3, 0x1.8075c579c5167p-4};
    static constexpr double kCoefficientSe[] = {0x1.a87b85c893ab2p-4, 0x1.8e86ec4dccd46p-5, 0x1.30bbb5656543fp-3};
    static constexpr double kZStatistics[] = {0x1.70e700834dff8p+4, 0x1.239e7cea94748p+2, 0x1.42fa10ce1e813p-1};
    static constexpr double kPValues[] = {0x1.99916a50f81fcp-389, 0x1.5cf92b4b679bdp-18, 0x1.0e6b42b577a24p-1};
    static constexpr double kNullDeviance = 0x1.b6d9ef9018d84p+6;
    static constexpr double kResidualDeviance = 0x1.daa2f72eac0bdp-1;
    static constexpr std::size_t kDfNull = 11;
    static constexpr std::size_t kDfResidual = 9;
    static constexpr double kAic = 0x1.caf6828e465acp+5;
    static constexpr double kLogLikelihood = -0x1.9af6828e465acp+4;
    static constexpr double kNullLogLikelihood = -0x1.404ff5746f56ep+6;
    static constexpr double kIncidenceRateRatios[] = {0x1.3f873f2925b2dp+0, 0x1.19314cb098a96p+0};
    static constexpr double kPredictCount = 0x1.b05cf0f8fa9f2p+5;
    static constexpr double kMcfadden = 0x1.5bc66e5bad242p-1;
    static constexpr double kOverdispersion = 0x1.9c6ddc8776b3ep-4;
};

/**
 * @brief R: closed forms, AIC = -2 logLik + 2k, BIC = -2 logLik + k log n, AICc adds 2k(k+1)/(n-k-1)
 */
struct InformationCriteria {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kLogLikelihood = -0x1.559999999999ap+5;
    static constexpr std::size_t kK = 4;
    static constexpr std::size_t kN = 30;
    static constexpr double kAic = 0x1.759999999999ap+6;
    static constexpr double kBic = 0x1.8c04e78bb146dp+6;
    static constexpr double kAicc = 0x1.7cp+6;
};

/**
 * @brief R: closed-form ridge on population-standardised predictors with centred response
 *
 * The coordinate descent stops at the API default tol = 1e-6, so agreement with the closed
 * form is about 7.7e-07 relative. Not compared with MASS::lm.ridge, which scales the penalty
 * differently. The reference reproduces the estimator statcpp defines: population
 * standardisation, centred response, penalty lambda on the standardised scale.
 */
struct RidgeRegression {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-05;
    static constexpr double kXFlat[] = {0x1.0cccccccccccdp+1, 0x1.6p+2, 0x1.b333333333333p+1, 0x1.0666666666666p+2, 0x1.ccccccccccccdp+0, 0x1.b333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.999999999999ap+1, 0x1.2666666666666p+2, 0x1.399999999999ap+2, 0x1.b99999999999ap+2, 0x1.4cccccccccccdp+1, 0x1.a666666666666p+1, 0x1.4666666666666p+2, 0x1.c666666666666p+2, 0x1.199999999999ap+1, 0x1.7333333333333p+2, 0x1.d99999999999ap+1, 0x1.0cccccccccccdp+3, 0x1.e666666666666p+0, 0x1.8cccccccccccdp+2, 0x1.b333333333333p+1, 0x1.2333333333333p+3, 0x1.6666666666666p+0};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kY[] = {0x1.a333333333333p+3, 0x1.c666666666666p+3, 0x1.799999999999ap+3, 0x1.2666666666666p+4, 0x1.2p+4, 0x1.64ccccccccccdp+4, 0x1.dcccccccccccdp+3, 0x1.9666666666666p+4, 0x1.399999999999ap+4, 0x1.c8p+4, 0x1.6333333333333p+4, 0x1.cb33333333333p+4};
    static constexpr double kLambda = 0x1.8p+0;
    static constexpr double kCoefficients[] = {0x1.f12ada12c931dp+3, 0x1.8840adcbb1192p+0, -0x1.0dfca69eca04dp+0};
    static constexpr double kMse = 0x1.7f89cd7379c65p+0;
};

/**
 * @brief R: car::vif, det(cor(X)) and 1 - |det(cor(X))|
 */
struct Multicollinearity {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kXFlat[] = {0x1.0cccccccccccdp+1, 0x1.6p+2, 0x1.b333333333333p+1, 0x1.0666666666666p+2, 0x1.ccccccccccccdp+0, 0x1.b333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.999999999999ap+1, 0x1.2666666666666p+2, 0x1.399999999999ap+2, 0x1.b99999999999ap+2, 0x1.4cccccccccccdp+1, 0x1.a666666666666p+1, 0x1.4666666666666p+2, 0x1.c666666666666p+2, 0x1.199999999999ap+1, 0x1.7333333333333p+2, 0x1.d99999999999ap+1, 0x1.0cccccccccccdp+3, 0x1.e666666666666p+0, 0x1.8cccccccccccdp+2, 0x1.b333333333333p+1, 0x1.2333333333333p+3, 0x1.6666666666666p+0};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 2;
    static constexpr double kVif[] = {0x1.564f51aea2e99p+3, 0x1.564f51aea2e99p+3};
    static constexpr double kDeterminant = 0x1.7ee7917d79655p-4;
    static constexpr double kScore = 0x1.d0230dd050d35p-1;
};

}  // namespace statcpp_test::r_ref
