/**
 * @file r_reference_applied.hpp
 * @brief R reference values for survival, time series, robust, multivariate, categorical and clustering.
 *
 * Generated by generate_r_reference.R against R 4.4.2.
 * Do not edit by hand: re-run the script instead.
 *
 * Values are C++17 hexadecimal floating-point literals and are therefore
 * bit-identical to the values R produced.
 */

#pragma once

#include <cstddef>

#include "r_compare.hpp"

namespace statcpp_test::r_ref {

/**
 * @brief R: survfit(Surv(time, event) ~ 1, conf.type = "plain"), with the origin prepended
 *
 * R's survfit stores std.err on the log scale, so it is multiplied by the survival estimate to
 * obtain the standard error of S(t) that statcpp reports. conf.type = "plain" matches the
 * linear interval statcpp builds.
 */
struct KaplanMeier {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-09;
    static constexpr double kTimes[] = {0x1.8p+2, 0x1.8p+2, 0x1.8p+2, 0x1.cp+2, 0x1.4p+3, 0x1.ap+3, 0x1p+4, 0x1.6p+4, 0x1.7p+4, 0x1.8p+2, 0x1.2p+3, 0x1.4p+3, 0x1.6p+3, 0x1.1p+4, 0x1.3p+4, 0x1.4p+4, 0x1.9p+4, 0x1p+5, 0x1p+5, 0x1.1p+5};
    static constexpr double kEvents[] = {0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0};
    static constexpr double kEventTimes[] = {0x0p+0, 0x1.8p+2, 0x1.cp+2, 0x1.4p+3, 0x1.ap+3, 0x1p+4, 0x1.6p+4, 0x1.7p+4};
    static constexpr double kSurvival[] = {0x1p+0, 0x1.b333333333333p-1, 0x1.98p-1, 0x1.7adb6db6db6dcp-1, 0x1.586a63bd81a99p-1, 0x1.35f959c427e57p-1, 0x1.024fcace213f3p-1, 0x1.9d4c77b03531fp-2};
    static constexpr double kSe[] = {0x0p+0, 0x1.470a146659909p-4, 0x1.74034d9c73c07p-4, 0x1.9c1216798a5dap-4, 0x1.c98bef3fd33e1p-4, 0x1.e7bfb4c73fc55p-4, 0x1.1549adc1f6cabp-3, 0x1.20bde5f5440a6p-3};
    static constexpr double kNAtRisk[] = {0x1.4p+4, 0x1.4p+4, 0x1p+4, 0x1.cp+3, 0x1.6p+3, 0x1.4p+3, 0x1.8p+2, 0x1.4p+2};
    static constexpr double kNEvents[] = {0x0p+0, 0x1.8p+1, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0};
    static constexpr double kMedian = 0x1.7p+4;
};

/**
 * @brief R: cumulative sum of d_i / n_i over the event times, with the origin prepended
 *
 * fh_check records R's Fleming-Harrington cumulative hazard. It differs from statcpp wherever
 * events are tied: at t = 6 with three tied events out of twenty at risk, statcpp gives 3/20 =
 * 0.15 while the tie-corrected form gives 0.15819.
 */
struct NelsonAalen {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-09;
    static constexpr double kTimes[] = {0x1.8p+2, 0x1.8p+2, 0x1.8p+2, 0x1.cp+2, 0x1.4p+3, 0x1.ap+3, 0x1p+4, 0x1.6p+4, 0x1.7p+4, 0x1.8p+2, 0x1.2p+3, 0x1.4p+3, 0x1.6p+3, 0x1.1p+4, 0x1.3p+4, 0x1.4p+4, 0x1.9p+4, 0x1p+5, 0x1p+5, 0x1.1p+5};
    static constexpr double kEvents[] = {0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0};
    static constexpr double kEventTimes[] = {0x0p+0, 0x1.8p+2, 0x1.cp+2, 0x1.4p+3, 0x1.ap+3, 0x1p+4, 0x1.6p+4, 0x1.7p+4};
    static constexpr double kCumulativeHazard[] = {0x0p+0, 0x1.3333333333333p-3, 0x1.b333333333333p-3, 0x1.22be2be2be2bep-2, 0x1.7fd571b43289p-2, 0x1.e63bd81a98ef6p-2, 0x1.48734162a1cdp-1, 0x1.aed9a7c908336p-1};
    static constexpr double kFhCheck[] = {0x0p+0, 0x1.43f79dcab43f9p-3, 0x1.c3f79dcab43f9p-3, 0x1.2b20612e7eb1fp-2, 0x1.8837a6fff30f1p-2, 0x1.ee9e0d6659759p-2, 0x1.4ca45c0882101p-1, 0x1.b30ac26ee8768p-1};
};

/**
 * @brief R: survival::survdiff(Surv(time, event) ~ group)
 */
struct LogrankTest {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-07;
    static constexpr double kTimes1[] = {0x1.8p+2, 0x1.8p+2, 0x1.8p+2, 0x1.cp+2, 0x1.4p+3, 0x1.ap+3, 0x1p+4, 0x1.6p+4, 0x1.7p+4, 0x1.8p+2, 0x1.2p+3, 0x1.4p+3, 0x1.6p+3, 0x1.1p+4, 0x1.3p+4, 0x1.4p+4, 0x1.9p+4, 0x1p+5, 0x1p+5, 0x1.1p+5};
    static constexpr double kEvents1[] = {0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0, 0x0p+0};
    static constexpr double kTimes2[] = {0x1p+0, 0x1p+0, 0x1p+1, 0x1p+1, 0x1.8p+1, 0x1p+2, 0x1p+2, 0x1.4p+2, 0x1.4p+2, 0x1p+3, 0x1p+3, 0x1p+3, 0x1p+3, 0x1.6p+3, 0x1.6p+3, 0x1.8p+3, 0x1.8p+3, 0x1.ep+3, 0x1.1p+4, 0x1.6p+4};
    static constexpr double kEvents2[] = {0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0, 0x1p+0};
    static constexpr double kStatistic = 0x1.15410e812e4f4p+4;
    static constexpr double kPValue = 0x1.07c8abee82d24p-15;
    static constexpr double kObserved1 = 0x1.2p+3;
    static constexpr double kObserved2 = 0x1.4p+4;
    static constexpr double kExpected1 = 0x1.30645f15d47e8p+4;
    static constexpr double kExpected2 = 0x1.3f3741d45703p+3;
};

/**
 * @brief R: acf, pacf, diff, stats::filter for the moving average, and the error closed forms
 *
 * statcpp's acf and pacf both start at lag 0; R's acf does too, while R's pacf starts at lag
 * 1, so a leading 1 is prepended. lag3 is the series shifted by three, which statcpp returns
 * without padding.
 */
struct TimeSeries {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-09;
    static constexpr double kX[] = {0x1.8cccccccccccdp+3, 0x1.a333333333333p+3, 0x1.799999999999ap+3, 0x1.d333333333333p+3, 0x1.e666666666666p+3, 0x1.bcccccccccccdp+3, 0x1.019999999999ap+4, 0x1.14ccccccccccdp+4, 0x1.f99999999999ap+3, 0x1.2333333333333p+4, 0x1.3666666666666p+4, 0x1.1e66666666666p+4, 0x1.419999999999ap+4, 0x1.58p+4, 0x1.3cccccccccccdp+4, 0x1.64ccccccccccdp+4, 0x1.719999999999ap+4, 0x1.599999999999ap+4, 0x1.8p+4, 0x1.9333333333333p+4};
    static constexpr double kY[] = {0x1.8p+3, 0x1.bp+3, 0x1.8666666666666p+3, 0x1.cp+3, 0x1.fp+3, 0x1.c666666666666p+3, 0x1.f99999999999ap+3, 0x1.1p+4, 0x1.0333333333333p+4, 0x1.2p+4, 0x1.3p+4, 0x1.24ccccccccccdp+4, 0x1.3cccccccccccdp+4, 0x1.5p+4, 0x1.4333333333333p+4, 0x1.6p+4, 0x1.78p+4, 0x1.6p+4, 0x1.799999999999ap+4, 0x1.9p+4};
    static constexpr std::size_t kMaxLag = 8;
    static constexpr std::size_t kWindow = 5;
    static constexpr std::size_t kPeriod = 4;
    static constexpr double kAlpha = 0x1.3333333333333p-2;
    static constexpr std::size_t kLagK = 3;
    static constexpr double kAcf[] = {0x1.fffffffffffffp-1, 0x1.8bbb6772763f6p-1, 0x1.456dc8d07769dp-1, 0x1.24fc4b1d85dcap-1, 0x1.83324e5b97318p-2, 0x1.fdb4748f1f336p-3, 0x1.84c60a12ce7a7p-3, 0x1.5f048b0f4a3a2p-7, -0x1.6441b06304a6ap-4};
    static constexpr double kAutocorrelationLag3 = 0x1.24fc4b1d85dcap-1;
    static constexpr double kPacf[] = {0x1p+0, 0x1.8bbb6772763f6p-1, 0x1.84b56c2ba98cap-4, 0x1.166ebcfa7f676p-3, -0x1.3928fa45dc135p-2, -0x1.c63bbb09d001bp-6, 0x1.19819804df0c1p-5, -0x1.f58aecafc66fap-3, -0x1.77228fba99a9dp-8};
    static constexpr double kDiff1[] = {0x1.666666666666p-1, -0x1.4ccccccccccc8p+0, 0x1.6666666666664p+1, 0x1.333333333333p-1, -0x1.4ccccccccccc8p+0, 0x1.199999999999cp+1, 0x1.333333333333p+0, -0x1.8p+0, 0x1.333333333333p+1, 0x1.333333333333p+0, -0x1.8p+0, 0x1.19999999999ap+1, 0x1.666666666666p+0, -0x1.b33333333333p+0, 0x1.4p+1, 0x1.99999999999ap-1, -0x1.8p+0, 0x1.333333333333p+1, 0x1.333333333333p+0};
    static constexpr double kDiff2[] = {-0x1.ffffffffffff8p+0, 0x1.0666666666664p+2, -0x1.1999999999998p+1, -0x1.e66666666666p+0, 0x1.cp+1, -0x1.0000000000008p+0, -0x1.5999999999998p+1, 0x1.f33333333333p+1, -0x1.333333333333p+0, -0x1.5999999999998p+1, 0x1.d9999999999ap+1, -0x1.99999999999cp-1, -0x1.8ccccccccccc8p+1, 0x1.0ccccccccccccp+2, -0x1.b33333333333p+0, -0x1.2666666666668p+1, 0x1.f33333333333p+1, -0x1.333333333333p+0};
    static constexpr double kSeasonalDiff[] = {0x1.6666666666664p+1, 0x1.99999999999ap-1, 0x1.1333333333334p+2, 0x1.599999999999cp+1, 0x1.333333333334p-1, 0x1.1333333333332p+2, 0x1.a66666666666p+1, 0x1.333333333332p-1, 0x1.1333333333334p+2, 0x1.a666666666668p+1, 0x1.99999999999cp-2, 0x1.199999999999cp+2, 0x1.8p+1, 0x1.9999999999ap-4, 0x1.0ccccccccccccp+2, 0x1.733333333333p+1};
    static constexpr double kLag3[] = {0x1.8cccccccccccdp+3, 0x1.a333333333333p+3, 0x1.799999999999ap+3, 0x1.d333333333333p+3, 0x1.e666666666666p+3, 0x1.bcccccccccccdp+3, 0x1.019999999999ap+4, 0x1.14ccccccccccdp+4, 0x1.f99999999999ap+3, 0x1.2333333333333p+4, 0x1.3666666666666p+4, 0x1.1e66666666666p+4, 0x1.419999999999ap+4, 0x1.58p+4, 0x1.3cccccccccccdp+4, 0x1.64ccccccccccdp+4, 0x1.719999999999ap+4};
    static constexpr double kMovingAverage[] = {0x1.ad70a3d70a3d8p+3, 0x1.b70a3d70a3d72p+3, 0x1.ca3d70a3d70a4p+3, 0x1.ed70a3d70a3d7p+3, 0x1.f51eb851eb852p+3, 0x1.0428f5c28f5c3p+4, 0x1.15c28f5c28f5cp+4, 0x1.1b851eb851eb8p+4, 0x1.247ae147ae148p+4, 0x1.36b851eb851ecp+4, 0x1.3bd70a3d70a3ep+4, 0x1.451eb851eb852p+4, 0x1.55c28f5c28f5cp+4, 0x1.5a8f5c28f5c2ap+4, 0x1.628f5c28f5c2ap+4, 0x1.73d70a3d70a3ep+4};
    static constexpr double kEma[] = {0x1.8cccccccccccdp+3, 0x1.93851eb851eb8p+3, 0x1.8bbe76c8b4394p+3, 0x1.a12e48e8a71dcp+3, 0x1.b5f251c193b38p+3, 0x1.b800a9de8b3b1p+3, 0x1.ce8fd3118a6bep+3, 0x1.e9df8ea0c22ccp+3, 0x1.ee975eb836009p+3, 0x1.04778a1ca242cp+4, 0x1.137265cc5d1a4p+4, 0x1.16bb992dc64aap+4, 0x1.2397cc81527bfp+4, 0x1.3350a8c0ecf06p+4, 0x1.362919f7b018ep+4, 0x1.442702d138b54p+4, 0x1.51c9634088f9cp+4, 0x1.5421738e745cep+4, 0x1.614a9db084a76p+4, 0x1.70439757b9048p+4};
    static constexpr double kMse = 0x1.21cac083126ep-3;
    static constexpr double kRmse = 0x1.81315c430e9bap-2;
    static constexpr double kMae = 0x1.75c28f5c28f56p-2;
    static constexpr double kMape = 0x1.110a3d20826ep+1;
};

/**
 * @brief R: mad(constant = 1) and mad(), quantile-based fences, Walsh averages, Tukey biweight
 *
 * mad_r_check confirms that statcpp's mad_scaled equals R's mad(). hl_r_check confirms that
 * hodges_lehmann equals the pseudomedian wilcox.test reports.
 */
struct Robust {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-09;
    static constexpr double kX[] = {0x1.0cccccccccccdp+1, 0x1.b333333333333p+1, 0x1.6666666666666p+1, 0x1.8cccccccccccdp+1, 0x1.7333333333333p+1, 0x1.a666666666666p+1, 0x1.599999999999ap+1, 0x1.8p+1, 0x1.999999999999ap+1, 0x1.4cccccccccccdp+1, 0x1.399999999999ap+3, 0x1.cp+1, 0x1.3333333333333p+1, 0x1.ccccccccccccdp+1, -0x1.0cccccccccccdp+2};
    static constexpr double kK = 0x1.8p+0;
    static constexpr double kZThreshold = 0x1.8p+1;
    static constexpr double kMzThreshold = 0x1.cp+1;
    static constexpr double kLimits = 0x1.999999999999ap-5;
    static constexpr double kC = 0x1.2p+3;
    static constexpr double kMad = 0x1.9999999999998p-2;
    static constexpr double kMadScaled = 0x1.2fa2f05a708ecp-1;
    static constexpr double kMadRCheck = 0x1.2fa2f05a708ecp-1;
    static constexpr double kHodgesLehmann = 0x1.8p+1;
    static constexpr double kHlRCheck = 0x1.8p+1;
    static constexpr double kQ1 = 0x1.5333333333334p+1;
    static constexpr double kQ3 = 0x1.accccccccccccp+1;
    static constexpr double kIqrValue = 0x1.666666666666p-1;
    static constexpr double kLowerFence = 0x1.99999999999ap+0;
    static constexpr double kUpperFence = 0x1.1999999999998p+2;
    static constexpr double kNOutliersIqr = 0x1p+1;
    static constexpr double kNOutliersZ = 0x0p+0;
    static constexpr double kNOutliersMz = 0x1p+1;
    static constexpr double kWinsorized[] = {0x1.0cccccccccccdp+1, 0x1.b333333333333p+1, 0x1.6666666666666p+1, 0x1.8cccccccccccdp+1, 0x1.7333333333333p+1, 0x1.a666666666666p+1, 0x1.599999999999ap+1, 0x1.8p+1, 0x1.999999999999ap+1, 0x1.4cccccccccccdp+1, 0x1.5d70a3d70a3dp+2, 0x1.cp+1, 0x1.3333333333333p+1, 0x1.ccccccccccccdp+1, 0x1.ae147ae147b08p-3};
    static constexpr double kBiweightMidvariance = 0x1.c0bafa5e866f2p-3;
};

/**
 * @brief R: closed forms for Cook's distance and DFFITS
 */
struct Influence {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kResiduals[] = {0x1.3333333333333p+0, -0x1.999999999999ap-1, 0x1p-1, -0x1.8p+0, 0x1.0cccccccccccdp+1, -0x1.3333333333333p-2, 0x1.ccccccccccccdp-1, -0x1.199999999999ap+0};
    static constexpr double kHatValues[] = {0x1.3333333333333p-2, 0x1.3333333333333p-3, 0x1.c28f5c28f5c29p-3, 0x1.70a3d70a3d70ap-3, 0x1.6666666666666p-2, 0x1.eb851eb851eb8p-4, 0x1p-2, 0x1.999999999999ap-3};
    static constexpr double kMse = 0x1.6666666666666p+0;
    static constexpr std::size_t kP = 2;
    static constexpr double kCooks[] = {0x1.426cf7ca432c2p-2, 0x1.84bed45791a75p-5, 0x1.087cd69255741p-5, 0x1.b88dd8f85d1d4p-3, 0x1.4e030792ef565p+0, 0x1.466c33fc5f825p-8, 0x1.0750750750751p-3, 0x1.1492492492493p-3};
    static constexpr double kDffits[] = {0x1.964d81ed6ed71p-1, -0x1.3b774f21b04dep-2, 0x1.04358f710bf31p-2, -0x1.4fd4809a06a68p-1, 0x1.9d89d89d89d8ap+0, -0x1.98d03bcb25508p-4, 0x1.03a1a294f6094p-1, -0x1.0a1644e937a6fp-1};
};

/**
 * @brief R: cov, cor, scale, prcomp and eigen; component signs normalised on both sides
 *
 * statcpp obtains the components by power iteration with deflation rather than a full
 * eigendecomposition, so agreement is about 1.8e-07 relative. PCA eigenvector signs are
 * arbitrary, so each component is normalised to have a positive largest-magnitude loading
 * before comparison. standardize uses the sample standard deviation, matching scale().
 */
struct Multivariate {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-06;
    static constexpr double kXFlat[] = {0x1.0cccccccccccdp+2, 0x1.0cccccccccccdp+1, 0x1.6p+2, 0x1.e666666666666p+1, 0x1.b333333333333p+1, 0x1.0666666666666p+2, 0x1.4666666666666p+2, 0x1.ccccccccccccdp+0, 0x1.8cccccccccccdp+2, 0x1.7333333333333p+1, 0x1.2666666666666p+2, 0x1.a666666666666p+1, 0x1.9333333333333p+2, 0x1.4p+1, 0x1.c666666666666p+2, 0x1.8cccccccccccdp+1, 0x1.f333333333333p+1, 0x1.e666666666666p+1, 0x1.7333333333333p+2, 0x1.199999999999ap+1, 0x1.ap+2, 0x1.2p+2, 0x1.8cccccccccccdp+1, 0x1.4p+2, 0x1.4cccccccccccdp+1, 0x1.399999999999ap+2, 0x1.7333333333333p+1, 0x1.b99999999999ap+2, 0x1.8p+0, 0x1.f333333333333p+2, 0x1.ccccccccccccdp+1, 0x1.0cccccccccccdp+2, 0x1p+2, 0x1.599999999999ap+2, 0x1.6666666666666p+1, 0x1.8p+2};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 3;
    static constexpr std::size_t kNComponents = 2;
    static constexpr double kCovarianceMatrix[] = {0x1.f17e4b17e4b19p+0, -0x1.5c8c41c8c41c9p+0, 0x1.14fbf74fbf75p+1, -0x1.5c8c41c8c41c9p+0, 0x1.4458204582046p+0, -0x1.a49da249da24ap+0, 0x1.14fbf74fbf75p+1, -0x1.a49da249da24ap+0, 0x1.3e1971e1971e1p+1};
    static constexpr double kCorrelationMatrix[] = {0x1p+0, -0x1.bc42285b9c39bp-1, 0x1.f827f1bf52ddep-1, -0x1.bc42285b9c39bp-1, 0x1p+0, -0x1.da15b21aecfe5p-1, 0x1.f827f1bf52ddep-1, -0x1.da15b21aecfe5p-1, 0x1p+0};
    static constexpr double kStandardized[] = {-0x1.d1386549e7234p-3, -0x1.bf49d2c430301p-1, 0x1.9b645ba69fcffp-3, -0x1.07377cad2e90ep-1, 0x1.20158368a9e1fp-2, -0x1.5fd9337031196p-1, 0x1.ac7e0c7339f17p-2, -0x1.23dfe6d276397p+0, 0x1.4a323c16947aap-1, -0x1.28e24e1ca2a95p+0, 0x1.58f1569ba2fdep+0, -0x1.31d665d1c4474p+0, 0x1.477d9824dda84p+0, -0x1.09572eeddfd73p-1, 0x1.374023a82b6f3p+0, -0x1.0427f545f5774p+0, 0x1.737a0e8039603p-1, -0x1.c1488c8371e54p-1, 0x1.d75774185956ap-1, -0x1.91cd29ce9c19dp-1, 0x1.aba19529d5469p-1, -0x1.87c3b39c8cbe3p-7, 0x1.e531b4e62b96p-7, -0x1.dc5941b375aa7p-4, -0x1.5ff9d35ea6743p+0, 0x1.9d2c540c011f7p+0, -0x1.72cb4bde9a249p+0, 0x1.b5aca2a8e53e4p+0, -0x1.681ae442d45adp+0, 0x1.a8ecb63ea1b28p+0, -0x1.50ac2e5a88f4bp-1, 0x1.fbf00960f5a31p-1, -0x1.8053a6769c07ep-1, 0x1.446e10bda48efp-1, -0x1.01c2681a47291p-2, 0x1.093d5609be9d4p-1};
    static constexpr double kMinMaxScaled[] = {0x1.7d05f417d05f3p-2, 0x1.6969696969697p-3, 0x1.0fac687d6343fp-1, 0x1.1dc47711dc475p-2, 0x1.1e1e1e1e1e1e1p-1, 0x1.f58d0fac687d4p-3, 0x1.29aca6b29aca5p-1, 0x1.6969696969697p-4, 0x1.58d0fac687d63p-1, 0x1.1dc47711dc473p-4, 0x1.d2d2d2d2d2d2bp-1, 0x1.4e5e0a72f0538p-4, 0x1.b88ee23b88eep-1, 0x1.2d2d2d2d2d2d2p-2, 0x1.b6db6db6db6dap-1, 0x1.dc47711dc477p-4, 0x1.6969696969696p-1, 0x1.7829cbc14e5ep-3, 0x1.7d05f417d05f2p-1, 0x1.a5a5a5a5a5a5bp-3, 0x1.7829cbc14e5ep-1, 0x1.c47711dc4771p-2, 0x1.e1e1e1e1e1e1ep-2, 0x1.b6db6db6db6dbp-2, 0x0p+0, 0x1p+0, 0x0p+0, 0x1p+0, 0x0p+0, 0x1p+0, 0x1.dc47711dc477p-3, 0x1.9696969696969p-1, 0x1.cbc14e5e0a72fp-3, 0x1.4d653594d6535p-1, 0x1.8787878787877p-2, 0x1.43eb1a1f58d0fp-1};
    static constexpr double kComponents[] = {0x1.2c15e72d2741cp-1, 0x1.0dbd659769936p-1, -0x1.ceea0549df417p-2, 0x1.afae30bed11ccp-1, 0x1.58448b0d17d9ap-1, 0x1.b8d49432c8edbp-4};
    static constexpr double kExplainedVariance[] = {0x1.5e7708fafff3dp+2, 0x1.a6dfae4d63c79p-3};
    static constexpr double kExplainedVarianceRatio[] = {0x1.ec45f2df077e5p-1, 0x1.28fd87495a4dcp-5};
    static constexpr double kPowerIterationValue = 0x1.5e7708fafff41p+2;
};

/**
 * @brief R: centred data projected onto the sign-normalised components
 *
 * Scores inherit the loading error from power iteration with deflation and amplify it:
 * measured agreement is 1.8e-06 relative.
 */
struct PcaTransform {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-05;
    static constexpr double kXFlat[] = {0x1.0cccccccccccdp+2, 0x1.0cccccccccccdp+1, 0x1.6p+2, 0x1.e666666666666p+1, 0x1.b333333333333p+1, 0x1.0666666666666p+2, 0x1.4666666666666p+2, 0x1.ccccccccccccdp+0, 0x1.8cccccccccccdp+2, 0x1.7333333333333p+1, 0x1.2666666666666p+2, 0x1.a666666666666p+1, 0x1.9333333333333p+2, 0x1.4p+1, 0x1.c666666666666p+2, 0x1.8cccccccccccdp+1, 0x1.f333333333333p+1, 0x1.e666666666666p+1, 0x1.7333333333333p+2, 0x1.199999999999ap+1, 0x1.ap+2, 0x1.2p+2, 0x1.8cccccccccccdp+1, 0x1.4p+2, 0x1.4cccccccccccdp+1, 0x1.399999999999ap+2, 0x1.7333333333333p+1, 0x1.b99999999999ap+2, 0x1.8p+0, 0x1.f333333333333p+2, 0x1.ccccccccccccdp+1, 0x1.0cccccccccccdp+2, 0x1p+2, 0x1.599999999999ap+2, 0x1.6666666666666p+1, 0x1.8p+2};
    static constexpr std::size_t kXRows = 12;
    static constexpr std::size_t kXCols = 3;
    static constexpr std::size_t kNComponents = 2;
    static constexpr double kScores[] = {0x1.e32e536344fadp-2, -0x1.ec742e810a4e4p-1, -0x1.4aa8093e2fdc3p+0, -0x1.d13dfa0685d03p-3, 0x1.9b0bc78a759a2p+0, -0x1.549e94ba5ed73p-1, -0x1.73235ba3c09efp+1, 0x1.cb6dad57ffe17p-3, 0x1.4c81018c0ecf3p+1, 0x1.4ed68b2d026eep-1, -0x1.10986b0964f13p+1, -0x1.a746fe6ba9569p-3, 0x1.04b65cca6b7f3p+1, 0x1.2b36c1eecb8a1p-4, -0x1.1fe6314acebeap-3, -0x1.d9d08931850c8p-7, -0x1.bd6e3b14d185cp+1, 0x1.1acba824f6c5cp-2, 0x1.efa0bd37f4c76p+1, 0x1.9e4bf7cf88fe1p-3, -0x1.d6760ec554d44p+0, 0x1.5326a4a36938bp-2, 0x1.31e74e30a7b13p+0, 0x1.41eca0c799d7dp-2};
};

/**
 * @brief R: closed forms for the 2x2 measures, with table() for the contingency counts
 *
 * The interval bounds use the hard-coded z = 1.96 that statcpp applies. z_exact records the
 * exact 0.975 normal quantile, 1.959964; using it would move the bounds by about 1.3e-05
 * relative.
 */
struct Categorical {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-09;
    static constexpr std::size_t kA = 45;
    static constexpr std::size_t kB = 25;
    static constexpr std::size_t kC = 20;
    static constexpr std::size_t kD = 60;
    static constexpr std::size_t kRows[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
    static constexpr std::size_t kCols[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
    static constexpr double kOddsRatio = 0x1.599999999999ap+2;
    static constexpr double kLogOddsRatio = 0x1.afb7d78197bedp+0;
    static constexpr double kSeLogOddsRatio = 0x1.6fa09382b9326p-2;
    static constexpr double kOrCiLower = 0x1.55fc3b079af31p+1;
    static constexpr double kOrCiUpper = 0x1.5d40c01ab1f51p+3;
    static constexpr double kRelativeRisk = 0x1.4924924924925p+1;
    static constexpr double kLogRelativeRisk = 0x1.e39078d49916cp-1;
    static constexpr double kSeLogRelativeRisk = 0x1.b48c658d45347p-3;
    static constexpr double kRrCiLower = 0x1.b17b33f1ab88bp+0;
    static constexpr double kRrCiUpper = 0x1.f3d64fd9951c2p+1;
    static constexpr double kRiskDifference = 0x1.924924924924ap-2;
    static constexpr double kSeRiskDifference = 0x1.3329a564a3fa4p-4;
    static constexpr double kRdCiLower = 0x1.f78d500480f2cp-3;
    static constexpr double kRdCiUpper = 0x1.1465d09128e7fp-1;
    static constexpr double kNumberNeededToTreat = 0x1.45d1745d1745cp+1;
    static constexpr double kTableCounts[] = {0x1.68p+5, 0x1.9p+4, 0x1.4p+4, 0x1.ep+5};
    static constexpr double kRowTotals[] = {0x1.18p+6, 0x1.4p+6};
    static constexpr double kColTotals[] = {0x1.04p+6, 0x1.54p+6};
    static constexpr double kTotal = 0x1.2cp+7;
    static constexpr double kZExact = 0x1.f5c0331eeff82p+0;
};

/**
 * @brief R: dist, hclust(method = "single"), cutree and cluster::silhouette
 *
 * Merge heights are compared as a sorted vector and cluster sizes as sorted counts: statcpp
 * numbers its dendrogram nodes and clusters differently from hclust, but a correct
 * single-linkage tree has the same merge distances and the same partition.
 */
struct Clustering {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-09;
    static constexpr double kXFlat[] = {0x1p+0, 0x1.3333333333333p+0, 0x1.4cccccccccccdp+0, 0x1.ccccccccccccdp-1, 0x1.999999999999ap-1, 0x1.6666666666666p+0, 0x1.4cccccccccccdp+2, 0x1.6p+2, 0x1.6666666666666p+2, 0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.599999999999ap+2, 0x1.2333333333333p+3, 0x1.299999999999ap+3, 0x1.2cccccccccccdp+3, 0x1.199999999999ap+3, 0x1.1cccccccccccdp+3, 0x1.3p+3, 0x1.2666666666666p+3, 0x1.2p+3};
    static constexpr std::size_t kXRows = 10;
    static constexpr std::size_t kXCols = 2;
    static constexpr std::size_t kK = 3;
    static constexpr double kA[] = {0x1p+0, 0x1.3333333333333p+0};
    static constexpr double kB[] = {0x1.2333333333333p+3, 0x1.299999999999ap+3};
    static constexpr double kEuclideanDistance = 0x1.6e906c7c73959p+3;
    static constexpr double kManhattanDistance = 0x1.0333333333334p+4;
    static constexpr double kMergeHeights[] = {0x1.21a1851ff62f8p-2, 0x1.21a1851ff6309p-2, 0x1.21a1851ff630fp-2, 0x1.43d136248490ap-2, 0x1.43d1362484919p-2, 0x1.b27247aff148fp-2, 0x1.21a1851ff6309p-1, 0x1.53710121b5f65p+2, 0x1.6e97932b82e06p+2};
    static constexpr double kClusterSizes[] = {0x1.8p+1, 0x1.8p+1, 0x1p+2};
    static constexpr double kSilhouetteScore = 0x1.d25a18ac29d0cp-1;
};

}  // namespace statcpp_test::r_ref
