/**
 * @file r_reference_inference.hpp
 * @brief R reference values for effect sizes, interval estimation and power analysis.
 *
 * Generated by generate_r_reference.R against R 4.4.2.
 * Do not edit by hand: re-run the script instead.
 *
 * Values are C++17 hexadecimal floating-point literals and are therefore
 * bit-identical to the values R produced.
 */

#pragma once

#include <cstddef>

#include "r_compare.hpp"

namespace statcpp_test::r_ref {

/**
 * @brief R: closed forms cross-checked against effectsize::cohens_d and effectsize::hedges_g
 *
 * effectsize_g_check is NOT expected to match: the effectsize package uses the exact
 * gamma-based correction factor, while statcpp uses the standard 1 - 3/(4 df - 1)
 * approximation. The two differ by about 1e-04 here. glass_delta divides by the standard
 * deviation of the first (control) sample and reports mean(treatment) - mean(control).
 */
struct EffectSizeSamples {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2, 0x1.599999999999ap+2, 0x1.4cccccccccccdp+2};
    static constexpr double kY[] = {0x1.2p+2, 0x1.2cccccccccccdp+2, 0x1.1333333333333p+2, 0x1.2666666666666p+2, 0x1.199999999999ap+2, 0x1.3333333333333p+2, 0x1.0cccccccccccdp+2, 0x1.2666666666666p+2, 0x1.199999999999ap+2, 0x1.2p+2};
    static constexpr double kMu0 = 0x1.4p+2;
    static constexpr double kCohensDOneSample = 0x1.e205529d3de6fp-2;
    static constexpr double kHedgesGOneSample = 0x1.b8b468ca47398p-2;
    static constexpr double kCohensDTwoSample = 0x1.93fdfc9c976p+1;
    static constexpr double kHedgesGTwoSample = 0x1.82ec0b2d69512p+1;
    static constexpr double kGlassDelta = -0x1.8afd4024680fap+1;
    static constexpr double kHedgesCorrectionFactor = 0x1.ea5dbf193d4bcp-1;
    static constexpr double kEffectsizeDCheck = 0x1.93fdfc9c97601p+1;
    static constexpr double kEffectsizeGCheck = 0x1.82e1b233a6652p+1;
};

/**
 * @brief R: closed forms for the effect-size conversions and 2x2 measures
 */
struct EffectSizeConversions {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kD = 0x1.999999999999ap-1;
    static constexpr double kR = 0x1p-1;
    static constexpr double kT = 0x1.4cccccccccccdp+1;
    static constexpr double kDf = 0x1.2p+4;
    static constexpr double kF = 0x1.0cccccccccccdp+2;
    static constexpr double kDf1 = 0x1p+1;
    static constexpr double kDf2 = 0x1.bp+4;
    static constexpr double kP1 = 0x1.4cccccccccccdp-1;
    static constexpr double kP2 = 0x1.999999999999ap-2;
    static constexpr double kSsEffect = 0x1.e2p+6;
    static constexpr double kSsTotal = 0x1.ep+8;
    static constexpr double kMsError = 0x1.3p+3;
    static constexpr double kDfEffect = 0x1.8p+1;
    static constexpr double kA = 0x1.ep+4;
    static constexpr double kB = 0x1.4p+4;
    static constexpr double kC = 0x1.ep+3;
    static constexpr double kDCell = 0x1.18p+5;
    static constexpr double kDToR = 0x1.7c4dd663ebb87p-2;
    static constexpr double kRToD = 0x1.279a74590331dp+0;
    static constexpr double kTToR = 0x1.0b86f86173274p-1;
    static constexpr double kPartialEtaSquared = 0x1.e5f75270d0457p-3;
    static constexpr double kCohensH = 0x1.03190f99d341p-1;
    static constexpr double kEtaSquared = 0x1.0111111111111p-2;
    static constexpr double kOmegaSquared = 0x1.80ea4bd51d8c7p-3;
    static constexpr double kOddsRatio = 0x1.cp+1;
    static constexpr double kRiskRatio = 0x1p+1;
    static constexpr double kEffectsizeDToRCheck = 0x1.7c4dd663ebb87p-2;
};

/**
 * @brief R: t.test(...)$conf.int, plus the z-interval and variance interval closed forms
 *
 * ci_mean_diff delegates to the pooled, equal-variance interval; ci_mean_diff_welch is the
 * separate-variance form. Interval bounds and margins pass through statcpp's own t and normal
 * quantile functions, which agree with R to about 1e-10, so they use the looser tier.
 */
struct EstimationMeans {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-09;
    static constexpr double kX[] = {0x1.4666666666666p+2, 0x1.399999999999ap+2, 0x1.5333333333333p+2, 0x1.4666666666666p+2, 0x1.3333333333333p+2, 0x1.4cccccccccccdp+2, 0x1.4p+2, 0x1.399999999999ap+2, 0x1.599999999999ap+2, 0x1.4cccccccccccdp+2};
    static constexpr double kY[] = {0x1.2p+2, 0x1.2cccccccccccdp+2, 0x1.1333333333333p+2, 0x1.2666666666666p+2, 0x1.199999999999ap+2, 0x1.3333333333333p+2, 0x1.0cccccccccccdp+2, 0x1.2666666666666p+2, 0x1.199999999999ap+2, 0x1.2p+2};
    static constexpr double kSigma = 0x1.999999999999ap-3;
    static constexpr double kConfidence = 0x1.e666666666666p-1;
    static constexpr double kCiMeanLower = 0x1.3d01ad038841dp+2;
    static constexpr double kCiMeanUpper = 0x1.4e8371b4c9a9ap+2;
    static constexpr double kCiMeanEstimate = 0x1.45c28f5c28f5cp+2;
    static constexpr double kCiMeanZLower = 0x1.3dd39d9a76207p+2;
    static constexpr double kCiMeanZUpper = 0x1.4db1811ddbcb1p+2;
    static constexpr double kCiDiffWelchLower = 0x1.a847f879872e3p-2;
    static constexpr double kCiDiffWelchUpper = 0x1.8804f985cbc4fp-1;
    static constexpr double kCiDiffPooledLower = 0x1.a84efca3161d8p-2;
    static constexpr double kCiDiffPooledUpper = 0x1.88017771044d4p-1;
    static constexpr double kCiVarianceLower = 0x1.1b5cc2535b2a8p-6;
    static constexpr double kCiVarianceUpper = 0x1.f3087f782f2fdp-4;
    static constexpr double kStandardError = 0x1.ef4c4e7ab75ep-5;
    static constexpr double kMarginOfErrorMean = 0x1.181c4b14167d6p-3;
};

/**
 * @brief R: prop.test(correct = FALSE)$conf.int for Wilson, plus the Wald closed forms
 *
 * ci_proportion is the Wald interval; ci_proportion_wilson is the score interval and matches
 * prop.test(correct = FALSE). Bounds pass through statcpp's own normal quantile, which agrees
 * with R to about 2e-10.
 */
struct EstimationProportions {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr std::size_t kSuccesses = 45;
    static constexpr std::size_t kTrials = 100;
    static constexpr std::size_t kSuccesses2 = 30;
    static constexpr std::size_t kTrials2 = 90;
    static constexpr double kConfidence = 0x1.e666666666666p-1;
    static constexpr double kWaldLower = 0x1.68f3ee55de184p-2;
    static constexpr double kWaldUpper = 0x1.1852d5a1ddc0bp-1;
    static constexpr double kWilsonLower = 0x1.6cb15fdb5dbc5p-2;
    static constexpr double kWilsonUpper = 0x1.1858fe741c11fp-1;
    static constexpr double kDiffLower = -0x1.5a7a46b57bb38p-6;
    static constexpr double kDiffUpper = 0x1.0496935a46aa4p-2;
    static constexpr double kMarginOfError = 0x1.8f6379dbbad25p-4;
    static constexpr double kMarginOfErrorWorstCase = 0x1.91668f4bf32cep-4;
    static constexpr double kSampleSizeMean = 0x1.fp+5;
    static constexpr double kSampleSizeProportion = 0x1.0bp+10;
    static constexpr double kMoeTarget = 0x1.999999999999ap-5;
    static constexpr double kMoeSigma = 0x1.999999999999ap-3;
    static constexpr double kMoePTarget = 0x1.eb851eb851eb8p-6;
};

/**
 * @brief R: statcpp's documented normal approximation; power.t.test recorded for comparison
 *
 * power_one_sample is NOT expected to equal r_power_t_test: statcpp uses a normal
 * approximation, R uses the noncentral t distribution. Both are recorded so the size of the
 * gap is visible.
 */
struct PowerTTest {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kEffectSize = 0x1p-1;
    static constexpr std::size_t kN = 30;
    static constexpr double kAlpha = 0x1.999999999999ap-5;
    static constexpr std::size_t kN1 = 25;
    static constexpr std::size_t kN2 = 35;
    static constexpr double kTargetPower = 0x1.999999999999ap-1;
    static constexpr double kRatio = 0x1p+0;
    static constexpr double kPowerOneSample = 0x1.90563ec611bf7p-1;
    static constexpr double kPowerTwoSample = 0x1.eb693d5c73d6p-2;
    static constexpr double kSampleSizeOne = 0x1p+5;
    static constexpr double kSampleSizeTwo = 0x1.f8p+5;
    static constexpr double kRPowerTTest = 0x1.820766fc83ba9p-1;
    static constexpr double kRSampleSize = 0x1.1p+5;
};

/**
 * @brief R: power.prop.test(n, p1, p2); statcpp implements the same closed form
 */
struct PowerPropTest {
    static constexpr double kRtol = 1e-12;
    static constexpr double kAtol = 0.0;
    static constexpr double kPRtol = 1e-08;
    static constexpr double kP1 = 0x1.4cccccccccccdp-1;
    static constexpr double kP2 = 0x1.ccccccccccccdp-2;
    static constexpr std::size_t kN = 100;
    static constexpr double kAlpha = 0x1.999999999999ap-5;
    static constexpr double kTargetPower = 0x1.999999999999ap-1;
    static constexpr double kPower = 0x1.a1e95b72e9e2ap-1;
    static constexpr double kSampleSize = 0x1.8p+6;
};

}  // namespace statcpp_test::r_ref
