/**
 * @file test_vs_r_distributions.cpp
 * @brief Compare statcpp distribution and special functions against R 4.4.2.
 *
 * Covers continuous_distributions.hpp, discrete_distributions.hpp and
 * special_functions.hpp. Every function is swept over a grid rather than checked
 * at a single point, so that the interior and the tails are both exercised.
 *
 * Reference values and grids both come from r_reference_distributions.hpp, which
 * is generated by generate_r_reference.R. R is not needed to build or run this
 * test.
 */

#include <cstddef>
#include <iterator>
#include <vector>

#include <gtest/gtest.h>

#include "statcpp/continuous_distributions.hpp"
#include "statcpp/discrete_distributions.hpp"
#include "statcpp/special_functions.hpp"

#include "r_compare.hpp"
#include "r_reference_distributions.hpp"

namespace {

namespace ref = statcpp_test::r_ref;

/**
 * @brief Evaluate `expr` at every point of the case's grid and compare with R.
 *
 * `RTOL_MACRO` selects the tolerance tier: EXPECT_R_RANGE for plain arithmetic,
 * EXPECT_R_PVALUE_RANGE for anything routed through statcpp's own incomplete
 * beta or incomplete gamma functions.
 */
#define R_SWEEP_TEST(Suite, CaseName, Grid, RangeMacro, expr)         \
    TEST(Suite, CaseName) {                                           \
        using Case = ref::CaseName;                                   \
        std::vector<double> actual;                                   \
        actual.reserve(std::size(Case::Grid));                        \
        for (const auto v : Case::Grid) actual.push_back(expr);       \
        RangeMacro(actual, Case, kY);                                 \
    }

// ============================================================================
// continuous_distributions.hpp
// ============================================================================

R_SWEEP_TEST(RContinuousDistributions, NormalPdf, kX, EXPECT_R_RANGE,
             statcpp::normal_pdf(v, Case::kMu, Case::kSigma))
R_SWEEP_TEST(RContinuousDistributions, NormalCdf, kX, EXPECT_R_PVALUE_RANGE,
             statcpp::normal_cdf(v, Case::kMu, Case::kSigma))
R_SWEEP_TEST(RContinuousDistributions, NormalQuantile, kP, EXPECT_R_PVALUE_RANGE,
             statcpp::normal_quantile(v, Case::kMu, Case::kSigma))

R_SWEEP_TEST(RContinuousDistributions, TPdf, kX, EXPECT_R_RANGE, statcpp::t_pdf(v, Case::kDf))
R_SWEEP_TEST(RContinuousDistributions, TCdf, kX, EXPECT_R_PVALUE_RANGE,
             statcpp::t_cdf(v, Case::kDf))
R_SWEEP_TEST(RContinuousDistributions, TQuantile, kP, EXPECT_R_PVALUE_RANGE,
             statcpp::t_quantile(v, Case::kDf))

R_SWEEP_TEST(RContinuousDistributions, ChisqPdf, kX, EXPECT_R_RANGE,
             statcpp::chisq_pdf(v, Case::kDf))
R_SWEEP_TEST(RContinuousDistributions, ChisqCdf, kX, EXPECT_R_PVALUE_RANGE,
             statcpp::chisq_cdf(v, Case::kDf))
R_SWEEP_TEST(RContinuousDistributions, ChisqQuantile, kP, EXPECT_R_PVALUE_RANGE,
             statcpp::chisq_quantile(v, Case::kDf))

R_SWEEP_TEST(RContinuousDistributions, FPdf, kX, EXPECT_R_RANGE,
             statcpp::f_pdf(v, Case::kDf1, Case::kDf2))
R_SWEEP_TEST(RContinuousDistributions, FCdf, kX, EXPECT_R_PVALUE_RANGE,
             statcpp::f_cdf(v, Case::kDf1, Case::kDf2))
R_SWEEP_TEST(RContinuousDistributions, FQuantile, kP, EXPECT_R_PVALUE_RANGE,
             statcpp::f_quantile(v, Case::kDf1, Case::kDf2))

R_SWEEP_TEST(RContinuousDistributions, GammaPdf, kX, EXPECT_R_RANGE,
             statcpp::gamma_pdf(v, Case::kShape, Case::kRate))
R_SWEEP_TEST(RContinuousDistributions, GammaCdf, kX, EXPECT_R_PVALUE_RANGE,
             statcpp::gamma_cdf(v, Case::kShape, Case::kRate))
R_SWEEP_TEST(RContinuousDistributions, GammaQuantile, kP, EXPECT_R_PVALUE_RANGE,
             statcpp::gamma_quantile(v, Case::kShape, Case::kRate))

R_SWEEP_TEST(RContinuousDistributions, BetaPdf, kX, EXPECT_R_RANGE,
             statcpp::beta_pdf(v, Case::kAlpha, Case::kBetaParam))
R_SWEEP_TEST(RContinuousDistributions, BetaCdf, kX, EXPECT_R_PVALUE_RANGE,
             statcpp::beta_cdf(v, Case::kAlpha, Case::kBetaParam))
R_SWEEP_TEST(RContinuousDistributions, BetaQuantile, kP, EXPECT_R_PVALUE_RANGE,
             statcpp::beta_quantile(v, Case::kAlpha, Case::kBetaParam))

R_SWEEP_TEST(RContinuousDistributions, ExponentialPdf, kX, EXPECT_R_RANGE,
             statcpp::exponential_pdf(v, Case::kLambda))
R_SWEEP_TEST(RContinuousDistributions, ExponentialCdf, kX, EXPECT_R_RANGE,
             statcpp::exponential_cdf(v, Case::kLambda))
R_SWEEP_TEST(RContinuousDistributions, ExponentialQuantile, kP, EXPECT_R_RANGE,
             statcpp::exponential_quantile(v, Case::kLambda))

R_SWEEP_TEST(RContinuousDistributions, UniformPdf, kX, EXPECT_R_RANGE,
             statcpp::uniform_pdf(v, Case::kA, Case::kB))
R_SWEEP_TEST(RContinuousDistributions, UniformCdf, kX, EXPECT_R_RANGE,
             statcpp::uniform_cdf(v, Case::kA, Case::kB))
R_SWEEP_TEST(RContinuousDistributions, UniformQuantile, kP, EXPECT_R_RANGE,
             statcpp::uniform_quantile(v, Case::kA, Case::kB))

R_SWEEP_TEST(RContinuousDistributions, LognormalPdf, kX, EXPECT_R_RANGE,
             statcpp::lognormal_pdf(v, Case::kMu, Case::kSigma))
R_SWEEP_TEST(RContinuousDistributions, LognormalCdf, kX, EXPECT_R_PVALUE_RANGE,
             statcpp::lognormal_cdf(v, Case::kMu, Case::kSigma))
R_SWEEP_TEST(RContinuousDistributions, LognormalQuantile, kP, EXPECT_R_PVALUE_RANGE,
             statcpp::lognormal_quantile(v, Case::kMu, Case::kSigma))

R_SWEEP_TEST(RContinuousDistributions, WeibullPdf, kX, EXPECT_R_RANGE,
             statcpp::weibull_pdf(v, Case::kShape, Case::kScale))
R_SWEEP_TEST(RContinuousDistributions, WeibullCdf, kX, EXPECT_R_RANGE,
             statcpp::weibull_cdf(v, Case::kShape, Case::kScale))
R_SWEEP_TEST(RContinuousDistributions, WeibullQuantile, kP, EXPECT_R_RANGE,
             statcpp::weibull_quantile(v, Case::kShape, Case::kScale))

R_SWEEP_TEST(RContinuousDistributions, StudentizedRangeCdf, kQ, EXPECT_R_PVALUE_RANGE,
             statcpp::studentized_range_cdf(v, Case::kK, Case::kDf))
R_SWEEP_TEST(RContinuousDistributions, StudentizedRangeQuantile, kP, EXPECT_R_PVALUE_RANGE,
             statcpp::studentized_range_quantile(v, Case::kK, Case::kDf))

// ============================================================================
// discrete_distributions.hpp
// ============================================================================

R_SWEEP_TEST(RDiscreteDistributions, BinomialPmf, kK, EXPECT_R_RANGE,
             statcpp::binomial_pmf(v, Case::kN, Case::kP))
R_SWEEP_TEST(RDiscreteDistributions, BinomialCdf, kK, EXPECT_R_RANGE,
             statcpp::binomial_cdf(v, Case::kN, Case::kP))
R_SWEEP_TEST(RDiscreteDistributions, BinomialQuantile, kProb, EXPECT_R_RANGE,
             static_cast<double>(statcpp::binomial_quantile(v, Case::kN, Case::kP)))

R_SWEEP_TEST(RDiscreteDistributions, PoissonPmf, kK, EXPECT_R_RANGE,
             statcpp::poisson_pmf(v, Case::kLambda))
R_SWEEP_TEST(RDiscreteDistributions, PoissonCdf, kK, EXPECT_R_RANGE,
             statcpp::poisson_cdf(v, Case::kLambda))
R_SWEEP_TEST(RDiscreteDistributions, PoissonQuantile, kP, EXPECT_R_RANGE,
             static_cast<double>(statcpp::poisson_quantile(v, Case::kLambda)))

R_SWEEP_TEST(RDiscreteDistributions, GeometricPmf, kK, EXPECT_R_RANGE,
             statcpp::geometric_pmf(v, Case::kP))
R_SWEEP_TEST(RDiscreteDistributions, GeometricCdf, kK, EXPECT_R_RANGE,
             statcpp::geometric_cdf(v, Case::kP))
R_SWEEP_TEST(RDiscreteDistributions, GeometricQuantile, kProb, EXPECT_R_RANGE,
             static_cast<double>(statcpp::geometric_quantile(v, Case::kP)))

R_SWEEP_TEST(RDiscreteDistributions, HypergeomPmf, kK, EXPECT_R_RANGE,
             statcpp::hypergeom_pmf(v, Case::kCapN, Case::kCapK, Case::kN))
R_SWEEP_TEST(RDiscreteDistributions, HypergeomCdf, kK, EXPECT_R_RANGE,
             statcpp::hypergeom_cdf(v, Case::kCapN, Case::kCapK, Case::kN))
R_SWEEP_TEST(RDiscreteDistributions, HypergeomQuantile, kP, EXPECT_R_RANGE,
             static_cast<double>(statcpp::hypergeom_quantile(v, Case::kCapN, Case::kCapK, Case::kN)))

R_SWEEP_TEST(RDiscreteDistributions, NbinomPmf, kK, EXPECT_R_RANGE,
             statcpp::nbinom_pmf(v, Case::kR, Case::kP))
R_SWEEP_TEST(RDiscreteDistributions, NbinomCdf, kK, EXPECT_R_RANGE,
             statcpp::nbinom_cdf(v, Case::kR, Case::kP))
R_SWEEP_TEST(RDiscreteDistributions, NbinomQuantile, kProb, EXPECT_R_RANGE,
             static_cast<double>(statcpp::nbinom_quantile(v, Case::kR, Case::kP)))

R_SWEEP_TEST(RDiscreteDistributions, BernoulliPmf, kK, EXPECT_R_RANGE,
             statcpp::bernoulli_pmf(v, Case::kP))
R_SWEEP_TEST(RDiscreteDistributions, BernoulliCdf, kK, EXPECT_R_RANGE,
             statcpp::bernoulli_cdf(v, Case::kP))
R_SWEEP_TEST(RDiscreteDistributions, BernoulliQuantile, kProb, EXPECT_R_RANGE,
             static_cast<double>(statcpp::bernoulli_quantile(v, Case::kP)))

R_SWEEP_TEST(RDiscreteDistributions, DiscreteUniformPmf, kK, EXPECT_R_RANGE,
             statcpp::discrete_uniform_pmf(static_cast<std::int64_t>(v),
                                            static_cast<std::int64_t>(Case::kA),
                                            static_cast<std::int64_t>(Case::kB)))
R_SWEEP_TEST(RDiscreteDistributions, DiscreteUniformCdf, kK, EXPECT_R_RANGE,
             statcpp::discrete_uniform_cdf(static_cast<std::int64_t>(v),
                                            static_cast<std::int64_t>(Case::kA),
                                            static_cast<std::int64_t>(Case::kB)))
R_SWEEP_TEST(RDiscreteDistributions, DiscreteUniformQuantile, kP, EXPECT_R_RANGE,
             static_cast<double>(statcpp::discrete_uniform_quantile(
                 v, static_cast<std::int64_t>(Case::kA), static_cast<std::int64_t>(Case::kB))))

/// @brief Binomial coefficient against choose(n, k).
TEST(RDiscreteDistributions, BinomialCoef) {
    using Case = ref::BinomialCoef;
    std::vector<double> actual;
    for (std::size_t i = 0; i < std::size(Case::kN); ++i) {
        actual.push_back(statcpp::binomial_coef(Case::kN[i], Case::kK[i]));
    }
    EXPECT_R_RANGE(actual, Case, kY);
}

/// @brief Log binomial coefficient against lchoose(n, k).
TEST(RDiscreteDistributions, LogBinomialCoef) {
    using Case = ref::LogBinomialCoef;
    std::vector<double> actual;
    for (std::size_t i = 0; i < std::size(Case::kN); ++i) {
        actual.push_back(statcpp::log_binomial_coef(Case::kN[i], Case::kK[i]));
    }
    EXPECT_R_RANGE(actual, Case, kY);
}

R_SWEEP_TEST(RDiscreteDistributions, LogFactorial, kN, EXPECT_R_RANGE,
             statcpp::log_factorial(v))

// ============================================================================
// special_functions.hpp
// ============================================================================

R_SWEEP_TEST(RSpecialFunctions, Erf, kX, EXPECT_R_PVALUE_RANGE, statcpp::erf(v))
R_SWEEP_TEST(RSpecialFunctions, Erfc, kX, EXPECT_R_PVALUE_RANGE, statcpp::erfc(v))
R_SWEEP_TEST(RSpecialFunctions, Lgamma, kX, EXPECT_R_RANGE, statcpp::lgamma(v))
R_SWEEP_TEST(RSpecialFunctions, Tgamma, kX, EXPECT_R_RANGE, statcpp::tgamma(v))
R_SWEEP_TEST(RSpecialFunctions, NormCdf, kX, EXPECT_R_PVALUE_RANGE, statcpp::norm_cdf(v))
R_SWEEP_TEST(RSpecialFunctions, NormQuantile, kP, EXPECT_R_PVALUE_RANGE, statcpp::norm_quantile(v))
R_SWEEP_TEST(RSpecialFunctions, NormSf, kX, EXPECT_R_PVALUE_RANGE, statcpp::norm_sf(v))

/// @brief Beta function against beta(a, b).
TEST(RSpecialFunctions, BetaFunction) {
    using Case = ref::BetaFunction;
    std::vector<double> actual;
    for (std::size_t i = 0; i < std::size(Case::kA); ++i) {
        actual.push_back(statcpp::beta(Case::kA[i], Case::kB[i]));
    }
    EXPECT_R_RANGE(actual, Case, kY);
}

/// @brief Log beta function against lbeta(a, b).
TEST(RSpecialFunctions, Lbeta) {
    using Case = ref::Lbeta;
    std::vector<double> actual;
    for (std::size_t i = 0; i < std::size(Case::kA); ++i) {
        actual.push_back(statcpp::lbeta(Case::kA[i], Case::kB[i]));
    }
    EXPECT_R_RANGE(actual, Case, kY);
}

R_SWEEP_TEST(RSpecialFunctions, Betainc, kX, EXPECT_R_PVALUE_RANGE,
             statcpp::betainc(Case::kA, Case::kB, v))
R_SWEEP_TEST(RSpecialFunctions, Betaincinv, kP, EXPECT_R_PVALUE_RANGE,
             statcpp::betaincinv(Case::kA, Case::kB, v))
R_SWEEP_TEST(RSpecialFunctions, GammaincLower, kX, EXPECT_R_PVALUE_RANGE,
             statcpp::gammainc_lower(Case::kA, v))
R_SWEEP_TEST(RSpecialFunctions, GammaincUpper, kX, EXPECT_R_PVALUE_RANGE,
             statcpp::gammainc_upper(Case::kA, v))
R_SWEEP_TEST(RSpecialFunctions, GammaincLowerInv, kP, EXPECT_R_PVALUE_RANGE,
             statcpp::gammainc_lower_inv(Case::kA, v))

}  // namespace
