/**
 * @file test_vs_r_conditional.cpp
 * @brief Compare statcpp functions whose R counterparts need extra packages.
 *
 * These four functions were previously classified as conditionally verifiable
 * because their references require glmnet, mice or naniar. Reference values come
 * from r_reference_conditional.hpp, generated by generate_r_reference.R.
 */

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <functional>
#include <iterator>
#include <vector>

#include <gtest/gtest.h>

#include "statcpp/missing_data.hpp"
#include "statcpp/model_selection.hpp"

#include "r_compare.hpp"
#include "r_reference_conditional.hpp"
#include "r_reference_crossval.hpp"

namespace {

namespace ref = statcpp_test::r_ref;
using statcpp_test::MakeMatrix;

/// @brief Copy a reference array into the vector type the statcpp API expects.
template <std::size_t N>
std::vector<double> AsVector(const double (&values)[N])
{
    return std::vector<double>(values, values + N);
}

/// @brief Lasso regression against glmnet with the penalty mapped as s = lambda / n.
TEST(RConditional, LassoRegression) {
    using Case = ref::LassoRegression;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::lasso_regression(X, y, Case::kLambda);
    ASSERT_TRUE(m.converged);
    EXPECT_R_PVALUE_RANGE(m.coefficients, Case, kCoefficients);
    EXPECT_R_PVALUE(m.mse, Case, kMse);
}

/// @brief Elastic net against an independent solution of statcpp's own objective.
///
/// Unlike the lasso, this does not coincide with glmnet under the same penalty
/// mapping; the reference records glmnet's answer for contrast rather than as an
/// expectation.
TEST(RConditional, ElasticNetRegression) {
    using Case = ref::ElasticNetRegression;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::elastic_net_regression(X, y, Case::kLambda, Case::kAlpha);
    ASSERT_TRUE(m.converged);
    EXPECT_R_PVALUE_RANGE(m.coefficients, Case, kCoefficients);
    EXPECT_R_PVALUE(m.mse, Case, kMse);
    // The gap against glmnet is real; assert only that it is the documented one.
    EXPECT_GT(std::abs(m.coefficients[0] - Case::kGlmnetContrast[0]), 1e-3);
}

/// @brief Missing-data pattern summary, cross-checked against mice::md.pattern.
TEST(RConditional, AnalyzeMissingPatterns) {
    using Case = ref::MissingPatterns;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto info = statcpp::analyze_missing_patterns(X);
    EXPECT_R_RANGE(info.missing_rates, Case, kMissingRates);
    EXPECT_R_FIELD(info.overall_missing_rate, Case, kOverallMissingRate);
    EXPECT_R_FIELD(static_cast<double>(info.n_complete_cases), Case, kNCompleteCases);
    EXPECT_R_FIELD(static_cast<double>(info.n_patterns), Case, kNPatterns);
    EXPECT_R_FIELD(static_cast<double>(info.n_patterns), Case, kMiceNPatterns);
    // Patterns are enumerated in a different order on each side.
    std::vector<double> counts;
    for (const auto c : info.pattern_counts) counts.push_back(static_cast<double>(c));
    std::sort(counts.begin(), counts.end(), std::greater<double>());
    EXPECT_R_RANGE(counts, Case, kPatternCounts);
}

/// @brief statcpp's MCAR heuristic against a reproduction of the same procedure.
///
/// This is not Little's MCAR test; naniar::mcar_test is recorded for contrast.
TEST(RConditional, TestMcarSimple) {
    using Case = ref::McarSimple;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto r = statcpp::test_mcar_simple(X);
    EXPECT_R_FIELD(r.chi_square, Case, kChiSquare);
    EXPECT_R_FIELD(static_cast<double>(r.df), Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Cross-validation over deterministic folds.
///
/// The shuffle argument added for this purpose makes create_cv_folds split the
/// data into contiguous blocks, so the whole procedure becomes reproducible. The
/// default still shuffles with the global random engine.
TEST(RConditional, CrossValidateLinear) {
    using Case = ref::CrossValidateLinear;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto r = statcpp::cross_validate_linear(X, y, Case::kK, false);
    EXPECT_R_PVALUE_RANGE(r.fold_errors, Case, kFoldErrors);
    EXPECT_R_PVALUE(r.mean_error, Case, kMeanError);
    EXPECT_R_PVALUE(r.se_error, Case, kSeError);
    EXPECT_EQ(r.n_folds, Case::kK);
}

/// @brief Ridge path selection over the same deterministic folds.
TEST(RConditional, CvRidge) {
    using Case = ref::CvRidge;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto grid = AsVector(Case::kLambdaGrid);
    const auto [best, errors] = statcpp::cv_ridge(X, y, grid, Case::kK, false);
    EXPECT_R_PVALUE_RANGE(errors, Case, kCvErrors);
    EXPECT_R_PVALUE(best, Case, kBestLambda);
}

/// @brief Lasso path selection over the same deterministic folds.
TEST(RConditional, CvLasso) {
    using Case = ref::CvLasso;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto grid = AsVector(Case::kLambdaGrid);
    const auto [best, errors] = statcpp::cv_lasso(X, y, grid, Case::kK, false);
    EXPECT_R_PVALUE_RANGE(errors, Case, kCvErrors);
    EXPECT_R_PVALUE(best, Case, kBestLambda);
}

/// @brief Deterministic fold construction.
TEST(RConditional, CreateCvFolds) {
    using Case = ref::CreateCvFolds;
    const auto folds = statcpp::create_cv_folds(Case::kN, Case::kK, false);
    ASSERT_EQ(folds.size(), Case::kK);
    std::vector<double> sizes, firsts, flat;
    for (const auto& f : folds) {
        sizes.push_back(static_cast<double>(f.size()));
        firsts.push_back(static_cast<double>(f.front()));
        for (const auto i : f) flat.push_back(static_cast<double>(i));
    }
    EXPECT_R_RANGE(sizes, Case, kFoldSizes);
    EXPECT_R_RANGE(firsts, Case, kFirstIndices);
    EXPECT_R_RANGE(flat, Case, kFlatIndices);
}

}  // namespace
