/**
 * @file test_vs_r_inference.cpp
 * @brief Compare statcpp effect sizes, interval estimation and power against R 4.4.2.
 *
 * Covers effect_size.hpp, estimation.hpp and power_analysis.hpp. Reference
 * values come from r_reference_inference.hpp, generated by
 * generate_r_reference.R.
 */

#include <cstddef>
#include <iterator>
#include <vector>

#include <gtest/gtest.h>

#include "statcpp/effect_size.hpp"
#include "statcpp/estimation.hpp"
#include "statcpp/power_analysis.hpp"

#include "r_compare.hpp"
#include "r_reference_inference.hpp"

namespace {

namespace ref = statcpp_test::r_ref;

/// @brief Copy a reference array into the vector type the statcpp API expects.
template <std::size_t N>
std::vector<double> AsVector(const double (&values)[N])
{
    return std::vector<double>(values, values + N);
}

// ============================================================================
// effect_size.hpp
// ============================================================================

/// @brief Sample-based effect sizes, cross-checked against the effectsize package.
TEST(REffectSize, SampleBased) {
    using Case = ref::EffectSizeSamples;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto xb = x.begin(), xe = x.end(), yb = y.begin(), ye = y.end();
    EXPECT_R_FIELD(statcpp::cohens_d(xb, xe, Case::kMu0), Case, kCohensDOneSample);
    EXPECT_R_FIELD(statcpp::hedges_g(xb, xe, Case::kMu0), Case, kHedgesGOneSample);
    EXPECT_R_FIELD(statcpp::cohens_d_two_sample(xb, xe, yb, ye), Case, kCohensDTwoSample);
    EXPECT_R_FIELD(statcpp::hedges_g_two_sample(xb, xe, yb, ye), Case, kHedgesGTwoSample);
    // glass_delta divides by the standard deviation of the control sample.
    EXPECT_R_FIELD(statcpp::glass_delta(xb, xe, yb, ye), Case, kGlassDelta);
    EXPECT_R_FIELD(statcpp::hedges_correction_factor(static_cast<double>(x.size() + y.size() - 2)),
                   Case, kHedgesCorrectionFactor);
    // Cohen's d matches the effectsize package exactly. Hedges' g does not:
    // effectsize uses the exact gamma-based correction factor while statcpp uses
    // the standard 1 - 3/(4 df - 1) approximation, so only closeness is asserted.
    EXPECT_R_FIELD(statcpp::cohens_d_two_sample(xb, xe, yb, ye), Case, kEffectsizeDCheck);
    EXPECT_NEAR(statcpp::hedges_g_two_sample(xb, xe, yb, ye), Case::kEffectsizeGCheck, 1e-3);
}

/// @brief Effect-size conversions and the 2x2 measures.
TEST(REffectSize, Conversions) {
    using Case = ref::EffectSizeConversions;
    EXPECT_R_FIELD(statcpp::d_to_r(Case::kD), Case, kDToR);
    EXPECT_R_FIELD(statcpp::d_to_r(Case::kD), Case, kEffectsizeDToRCheck);
    EXPECT_R_FIELD(statcpp::r_to_d(Case::kR), Case, kRToD);
    EXPECT_R_FIELD(statcpp::t_to_r(Case::kT, Case::kDf), Case, kTToR);
    EXPECT_R_FIELD(statcpp::partial_eta_squared(Case::kF, Case::kDf1, Case::kDf2), Case,
                   kPartialEtaSquared);
    EXPECT_R_FIELD(statcpp::cohens_h(Case::kP1, Case::kP2), Case, kCohensH);
    EXPECT_R_FIELD(statcpp::eta_squared(Case::kSsEffect, Case::kSsTotal), Case, kEtaSquared);
    EXPECT_R_FIELD(statcpp::omega_squared(Case::kSsEffect, Case::kSsTotal, Case::kMsError,
                                           Case::kDfEffect),
                   Case, kOmegaSquared);
    EXPECT_R_FIELD(statcpp::odds_ratio(Case::kA, Case::kB, Case::kC, Case::kDCell), Case,
                   kOddsRatio);
    EXPECT_R_FIELD(statcpp::risk_ratio(Case::kA, Case::kB, Case::kC, Case::kDCell), Case,
                   kRiskRatio);
}

// ============================================================================
// estimation.hpp
// ============================================================================

/// @brief Confidence intervals for means and variances.
TEST(REstimation, Means) {
    using Case = ref::EstimationMeans;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto xb = x.begin(), xe = x.end(), yb = y.begin(), ye = y.end();

    const auto ci = statcpp::ci_mean(xb, xe, Case::kConfidence);
    EXPECT_R_PVALUE(ci.lower, Case, kCiMeanLower);
    EXPECT_R_PVALUE(ci.upper, Case, kCiMeanUpper);
    EXPECT_R_FIELD(ci.point_estimate, Case, kCiMeanEstimate);

    const auto ciz = statcpp::ci_mean_z(xb, xe, Case::kSigma, Case::kConfidence);
    EXPECT_R_PVALUE(ciz.lower, Case, kCiMeanZLower);
    EXPECT_R_PVALUE(ciz.upper, Case, kCiMeanZUpper);

    // ci_mean_diff delegates to the pooled interval, not the Welch one.
    const auto cid = statcpp::ci_mean_diff(xb, xe, yb, ye, Case::kConfidence);
    EXPECT_R_PVALUE(cid.lower, Case, kCiDiffPooledLower);
    EXPECT_R_PVALUE(cid.upper, Case, kCiDiffPooledUpper);
    const auto ciw = statcpp::ci_mean_diff_welch(xb, xe, yb, ye, Case::kConfidence);
    EXPECT_R_PVALUE(ciw.lower, Case, kCiDiffWelchLower);
    EXPECT_R_PVALUE(ciw.upper, Case, kCiDiffWelchUpper);
    const auto cip = statcpp::ci_mean_diff_pooled(xb, xe, yb, ye, Case::kConfidence);
    EXPECT_R_PVALUE(cip.lower, Case, kCiDiffPooledLower);
    EXPECT_R_PVALUE(cip.upper, Case, kCiDiffPooledUpper);

    const auto civ = statcpp::ci_variance(xb, xe, Case::kConfidence);
    EXPECT_R_PVALUE(civ.lower, Case, kCiVarianceLower);
    EXPECT_R_PVALUE(civ.upper, Case, kCiVarianceUpper);

    EXPECT_R_FIELD(statcpp::standard_error(xb, xe), Case, kStandardError);
    EXPECT_R_PVALUE(statcpp::margin_of_error_mean(xb, xe, Case::kConfidence), Case,
                    kMarginOfErrorMean);
}

/// @brief Confidence intervals and margins of error for proportions.
TEST(REstimation, Proportions) {
    using Case = ref::EstimationProportions;
    // ci_proportion is the Wald interval.
    const auto wald = statcpp::ci_proportion(Case::kSuccesses, Case::kTrials, Case::kConfidence);
    EXPECT_R_PVALUE(wald.lower, Case, kWaldLower);
    EXPECT_R_PVALUE(wald.upper, Case, kWaldUpper);

    // ci_proportion_wilson is the score interval and matches prop.test(correct = FALSE).
    const auto wilson =
        statcpp::ci_proportion_wilson(Case::kSuccesses, Case::kTrials, Case::kConfidence);
    EXPECT_R_PVALUE(wilson.lower, Case, kWilsonLower);
    EXPECT_R_PVALUE(wilson.upper, Case, kWilsonUpper);

    const auto diff = statcpp::ci_proportion_diff(Case::kSuccesses, Case::kTrials,
                                                   Case::kSuccesses2, Case::kTrials2,
                                                   Case::kConfidence);
    EXPECT_R_PVALUE(diff.lower, Case, kDiffLower);
    EXPECT_R_PVALUE(diff.upper, Case, kDiffUpper);

    EXPECT_R_PVALUE(
        statcpp::margin_of_error_proportion(Case::kSuccesses, Case::kTrials, Case::kConfidence),
        Case, kMarginOfError);
    EXPECT_R_PVALUE(
        statcpp::margin_of_error_proportion_worst_case(Case::kTrials, Case::kConfidence), Case,
        kMarginOfErrorWorstCase);
    EXPECT_R_FIELD(static_cast<double>(statcpp::sample_size_for_moe_mean(
                       Case::kMoeTarget, Case::kMoeSigma, Case::kConfidence)),
                   Case, kSampleSizeMean);
    EXPECT_R_FIELD(static_cast<double>(statcpp::sample_size_for_moe_proportion(
                       Case::kMoePTarget, Case::kConfidence, 0.5)),
                   Case, kSampleSizeProportion);
}

// ============================================================================
// power_analysis.hpp
// ============================================================================

/// @brief t-test power; statcpp uses a documented normal approximation.
///
/// The reference reproduces that approximation. R's power.t.test uses the
/// noncentral t distribution, and the gap between the two is asserted rather
/// than ignored: it is real and around four percentage points here.
TEST(RPowerAnalysis, TTest) {
    using Case = ref::PowerTTest;
    EXPECT_R_PVALUE(statcpp::power_t_test_one_sample(Case::kEffectSize, Case::kN, Case::kAlpha),
                    Case, kPowerOneSample);
    EXPECT_R_PVALUE(
        statcpp::power_t_test_two_sample(Case::kEffectSize, Case::kN1, Case::kN2, Case::kAlpha),
        Case, kPowerTwoSample);
    EXPECT_R_FIELD(static_cast<double>(statcpp::sample_size_t_test_one_sample(
                       Case::kEffectSize, Case::kTargetPower, Case::kAlpha)),
                   Case, kSampleSizeOne);
    EXPECT_R_FIELD(static_cast<double>(statcpp::sample_size_t_test_two_sample(
                       Case::kEffectSize, Case::kTargetPower, Case::kAlpha, Case::kRatio)),
                   Case, kSampleSizeTwo);

    const auto pa = statcpp::power_analysis_t_one_sample(Case::kEffectSize, Case::kN, Case::kAlpha);
    EXPECT_R_PVALUE(pa.power, Case, kPowerOneSample);
    const auto pn = statcpp::power_analysis_t_one_sample_n(Case::kEffectSize, Case::kTargetPower,
                                                            Case::kAlpha);
    EXPECT_R_FIELD(pn.sample_size, Case, kSampleSizeOne);

    // The normal approximation is optimistic relative to the noncentral t.
    EXPECT_GT(Case::kPowerOneSample, Case::kRPowerTTest);
    EXPECT_LT(Case::kPowerOneSample - Case::kRPowerTTest, 0.05);
    EXPECT_LT(Case::kSampleSizeOne, Case::kRSampleSize);
}

/// @brief Proportion power; statcpp implements the same closed form as R.
TEST(RPowerAnalysis, PropTest) {
    using Case = ref::PowerPropTest;
    EXPECT_R_PVALUE(statcpp::power_prop_test(Case::kP1, Case::kP2, Case::kN, Case::kAlpha), Case,
                    kPower);
    EXPECT_R_FIELD(static_cast<double>(statcpp::sample_size_prop_test(
                       Case::kP1, Case::kP2, Case::kTargetPower, Case::kAlpha)),
                   Case, kSampleSize);
}

}  // namespace
