/**
 * @file test_vs_r_data.cpp
 * @brief Compare statcpp data-handling modules against R 4.4.2 reference values.
 *
 * Covers data_wrangling.hpp, missing_data.hpp and numerical_utils.hpp.
 * Reference values come from r_reference_data.hpp, generated by
 * generate_r_reference.R.
 */

#include <algorithm>
#include <cstddef>
#include <iterator>
#include <map>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "statcpp/data_wrangling.hpp"
#include "statcpp/missing_data.hpp"
#include "statcpp/numerical_utils.hpp"

#include "r_compare.hpp"
#include "r_reference_data.hpp"

namespace {

namespace ref = statcpp_test::r_ref;
using statcpp_test::MakeMatrix;

/// @brief Copy a reference array into the vector type the statcpp API expects.
template <std::size_t N>
std::vector<double> AsVector(const double (&values)[N])
{
    return std::vector<double>(values, values + N);
}

/// @brief Flatten a matrix in row-major order for comparison against the reference.
std::vector<double> Flatten(const std::vector<std::vector<double>>& m)
{
    std::vector<double> out;
    for (const auto& row : m) out.insert(out.end(), row.begin(), row.end());
    return out;
}

/// @brief Widen an integral sequence for comparison against a double reference.
template <typename T>
std::vector<double> ToDouble(const std::vector<T>& v)
{
    std::vector<double> out;
    out.reserve(v.size());
    for (const auto e : v) out.push_back(static_cast<double>(e));
    return out;
}

// ============================================================================
// data_wrangling.hpp
// ============================================================================

/// @brief Element-wise transforms, ranks and rolling windows.
TEST(RDataWrangling, TransformsAndRolling) {
    using Case = ref::Transforms;
    const auto x = AsVector(Case::kX);
    EXPECT_R_RANGE(statcpp::log_transform(x), Case, kLogTransform);
    EXPECT_R_RANGE(statcpp::log1p_transform(x), Case, kLog1pTransform);
    EXPECT_R_RANGE(statcpp::sqrt_transform(x), Case, kSqrtTransform);
    EXPECT_R_RANGE(statcpp::boxcox_transform(x, Case::kLambda), Case, kBoxcox);
    EXPECT_R_RANGE(statcpp::rank_transform(x), Case, kRankTransform);
    // The rolling functions emit one value per complete window.
    EXPECT_R_RANGE(statcpp::rolling_mean(x, Case::kWindow), Case, kRollingMean);
    EXPECT_R_RANGE(statcpp::rolling_sum(x, Case::kWindow), Case, kRollingSum);
    EXPECT_R_RANGE(statcpp::rolling_min(x, Case::kWindow), Case, kRollingMin);
    EXPECT_R_RANGE(statcpp::rolling_max(x, Case::kWindow), Case, kRollingMax);
    EXPECT_R_RANGE(statcpp::rolling_std(x, Case::kWindow), Case, kRollingStd);
}

/// @brief Missing-value filling against mean, median, na.locf and na.approx.
TEST(RDataWrangling, FillNa) {
    using Case = ref::FillNa;
    const auto x = AsVector(Case::kX);
    EXPECT_R_RANGE(statcpp::fillna_mean(x), Case, kFillMean);
    EXPECT_R_RANGE(statcpp::fillna_median(x), Case, kFillMedian);
    EXPECT_R_RANGE(statcpp::fillna_ffill(x), Case, kFfill);
    EXPECT_R_RANGE(statcpp::fillna_bfill(x), Case, kBfill);
    EXPECT_R_RANGE(statcpp::fillna_interpolate(x), Case, kInterpolate);
}

/// @brief Sorting, de-duplication, counting and encoding.
TEST(RDataWrangling, SortingAndEncoding) {
    using Case = ref::Encoding;
    const auto x = AsVector(Case::kX);
    EXPECT_R_RANGE(statcpp::sort_values(x), Case, kSorted);
    EXPECT_R_RANGE(statcpp::sort_values(x, false), Case, kSortedDesc);
    // argsort is zero-based in C++ and one-based in R.
    EXPECT_R_RANGE(ToDouble(statcpp::argsort(x)), Case, kArgsort);
    EXPECT_R_RANGE(statcpp::drop_duplicates(x), Case, kUniqueValues);
    // get_duplicates returns its values in unspecified order.
    auto dupes = statcpp::get_duplicates(x);
    std::sort(dupes.begin(), dupes.end());
    EXPECT_R_RANGE(dupes, Case, kDuplicatedValues);

    const auto counts = statcpp::value_counts(x);
    std::vector<double> keys, values;
    for (const auto& [key, count] : counts) {
        keys.push_back(key);
        values.push_back(static_cast<double>(count));
    }
    EXPECT_R_RANGE(keys, Case, kValueCountsKeys);
    EXPECT_R_RANGE(values, Case, kValueCountsValues);

    const auto encoded = statcpp::label_encode(x);
    EXPECT_R_RANGE(ToDouble(encoded.encoded), Case, kLabelEncoded);
    EXPECT_R_RANGE(encoded.classes, Case, kClasses);
    // Columns follow the first-appearance class order that label_encode assigns.
    EXPECT_R_RANGE(Flatten(statcpp::one_hot_encode(x)), Case, kOneHot);
}

/// @brief Equal-width and equal-frequency binning.
TEST(RDataWrangling, Binning) {
    using Case = ref::Binning;
    const auto x = AsVector(Case::kX);
    EXPECT_R_RANGE(ToDouble(statcpp::bin_equal_width(x, Case::kNBins)), Case, kEqualWidth);
    // Only the bin occupancies are compared: the tie-breaking rule at a bin edge
    // is implementation specific.
    const auto bins = statcpp::bin_equal_freq(x, Case::kNBins);
    std::map<std::size_t, std::size_t> occupancy;
    for (const auto b : bins) ++occupancy[b];
    std::vector<double> counts;
    for (const auto& [bin, count] : occupancy) counts.push_back(static_cast<double>(count));
    EXPECT_R_RANGE(counts, Case, kEqualFreqCounts);
}

/// @brief Grouped aggregation against tapply.
TEST(RDataWrangling, GroupBy) {
    using Case = ref::GroupBy;
    const std::vector<std::string> keys{"a", "b", "a", "c", "b", "a", "c", "b"};
    const auto values = AsVector(Case::kValues);
    EXPECT_R_RANGE(statcpp::group_sum(keys, values).values, Case, kGroupSum);
    EXPECT_R_RANGE(statcpp::group_mean(keys, values).values, Case, kGroupMean);
    EXPECT_R_RANGE(statcpp::group_count(keys, values).values, Case, kGroupCount);
}

// ============================================================================
// missing_data.hpp
// ============================================================================

/// @brief Complete cases, missing indicators, pairwise correlation and imputation.
TEST(RMissingData, All) {
    using Case = ref::MissingData;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto cc = statcpp::extract_complete_cases(X);
    EXPECT_R_RANGE(Flatten(cc.complete_data), Case, kCompleteData);
    EXPECT_R_FIELD(static_cast<double>(cc.n_complete), Case, kNComplete);
    EXPECT_R_FIELD(static_cast<double>(cc.n_dropped), Case, kNDropped);
    EXPECT_R_FIELD(cc.proportion_complete, Case, kProportionComplete);
    EXPECT_R_RANGE(Flatten(statcpp::create_missing_indicator(X)), Case, kMissingIndicator);
    EXPECT_R_RANGE(Flatten(statcpp::correlation_matrix_pairwise(X)), Case, kPairwiseCorrelation);
    // Only the first predictor column is used by this function.
    EXPECT_R_PVALUE_RANGE(statcpp::impute_conditional_mean(X, 1, {0, 2}), Case, kImputedColumn);
}

// ============================================================================
// numerical_utils.hpp
// ============================================================================

/// @brief log1p, expm1 and a compensated sum.
TEST(RNumericalUtils, All) {
    using Case = ref::NumericalUtils;
    const auto x = AsVector(Case::kX);
    std::vector<double> l, e;
    for (const double v : x) {
        l.push_back(statcpp::log1p_safe(v));
        e.push_back(statcpp::expm1_safe(v));
    }
    EXPECT_R_RANGE(l, Case, kLog1p);
    EXPECT_R_RANGE(e, Case, kExpm1);

    const auto k = AsVector(Case::kKahanInput);
    EXPECT_R_FIELD(statcpp::kahan_sum(k.begin(), k.end()), Case, kKahanSum);
}

}  // namespace
