/**
 * @file test_vs_r_nan.cpp
 * @brief Compare statcpp against R 4.4.2 on inputs containing missing values.
 *
 * statcpp represents NA as NaN and follows the default NA handling of the R
 * counterpart of each function (docs/NAN_POLICY.md). The reference values and
 * the inputs, NA included, come from r_reference_nan.hpp, which is generated by
 * generate_r_reference.R. R is not needed to build or run this test.
 *
 * Functions that throw on NaN have no R value to compare against; they are
 * covered by the GTest suite in test/.
 */

#include <cstddef>
#include <iterator>
#include <vector>

#include <gtest/gtest.h>

#include "statcpp/anova.hpp"
#include "statcpp/clustering.hpp"
#include "statcpp/correlation_covariance.hpp"
#include "statcpp/data_wrangling.hpp"
#include "statcpp/distance_metrics.hpp"
#include "statcpp/glm.hpp"
#include "statcpp/linear_regression.hpp"
#include "statcpp/multivariate.hpp"
#include "statcpp/nonparametric_tests.hpp"
#include "statcpp/parametric_tests.hpp"
#include "statcpp/survival.hpp"
#include "statcpp/time_series.hpp"

#include "r_compare.hpp"
#include "r_reference_nan.hpp"

namespace {

using statcpp_test::MakeGroups;
using statcpp_test::MakeMatrix;
namespace ref = statcpp_test::r_ref;

/// @brief Copy a reference array into a vector, without needing the case type.
template <std::size_t N>
std::vector<double> AsVector(const double (&values)[N])
{
    return std::vector<double>(values, values + N);
}

/// @brief Convert a 0/1 reference array into the event flags statcpp expects.
template <std::size_t N>
std::vector<bool> AsEvents(const double (&values)[N])
{
    std::vector<bool> out;
    out.reserve(N);
    for (const double v : values) out.push_back(v != 0.0);
    return out;
}

/// @brief Flatten a matrix in row-major order for comparison against the reference.
std::vector<double> Flatten(const std::vector<std::vector<double>>& m)
{
    std::vector<double> out;
    for (const auto& row : m) out.insert(out.end(), row.begin(), row.end());
    return out;
}

// ============================================================================
// Removal: tests and estimators
// ============================================================================

/// @brief One-sample t-test with NA, against t.test(x, mu).
TEST(RNaRemoval, TTestOneSample) {
    using Case = ref::NaTTestOneSample;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::t_test(x.begin(), x.end(), Case::kMu0);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Pooled two-sample t-test with NA, against t.test(x, y, var.equal = TRUE).
TEST(RNaRemoval, TTestTwoSample) {
    using Case = ref::NaTTestTwoSample;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto r = statcpp::t_test_two_sample(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Welch t-test with NA, against t.test(x, y).
TEST(RNaRemoval, TTestWelch) {
    using Case = ref::NaTTestWelch;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto r = statcpp::t_test_welch(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Paired t-test with NA on either side, against t.test(x, y, paired = TRUE).
TEST(RNaRemoval, TTestPaired) {
    using Case = ref::NaTTestPaired;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto r = statcpp::t_test_paired(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Variance ratio F-test with NA, against var.test(x, y).
TEST(RNaRemoval, FTest) {
    using Case = ref::NaFTest;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto r = statcpp::f_test(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_FIELD(r.df2, Case, kDf2);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Wilcoxon signed-rank test with NA, against wilcox.test(x, mu).
TEST(RNaRemoval, WilcoxonSignedRank) {
    using Case = ref::NaWilcoxonSignedRank;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::wilcoxon_signed_rank_test(x.begin(), x.end(), Case::kMu0);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Mann-Whitney U test with NA, against wilcox.test(x, y).
TEST(RNaRemoval, MannWhitneyU) {
    using Case = ref::NaMannWhitneyU;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto r = statcpp::mann_whitney_u_test(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Kruskal-Wallis test with NA in every group, against kruskal.test.
TEST(RNaRemoval, KruskalWallis) {
    using Case = ref::NaKruskalWallis;
    const auto groups = MakeGroups(Case::kGroupsFlat, Case::kGroupsSizes, Case::kGroupsCount);
    const auto r = statcpp::kruskal_wallis_test(groups);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Shapiro-Wilk test with NA, against shapiro.test, with a loose bound.
TEST(RNaRemoval, ShapiroWilk) {
    using Case = ref::NaShapiroWilk;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::shapiro_wilk_test(x.begin(), x.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief One-way ANOVA with NA in every group, against summary(aov(y ~ g)).
TEST(RNaRemoval, OneWayAnova) {
    using Case = ref::NaOneWayAnova;
    const auto groups = MakeGroups(Case::kGroupsFlat, Case::kGroupsSizes, Case::kGroupsCount);
    const auto r = statcpp::one_way_anova(groups);
    EXPECT_R_FIELD(r.between.f_statistic, Case, kFStatistic);
    EXPECT_R_PVALUE(r.between.p_value, Case, kPValue);
    EXPECT_R_FIELD(r.between.df, Case, kDfBetween);
    EXPECT_R_FIELD(r.within.df, Case, kDfWithin);
    EXPECT_R_FIELD(r.between.ss, Case, kSsBetween);
    EXPECT_R_FIELD(r.within.ss, Case, kSsWithin);
}

/// @brief Kaplan-Meier estimator with NA times, against survfit.
TEST(RNaRemoval, KaplanMeier) {
    using Case = ref::NaKaplanMeier;
    const auto km = statcpp::kaplan_meier(AsVector(Case::kTimes), AsEvents(Case::kEvents));
    EXPECT_R_RANGE(km.times, Case, kEventTimes);
    EXPECT_R_RANGE(km.survival, Case, kSurvival);
}

// ============================================================================
// Propagation: descriptive statistics and correlation
// ============================================================================

/// @brief Descriptive statistics are NaN when the data contain NaN, as in R.
TEST(RNaPropagation, Descriptive) {
    using Case = ref::NaDescriptive;
    const auto x = AsVector(Case::kX);
    EXPECT_R_FIELD(statcpp::mean(x.begin(), x.end()), Case, kMean);
    EXPECT_R_FIELD(statcpp::sample_variance(x.begin(), x.end()), Case, kVariance);
    EXPECT_R_FIELD(statcpp::sample_stddev(x.begin(), x.end()), Case, kStddev);
    EXPECT_R_FIELD(statcpp::median(x.begin(), x.end()), Case, kMedian);
    EXPECT_R_FIELD(statcpp::range(x.begin(), x.end()), Case, kRange);
}

/// @brief Correlation coefficients are NaN when either input contains NaN, as in R's cor.
TEST(RNaPropagation, Correlation) {
    using Case = ref::NaCorrelation;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    EXPECT_R_FIELD(statcpp::pearson_correlation(x.begin(), x.end(), y.begin(), y.end()), Case, kPearson);
    EXPECT_R_FIELD(statcpp::spearman_correlation(x.begin(), x.end(), y.begin(), y.end()), Case, kSpearman);
    EXPECT_R_FIELD(statcpp::kendall_tau(x.begin(), x.end(), y.begin(), y.end()), Case, kKendall);
}

// ============================================================================
// Element-wise: adjustments, scaling and filters
// ============================================================================

/// @brief Multiplicity corrections count only the non-NaN p-values, as p.adjust does.
TEST(RNaElementwise, PAdjust) {
    using Case = ref::NaPAdjust;
    const auto p = AsVector(Case::kPValues);
    EXPECT_R_RANGE(statcpp::bonferroni_correction(p), Case, kBonferroni);
    EXPECT_R_RANGE(statcpp::holm_correction(p), Case, kHolm);
    EXPECT_R_RANGE(statcpp::benjamini_hochberg_correction(p), Case, kBh);
}

/// @brief standardize follows scale(): column statistics from the non-NaN values.
TEST(RNaElementwise, Scale) {
    using Case = ref::NaScale;
    const auto x = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto z = statcpp::standardize(x);
    EXPECT_R_RANGE(Flatten(z), Case, kScaledFlat);
}

/// @brief moving_average gives NaN only for the windows containing NaN, as stats::filter does.
TEST(RNaElementwise, MovingAverage) {
    using Case = ref::NaMovingAverage;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::moving_average(x.begin(), x.end(), Case::kWindow);
    EXPECT_R_RANGE(r, Case, kAverage);
}

// ============================================================================
// Distances: NaN coordinates skipped and the sum rescaled
// ============================================================================

/// @brief Lp distances follow dist(): NaN coordinates are skipped and the sum is rescaled.
TEST(RNaDistance, Dist) {
    using Case = ref::NaDistance;
    const auto a = AsVector(Case::kA);
    const auto b = AsVector(Case::kB);
    EXPECT_R_FIELD(statcpp::euclidean_distance(a.begin(), a.end(), b.begin(), b.end()), Case, kEuclidean);
    EXPECT_R_FIELD(statcpp::manhattan_distance(a.begin(), a.end(), b.begin(), b.end()), Case, kManhattan);
    EXPECT_R_FIELD(statcpp::minkowski_distance(a.begin(), a.end(), b.begin(), b.end(), Case::kP), Case,
                   kMinkowski);
    // The vector overloads in clustering.hpp follow the same rule.
    EXPECT_R_FIELD(statcpp::euclidean_distance(a, b), Case, kEuclidean);
    EXPECT_R_FIELD(statcpp::manhattan_distance(a, b), Case, kManhattan);
}

// ============================================================================
// Row removal: models (na.omit)
// ============================================================================

/// @brief Simple regression with NA, against lm(y ~ x).
TEST(RNaModels, SimpleLinearRegression) {
    using Case = ref::NaSimpleLinearRegression;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::simple_linear_regression(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(m.intercept, Case, kIntercept);
    EXPECT_R_FIELD(m.slope, Case, kSlope);
    EXPECT_R_FIELD(m.r_squared, Case, kRSquared);
    EXPECT_R_FIELD(m.residual_se, Case, kResidualSe);
    EXPECT_R_FIELD(m.df_residual, Case, kDfResidual);
}

/// @brief Multiple regression with NA in X and y, against lm(y ~ X).
TEST(RNaModels, MultipleLinearRegression) {
    using Case = ref::NaMultipleLinearRegression;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::multiple_linear_regression(X, y);
    EXPECT_R_RANGE(m.coefficients, Case, kCoefficients);
    EXPECT_R_FIELD(m.r_squared, Case, kRSquared);
    EXPECT_R_FIELD(m.df_residual, Case, kDfResidual);
}

/// @brief Logistic regression with NA in x and y, against glm(family = binomial()).
TEST(RNaModels, LogisticRegression) {
    using Case = ref::NaLogisticRegression;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::logistic_regression(X, y);
    ASSERT_TRUE(m.converged);
    EXPECT_R_RANGE(m.coefficients, Case, kCoefficients);
    EXPECT_R_FIELD(m.residual_deviance, Case, kResidualDeviance);
    EXPECT_R_FIELD(m.df_residual, Case, kDfResidual);
}

/// @brief Poisson regression with NA in x and y, against glm(family = poisson()).
TEST(RNaModels, PoissonRegression) {
    using Case = ref::NaPoissonRegression;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::poisson_regression(X, y);
    ASSERT_TRUE(m.converged);
    EXPECT_R_RANGE(m.coefficients, Case, kCoefficients);
    EXPECT_R_FIELD(m.residual_deviance, Case, kResidualDeviance);
    EXPECT_R_FIELD(m.df_residual, Case, kDfResidual);
}

// ============================================================================
// Ordering and duplicates
// ============================================================================

/// @brief sort_values drops NaN, argsort places it last, rank_transform keeps it.
TEST(RNaOrdering, SortOrderRank) {
    using Case = ref::NaSortOrder;
    const auto x = AsVector(Case::kX);
    EXPECT_R_RANGE(statcpp::sort_values(x), Case, kSorted);
    EXPECT_R_RANGE(statcpp::sort_values(x, false), Case, kSortedDecreasing);
    EXPECT_R_RANGE(statcpp::rank_transform(x), Case, kRank);

    // Tied values may come in either order, so the comparison is on the values each
    // order selects; NaN positions must match exactly because NaN keeps its original order.
    auto selected = [&x](const std::vector<std::size_t>& order) {
        std::vector<double> out;
        for (const std::size_t i : order) out.push_back(x[i]);
        return out;
    };
    auto selected_ref = [&x](const double* order, std::size_t n) {
        std::vector<double> out;
        for (std::size_t k = 0; k < n; ++k) out.push_back(x[static_cast<std::size_t>(order[k])]);
        return out;
    };
    const auto asc = statcpp::argsort(x);
    const auto desc = statcpp::argsort(x, false);
    EXPECT_EQ(asc.size(), std::size(Case::kOrder));
    const auto asc_ref = selected_ref(Case::kOrder, std::size(Case::kOrder));
    const auto desc_ref = selected_ref(Case::kOrderDecreasing, std::size(Case::kOrderDecreasing));
    EXPECT_TRUE(statcpp_test::RCloseRange(selected(asc), asc_ref.data(), asc_ref.size(), Case::kRtol, Case::kAtol));
    EXPECT_TRUE(statcpp_test::RCloseRange(selected(desc), desc_ref.data(), desc_ref.size(), Case::kRtol, Case::kAtol));
    for (std::size_t k = asc.size() - 2; k < asc.size(); ++k) {
        EXPECT_EQ(static_cast<double>(asc[k]), Case::kOrder[k]);
        EXPECT_EQ(static_cast<double>(desc[k]), Case::kOrderDecreasing[k]);
    }
}

/// @brief drop_duplicates keeps one NaN, as unique does.
TEST(RNaOrdering, Unique) {
    using Case = ref::NaUnique;
    EXPECT_R_RANGE(statcpp::drop_duplicates(AsVector(Case::kX)), Case, kUnique);
}

}  // namespace
