/**
 * @file test_vs_r_hypothesis.cpp
 * @brief Compare statcpp hypothesis tests against R 4.4.2 reference values.
 *
 * Covers parametric_tests.hpp, nonparametric_tests.hpp and anova.hpp.
 * Reference values and input data both come from r_reference_hypothesis.hpp,
 * which is generated by generate_r_reference.R. R is not needed to build or run
 * this test.
 */

#include <cstddef>
#include <iterator>
#include <utility>
#include <vector>

#include <gtest/gtest.h>

#include "statcpp/anova.hpp"
#include "statcpp/nonparametric_tests.hpp"
#include "statcpp/parametric_tests.hpp"

#include "r_compare.hpp"
#include "r_reference_hypothesis.hpp"

namespace {

using statcpp_test::MakeGroups;
using statcpp_test::MakeMatrix;
namespace ref = statcpp_test::r_ref;

/// @brief Copy a reference array into a vector, without needing the case type.
template <std::size_t N>
std::vector<double> AsVector(const double (&values)[N])
{
    return std::vector<double>(values, values + N);
}

/// @brief Extract one field from every pairwise comparison of a post-hoc result.
template <typename Projection>
std::vector<double> Project(const statcpp::posthoc_result& result, Projection projection)
{
    std::vector<double> out;
    out.reserve(result.comparisons.size());
    for (const auto& comparison : result.comparisons) out.push_back(projection(comparison));
    return out;
}

// ============================================================================
// parametric_tests.hpp
// ============================================================================

/// @brief One-sample t-test against t.test(x, mu).
TEST(RParametricTests, TTestOneSample) {
    using Case = ref::TTestOneSample;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::t_test(x.begin(), x.end(), Case::kMu0);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief One-sided t-test against t.test(x, mu, alternative = "greater").
TEST(RParametricTests, TTestOneSampleGreater) {
    using Case = ref::TTestOneSampleGreater;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::t_test(x.begin(), x.end(), Case::kMu0,
                                   statcpp::alternative_hypothesis::greater);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Pooled-variance two-sample t-test against t.test(x, y, var.equal = TRUE).
TEST(RParametricTests, TTestTwoSample) {
    using Case = ref::TTestTwoSample;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto r = statcpp::t_test_two_sample(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Welch t-test against t.test(x, y).
TEST(RParametricTests, TTestWelch) {
    using Case = ref::TTestWelch;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto r = statcpp::t_test_welch(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Paired t-test against t.test(x, y, paired = TRUE).
TEST(RParametricTests, TTestPaired) {
    using Case = ref::TTestPaired;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto r = statcpp::t_test_paired(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief One-sample z-test; df is infinite because the variance is known.
TEST(RParametricTests, ZTest) {
    using Case = ref::ZTest;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::z_test(x.begin(), x.end(), Case::kMu0, Case::kSigma);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
    EXPECT_R_FIELD(r.df, Case, kDf);
}

/// @brief Variance ratio F-test against var.test(x, y).
TEST(RParametricTests, FTest) {
    using Case = ref::FTest;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto r = statcpp::f_test(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_FIELD(r.df2, Case, kDf2);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Goodness-of-fit chi-squared test with explicit expected counts.
TEST(RParametricTests, ChisqTestGof) {
    using Case = ref::ChisqTestGof;
    const auto observed = AsVector(Case::kObserved);
    const auto expected = AsVector(Case::kExpected);
    const auto r = statcpp::chisq_test_gof(observed.begin(), observed.end(), expected.begin(),
                                            expected.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Goodness-of-fit chi-squared test against a uniform expectation.
TEST(RParametricTests, ChisqTestGofUniform) {
    using Case = ref::ChisqTestGofUniform;
    const auto observed = AsVector(Case::kObserved);
    const auto r = statcpp::chisq_test_gof_uniform(observed.begin(), observed.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Chi-squared test of independence without the Yates correction.
TEST(RParametricTests, ChisqTestIndependence) {
    using Case = ref::ChisqTestIndependence;
    const auto table = MakeMatrix(Case::kTableFlat, Case::kTableRows, Case::kTableCols);
    const auto r = statcpp::chisq_test_independence(table);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief One-sample proportion z-test; the squared statistic matches prop.test.
TEST(RParametricTests, ZTestProportion) {
    using Case = ref::ZTestProportion;
    const auto r = statcpp::z_test_proportion(Case::kSuccesses, Case::kTrials, Case::kP0);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
    EXPECT_R_FIELD(r.statistic * r.statistic, Case, kChisqCrossCheck);
}

/// @brief Two-sample proportion z-test; the squared statistic matches prop.test.
TEST(RParametricTests, ZTestProportionTwoSample) {
    using Case = ref::ZTestProportionTwoSample;
    const auto r = statcpp::z_test_proportion_two_sample(Case::kSuccesses1, Case::kTrials1,
                                                          Case::kSuccesses2, Case::kTrials2);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
    EXPECT_R_FIELD(r.statistic * r.statistic, Case, kChisqCrossCheck);
}

/// @brief Bonferroni multiplicity correction against p.adjust.
TEST(RParametricTests, BonferroniCorrection) {
    using Case = ref::BonferroniCorrection;
    const auto adjusted = statcpp::bonferroni_correction(AsVector(Case::kPValues));
    EXPECT_R_RANGE(adjusted, Case, kAdjusted);
}

/// @brief Holm multiplicity correction against p.adjust.
TEST(RParametricTests, HolmCorrection) {
    using Case = ref::HolmCorrection;
    const auto adjusted = statcpp::holm_correction(AsVector(Case::kPValues));
    EXPECT_R_RANGE(adjusted, Case, kAdjusted);
}

/// @brief Benjamini-Hochberg correction against p.adjust.
TEST(RParametricTests, BenjaminiHochbergCorrection) {
    using Case = ref::BenjaminiHochbergCorrection;
    const auto adjusted = statcpp::benjamini_hochberg_correction(AsVector(Case::kPValues));
    EXPECT_R_RANGE(adjusted, Case, kAdjusted);
}

// ============================================================================
// nonparametric_tests.hpp
// ============================================================================

/// @brief Wilcoxon signed-rank test against wilcox.test with the normal approximation.
TEST(RNonparametricTests, WilcoxonSignedRank) {
    using Case = ref::WilcoxonSignedRank;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::wilcoxon_signed_rank_test(x.begin(), x.end(), Case::kMu0);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Mann-Whitney U test against wilcox.test(x, y).
TEST(RNonparametricTests, MannWhitneyU) {
    using Case = ref::MannWhitneyU;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto r = statcpp::mann_whitney_u_test(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Kruskal-Wallis test against kruskal.test.
TEST(RNonparametricTests, KruskalWallis) {
    using Case = ref::KruskalWallis;
    const auto groups = MakeGroups(Case::kGroupsFlat, Case::kGroupsSizes, Case::kGroupsCount);
    const auto r = statcpp::kruskal_wallis_test(groups);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Shapiro-Wilk test against shapiro.test, with a loose bound.
TEST(RNonparametricTests, ShapiroWilk) {
    using Case = ref::ShapiroWilk;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::shapiro_wilk_test(x.begin(), x.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Lilliefors normality test well inside the published p-value range.
TEST(RNonparametricTests, LillieforsTest) {
    using Case = ref::LillieforsTest;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::lilliefors_test(x.begin(), x.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Lilliefors normality test just below the 0.05 significance level.
TEST(RNonparametricTests, LillieforsTestNearAlpha) {
    using Case = ref::LillieforsTestNearAlpha;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::lilliefors_test(x.begin(), x.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Above the published range only the D statistic is compared.
///
/// The Dallal-Wilkinson approximation is defined for p <= 0.10. statcpp still
/// returns a value there, but it indicates consistency with normality rather
/// than an accurate p-value, so the test asserts only that it stays clearly
/// above every conventional significance level.
TEST(RNonparametricTests, LillieforsTestUpperRange) {
    using Case = ref::LillieforsTestUpperRange;
    const auto x = AsVector(Case::kX);
    const auto r = statcpp::lilliefors_test(x.begin(), x.end());
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_GT(r.p_value, 0.10);
    EXPECT_LE(r.p_value, 1.0);
}

/// @brief ks_test_normal forwards to lilliefors_test, so it shares the reference.
///
/// The function is deprecated in statcpp; the deprecation warning is suppressed
/// here because exercising it is the point of this test.
TEST(RNonparametricTests, KsTestNormal) {
    using Case = ref::KsTestNormal;
    const auto x = AsVector(Case::kX);
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif
    const auto r = statcpp::ks_test_normal(x.begin(), x.end());
#if defined(__clang__) || defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Bartlett homogeneity-of-variance test against bartlett.test.
TEST(RNonparametricTests, BartlettTest) {
    using Case = ref::BartlettTest;
    const auto groups = MakeGroups(Case::kGroupsFlat, Case::kGroupsSizes, Case::kGroupsCount);
    const auto r = statcpp::bartlett_test(groups);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_FIELD(r.df, Case, kDf);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Median-centred Levene test against car::leveneTest.
TEST(RNonparametricTests, LeveneTest) {
    using Case = ref::LeveneTest;
    const auto groups = MakeGroups(Case::kGroupsFlat, Case::kGroupsSizes, Case::kGroupsCount);
    const auto r = statcpp::levene_test(groups);
    EXPECT_R_FIELD(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Fisher exact test against fisher.test on a 2x2 table.
TEST(RNonparametricTests, FisherExactTest) {
    using Case = ref::FisherExactTest;
    const auto r = statcpp::fisher_exact_test(Case::kA, Case::kB, Case::kC, Case::kD);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
}

/// @brief Average ranks with ties against rank(x, ties.method = "average").
TEST(RNonparametricTests, ComputeRanksWithTies) {
    using Case = ref::ComputeRanksWithTies;
    const auto x = AsVector(Case::kX);
    const auto ranks = statcpp::compute_ranks_with_ties(x.begin(), x.end());
    EXPECT_R_RANGE(ranks, Case, kRanks);
}

// ============================================================================
// anova.hpp
// ============================================================================

/// @brief One-way ANOVA and its effect sizes against summary(aov(y ~ g)).
TEST(RAnova, OneWayAnova) {
    using Case = ref::OneWayAnova;
    const auto groups = MakeGroups(Case::kGroupsFlat, Case::kGroupsSizes, Case::kGroupsCount);
    const auto r = statcpp::one_way_anova(groups);
    EXPECT_R_FIELD(r.between.f_statistic, Case, kFStatistic);
    EXPECT_R_PVALUE(r.between.p_value, Case, kPValue);
    EXPECT_R_FIELD(r.between.ss, Case, kSsBetween);
    EXPECT_R_FIELD(r.between.df, Case, kDfBetween);
    EXPECT_R_FIELD(r.between.ms, Case, kMsBetween);
    EXPECT_R_FIELD(r.within.ss, Case, kSsWithin);
    EXPECT_R_FIELD(r.within.df, Case, kDfWithin);
    EXPECT_R_FIELD(r.within.ms, Case, kMsWithin);
    EXPECT_R_FIELD(r.ss_total, Case, kSsTotal);
    EXPECT_R_FIELD(statcpp::eta_squared(r), Case, kEtaSquared);
    EXPECT_R_FIELD(statcpp::omega_squared(r), Case, kOmegaSquared);
    EXPECT_R_FIELD(statcpp::cohens_f(r), Case, kCohensF);
}

/// @brief Tukey HSD against TukeyHSD(aov(y ~ g)).
TEST(RAnova, TukeyHsd) {
    using Case = ref::TukeyHsd;
    const auto groups = MakeGroups(Case::kGroupsFlat, Case::kGroupsSizes, Case::kGroupsCount);
    const auto anova = statcpp::one_way_anova(groups);
    const auto r = statcpp::tukey_hsd(anova, groups);
    EXPECT_R_RANGE(Project(r, [](const auto& c) { return c.mean_diff; }), Case, kMeanDiff);
    EXPECT_R_PVALUE_RANGE(Project(r, [](const auto& c) { return c.p_value; }), Case, kPValue);
    EXPECT_R_RANGE(Project(r, [](const auto& c) { return c.lower; }), Case, kLower);
    EXPECT_R_RANGE(Project(r, [](const auto& c) { return c.upper; }), Case, kUpper);
}

/// @brief Bonferroni post-hoc comparisons against the pooled-MSE closed form.
TEST(RAnova, BonferroniPosthoc) {
    using Case = ref::BonferroniPosthoc;
    const auto groups = MakeGroups(Case::kGroupsFlat, Case::kGroupsSizes, Case::kGroupsCount);
    const auto anova = statcpp::one_way_anova(groups);
    const auto r = statcpp::bonferroni_posthoc(anova);
    EXPECT_R_RANGE(Project(r, [](const auto& c) { return c.mean_diff; }), Case, kMeanDiff);
    EXPECT_R_RANGE(Project(r, [](const auto& c) { return c.statistic; }), Case, kStatistic);
    EXPECT_R_PVALUE_RANGE(Project(r, [](const auto& c) { return c.p_value; }), Case, kPValue);
    // The same p-values are produced by R's pairwise.t.test.
    EXPECT_R_PVALUE_RANGE(Project(r, [](const auto& c) { return c.p_value; }), Case, kCrossCheck);
}

/// @brief Scheffe post-hoc comparisons against the F-based closed form.
TEST(RAnova, ScheffePosthoc) {
    using Case = ref::ScheffePosthoc;
    const auto groups = MakeGroups(Case::kGroupsFlat, Case::kGroupsSizes, Case::kGroupsCount);
    const auto anova = statcpp::one_way_anova(groups);
    const auto r = statcpp::scheffe_posthoc(anova);
    EXPECT_R_RANGE(Project(r, [](const auto& c) { return c.mean_diff; }), Case, kMeanDiff);
    // statcpp keeps the signed t statistic here; F = t^2 / df_between is used
    // only to obtain the p-value.
    EXPECT_R_RANGE(Project(r, [](const auto& c) { return c.statistic; }), Case, kStatistic);
    const double df_between = anova.between.df;
    EXPECT_R_RANGE(Project(r, [df_between](const auto& c) { return c.statistic * c.statistic / df_between; }),
                   Case, kFStatistic);
    EXPECT_R_PVALUE_RANGE(Project(r, [](const auto& c) { return c.p_value; }), Case, kPValue);
}

/// @brief Comparisons against a control group, using statcpp's Bonferroni approximation.
TEST(RAnova, DunnettPosthoc) {
    using Case = ref::DunnettPosthoc;
    const auto groups = MakeGroups(Case::kGroupsFlat, Case::kGroupsSizes, Case::kGroupsCount);
    const auto anova = statcpp::one_way_anova(groups);
    const auto r = statcpp::dunnett_posthoc(anova, Case::kControlGroup);
    EXPECT_R_RANGE(Project(r, [](const auto& c) { return c.mean_diff; }), Case, kMeanDiff);
    EXPECT_R_RANGE(Project(r, [](const auto& c) { return c.statistic; }), Case, kStatistic);
    EXPECT_R_PVALUE_RANGE(Project(r, [](const auto& c) { return c.p_value; }), Case, kPValue);
}

/// @brief Two-way ANOVA and partial eta squared against summary(aov(y ~ a * b)).
TEST(RAnova, TwoWayAnova) {
    using Case = ref::TwoWayAnova;
    std::vector<std::vector<std::vector<double>>> data(
        Case::kLevelsA, std::vector<std::vector<double>>(Case::kLevelsB));
    std::size_t offset = 0;
    for (std::size_t a = 0; a < Case::kLevelsA; ++a) {
        for (std::size_t b = 0; b < Case::kLevelsB; ++b) {
            data[a][b].assign(Case::kValues + offset, Case::kValues + offset + Case::kReps);
            offset += Case::kReps;
        }
    }
    const auto r = statcpp::two_way_anova(data);
    EXPECT_R_FIELD(r.factor_a.f_statistic, Case, kFA);
    EXPECT_R_PVALUE(r.factor_a.p_value, Case, kPA);
    EXPECT_R_FIELD(r.factor_b.f_statistic, Case, kFB);
    EXPECT_R_PVALUE(r.factor_b.p_value, Case, kPB);
    EXPECT_R_FIELD(r.interaction.f_statistic, Case, kFInteraction);
    EXPECT_R_PVALUE(r.interaction.p_value, Case, kPInteraction);
    EXPECT_R_FIELD(r.factor_a.ss, Case, kSsA);
    EXPECT_R_FIELD(r.factor_b.ss, Case, kSsB);
    EXPECT_R_FIELD(r.interaction.ss, Case, kSsInteraction);
    EXPECT_R_FIELD(r.error.ss, Case, kSsError);
    EXPECT_R_FIELD(statcpp::partial_eta_squared_a(r), Case, kPartialEtaSquaredA);
    EXPECT_R_FIELD(statcpp::partial_eta_squared_b(r), Case, kPartialEtaSquaredB);
    EXPECT_R_FIELD(statcpp::partial_eta_squared_interaction(r), Case, kPartialEtaSquaredInteraction);
}

/// @brief One-way ANCOVA against summary(aov(y ~ x + g)).
TEST(RAnova, OneWayAncova) {
    using Case = ref::OneWayAncova;
    std::vector<std::vector<std::pair<double, double>>> groups(Case::kYCount);
    std::size_t offset = 0;
    for (std::size_t g = 0; g < Case::kYCount; ++g) {
        for (std::size_t i = 0; i < Case::kYSizes[g]; ++i) {
            groups[g].emplace_back(Case::kYFlat[offset + i], Case::kXFlat[offset + i]);
        }
        offset += Case::kYSizes[g];
    }
    const auto r = statcpp::one_way_ancova(groups);
    EXPECT_R_FIELD(r.ss_covariate, Case, kSsCovariate);
    EXPECT_R_FIELD(r.df_covariate, Case, kDfCovariate);
    EXPECT_R_FIELD(r.f_covariate, Case, kFCovariate);
    EXPECT_R_PVALUE(r.p_covariate, Case, kPCovariate);
    EXPECT_R_FIELD(r.ss_treatment, Case, kSsTreatment);
    EXPECT_R_FIELD(r.df_treatment, Case, kDfTreatment);
    EXPECT_R_FIELD(r.f_treatment, Case, kFTreatment);
    EXPECT_R_PVALUE(r.p_treatment, Case, kPTreatment);
    EXPECT_R_FIELD(r.ss_error, Case, kSsError);
    EXPECT_R_FIELD(r.df_error, Case, kDfError);
}

}  // namespace
