/**
 * @file test_vs_r_applied.cpp
 * @brief Compare statcpp applied-analysis modules against R 4.4.2 reference values.
 *
 * Covers survival.hpp, time_series.hpp, robust.hpp, multivariate.hpp,
 * categorical.hpp and clustering.hpp. Reference values come from
 * r_reference_applied.hpp, generated by generate_r_reference.R.
 */

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <iterator>
#include <map>
#include <vector>

#include <gtest/gtest.h>

#include "statcpp/categorical.hpp"
#include "statcpp/clustering.hpp"
#include "statcpp/multivariate.hpp"
#include "statcpp/robust.hpp"
#include "statcpp/survival.hpp"
#include "statcpp/time_series.hpp"

#include "r_compare.hpp"
#include "r_reference_applied.hpp"

namespace {

namespace ref = statcpp_test::r_ref;
using statcpp_test::MakeMatrix;

/// @brief Copy a reference array into the vector type the statcpp API expects.
template <std::size_t N>
std::vector<double> AsVector(const double (&values)[N])
{
    return std::vector<double>(values, values + N);
}

/// @brief Convert a reference array of 0/1 flags into the event vector survival takes.
template <std::size_t N>
std::vector<bool> AsEvents(const double (&values)[N])
{
    std::vector<bool> out;
    out.reserve(N);
    for (const double v : values) out.push_back(v != 0.0);
    return out;
}

/// @brief Flatten a matrix in row-major order for comparison against the reference.
std::vector<double> Flatten(const std::vector<std::vector<double>>& m)
{
    std::vector<double> out;
    for (const auto& row : m) out.insert(out.end(), row.begin(), row.end());
    return out;
}

// ============================================================================
// survival.hpp
// ============================================================================

/// @brief Kaplan-Meier estimator against survfit(conf.type = "plain").
TEST(RSurvival, KaplanMeier) {
    using Case = ref::KaplanMeier;
    const auto km = statcpp::kaplan_meier(AsVector(Case::kTimes), AsEvents(Case::kEvents));
    EXPECT_R_RANGE(km.times, Case, kEventTimes);
    EXPECT_R_RANGE(km.survival, Case, kSurvival);
    EXPECT_R_PVALUE_RANGE(km.se, Case, kSe);
    std::vector<double> risk, events;
    for (const auto v : km.n_at_risk) risk.push_back(static_cast<double>(v));
    for (const auto v : km.n_events) events.push_back(static_cast<double>(v));
    EXPECT_R_RANGE(risk, Case, kNAtRisk);
    EXPECT_R_RANGE(events, Case, kNEvents);
    EXPECT_R_FIELD(statcpp::median_survival_time(km), Case, kMedian);
}

/// @brief Nelson-Aalen cumulative hazard against survfit(type = "fh").
TEST(RSurvival, NelsonAalen) {
    using Case = ref::NelsonAalen;
    const auto na = statcpp::nelson_aalen(AsVector(Case::kTimes), AsEvents(Case::kEvents));
    EXPECT_R_RANGE(na.times, Case, kEventTimes);
    // statcpp accumulates d_i / n_i; R's type = "fh" applies a tie correction,
    // recorded as fh_check, which differs wherever events are tied.
    EXPECT_R_PVALUE_RANGE(na.cumulative_hazard, Case, kCumulativeHazard);
}

/// @brief Log-rank test against survival::survdiff.
TEST(RSurvival, LogrankTest) {
    using Case = ref::LogrankTest;
    const auto r = statcpp::logrank_test(AsVector(Case::kTimes1), AsEvents(Case::kEvents1),
                                          AsVector(Case::kTimes2), AsEvents(Case::kEvents2));
    EXPECT_R_PVALUE(r.statistic, Case, kStatistic);
    EXPECT_R_PVALUE(r.p_value, Case, kPValue);
    EXPECT_R_FIELD(static_cast<double>(r.observed1), Case, kObserved1);
    EXPECT_R_FIELD(static_cast<double>(r.observed2), Case, kObserved2);
    EXPECT_R_PVALUE(r.expected1, Case, kExpected1);
    EXPECT_R_PVALUE(r.expected2, Case, kExpected2);
}

// ============================================================================
// time_series.hpp
// ============================================================================

/// @brief Autocorrelation, differencing, smoothing and the error measures.
TEST(RTimeSeries, All) {
    using Case = ref::TimeSeries;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto b = x.begin(), e = x.end();
    EXPECT_R_RANGE(statcpp::acf(b, e, Case::kMaxLag), Case, kAcf);
    EXPECT_R_FIELD(statcpp::autocorrelation(b, e, Case::kLagK), Case, kAutocorrelationLag3);
    EXPECT_R_RANGE(statcpp::pacf(b, e, Case::kMaxLag), Case, kPacf);
    EXPECT_R_RANGE(statcpp::diff(b, e, 1), Case, kDiff1);
    EXPECT_R_RANGE(statcpp::diff(b, e, 2), Case, kDiff2);
    EXPECT_R_RANGE(statcpp::seasonal_diff(b, e, Case::kPeriod), Case, kSeasonalDiff);
    EXPECT_R_RANGE(statcpp::lag(b, e, Case::kLagK), Case, kLag3);
    EXPECT_R_RANGE(statcpp::moving_average(b, e, Case::kWindow), Case, kMovingAverage);
    EXPECT_R_RANGE(statcpp::exponential_moving_average(b, e, Case::kAlpha), Case, kEma);
    EXPECT_R_FIELD(statcpp::mse(y.begin(), y.end(), b), Case, kMse);
    EXPECT_R_FIELD(statcpp::rmse(y.begin(), y.end(), b), Case, kRmse);
    EXPECT_R_FIELD(statcpp::mae(y.begin(), y.end(), b), Case, kMae);
    EXPECT_R_FIELD(statcpp::mape(x.begin(), x.end(), y.begin()), Case, kMape);
}

// ============================================================================
// robust.hpp
// ============================================================================

/// @brief Robust location and scale, outlier fences and winsorising.
TEST(RRobust, LocationScaleAndOutliers) {
    using Case = ref::Robust;
    const auto x = AsVector(Case::kX);
    const auto b = x.begin(), e = x.end();
    // mad is the median absolute deviation with constant 1; mad_scaled applies
    // the 1.4826 factor and equals R's mad().
    EXPECT_R_FIELD(statcpp::mad(b, e), Case, kMad);
    EXPECT_R_FIELD(statcpp::mad_scaled(b, e), Case, kMadScaled);
    EXPECT_R_FIELD(statcpp::mad_scaled(b, e), Case, kMadRCheck);
    EXPECT_R_FIELD(statcpp::hodges_lehmann(b, e), Case, kHodgesLehmann);
    EXPECT_R_FIELD(statcpp::hodges_lehmann(b, e), Case, kHlRCheck);
    EXPECT_R_PVALUE(statcpp::biweight_midvariance(b, e, Case::kC), Case, kBiweightMidvariance);
    EXPECT_R_RANGE(statcpp::winsorize(b, e, Case::kLimits), Case, kWinsorized);

    const auto iqr = statcpp::detect_outliers_iqr(b, e, Case::kK);
    EXPECT_R_FIELD(iqr.q1, Case, kQ1);
    EXPECT_R_FIELD(iqr.q3, Case, kQ3);
    EXPECT_R_FIELD(iqr.iqr_value, Case, kIqrValue);
    EXPECT_R_FIELD(iqr.lower_fence, Case, kLowerFence);
    EXPECT_R_FIELD(iqr.upper_fence, Case, kUpperFence);
    EXPECT_R_FIELD(static_cast<double>(iqr.outliers.size()), Case, kNOutliersIqr);
    EXPECT_R_FIELD(
        static_cast<double>(statcpp::detect_outliers_zscore(b, e, Case::kZThreshold).outliers.size()),
        Case, kNOutliersZ);
    EXPECT_R_FIELD(static_cast<double>(
                       statcpp::detect_outliers_modified_zscore(b, e, Case::kMzThreshold)
                           .outliers.size()),
                   Case, kNOutliersMz);
}

/// @brief Cook's distance and DFFITS against their closed forms.
TEST(RRobust, Influence) {
    using Case = ref::Influence;
    const auto res = AsVector(Case::kResiduals);
    const auto hat = AsVector(Case::kHatValues);
    EXPECT_R_RANGE(statcpp::cooks_distance(res, hat, Case::kMse, Case::kP), Case, kCooks);
    EXPECT_R_RANGE(statcpp::dffits(res, hat, Case::kMse), Case, kDffits);
}

// ============================================================================
// multivariate.hpp
// ============================================================================

/// @brief Normalise an eigenvector so that its largest-magnitude entry is positive.
///
/// The sign of a principal component is arbitrary, so both sides apply the same
/// rule before comparison.
void FixSign(std::vector<double>& v)
{
    std::size_t k = 0;
    for (std::size_t i = 1; i < v.size(); ++i) {
        if (std::abs(v[i]) > std::abs(v[k])) k = i;
    }
    if (v[k] < 0.0) {
        for (double& e : v) e = -e;
    }
}

/// @brief Covariance, correlation, scaling and PCA against cov, cor, scale and prcomp.
TEST(RMultivariate, MatrixOperations) {
    using Case = ref::Multivariate;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    EXPECT_R_RANGE(Flatten(statcpp::covariance_matrix(X)), Case, kCovarianceMatrix);
    EXPECT_R_RANGE(Flatten(statcpp::correlation_matrix(X)), Case, kCorrelationMatrix);
    EXPECT_R_RANGE(Flatten(statcpp::standardize(X)), Case, kStandardized);
    EXPECT_R_RANGE(Flatten(statcpp::min_max_scale(X)), Case, kMinMaxScaled);

    const auto p = statcpp::pca(X, Case::kNComponents);
    EXPECT_R_PVALUE_RANGE(p.explained_variance, Case, kExplainedVariance);
    EXPECT_R_PVALUE_RANGE(p.explained_variance_ratio, Case, kExplainedVarianceRatio);

    // components is indexed [variable][component], so the sign is normalised per
    // column before flattening in the same row-major order as the reference.
    auto comps = p.components;
    for (std::size_t c = 0; c < Case::kNComponents; ++c) {
        std::vector<double> col;
        for (std::size_t r = 0; r < Case::kXCols; ++r) col.push_back(comps[r][c]);
        FixSign(col);
        for (std::size_t r = 0; r < Case::kXCols; ++r) comps[r][c] = col[r];
    }
    EXPECT_R_PVALUE_RANGE(Flatten(comps), Case, kComponents);

    EXPECT_R_PVALUE(statcpp::power_iteration(statcpp::covariance_matrix(X)).first, Case,
                    kPowerIterationValue);
}

/// @brief Principal component scores against the centred projection.
TEST(RMultivariate, PcaTransform) {
    using Case = ref::PcaTransform;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    auto p = statcpp::pca(X, Case::kNComponents);
    // Normalise each component's sign before projecting, so the scores match the
    // reference, which was built from the sign-normalised loadings.
    for (std::size_t c = 0; c < Case::kNComponents; ++c) {
        std::vector<double> col;
        for (std::size_t r = 0; r < Case::kXCols; ++r) col.push_back(p.components[r][c]);
        FixSign(col);
        for (std::size_t r = 0; r < Case::kXCols; ++r) p.components[r][c] = col[r];
    }
    const auto scores = statcpp::pca_transform(X, p);
    EXPECT_R_PVALUE_RANGE(Flatten(scores), Case, kScores);
}

// ============================================================================
// categorical.hpp
// ============================================================================

/// @brief 2x2 association measures and the contingency table.
TEST(RCategorical, TwoByTwo) {
    using Case = ref::Categorical;
    const auto orr = statcpp::odds_ratio(Case::kA, Case::kB, Case::kC, Case::kD);
    EXPECT_R_FIELD(orr.odds_ratio, Case, kOddsRatio);
    EXPECT_R_FIELD(orr.log_odds_ratio, Case, kLogOddsRatio);
    EXPECT_R_FIELD(orr.se_log_odds_ratio, Case, kSeLogOddsRatio);
    EXPECT_R_PVALUE(orr.ci_lower, Case, kOrCiLower);
    EXPECT_R_PVALUE(orr.ci_upper, Case, kOrCiUpper);

    const auto rr = statcpp::relative_risk(Case::kA, Case::kB, Case::kC, Case::kD);
    EXPECT_R_FIELD(rr.relative_risk, Case, kRelativeRisk);
    EXPECT_R_FIELD(rr.log_relative_risk, Case, kLogRelativeRisk);
    EXPECT_R_FIELD(rr.se_log_relative_risk, Case, kSeLogRelativeRisk);
    EXPECT_R_PVALUE(rr.ci_lower, Case, kRrCiLower);
    EXPECT_R_PVALUE(rr.ci_upper, Case, kRrCiUpper);

    const auto rd = statcpp::risk_difference(Case::kA, Case::kB, Case::kC, Case::kD);
    EXPECT_R_FIELD(rd.risk_difference, Case, kRiskDifference);
    EXPECT_R_FIELD(rd.se, Case, kSeRiskDifference);
    EXPECT_R_PVALUE(rd.ci_lower, Case, kRdCiLower);
    EXPECT_R_PVALUE(rd.ci_upper, Case, kRdCiUpper);

    const std::vector<std::vector<std::size_t>> table{{Case::kA, Case::kB}, {Case::kC, Case::kD}};
    EXPECT_R_FIELD(statcpp::number_needed_to_treat(table), Case, kNumberNeededToTreat);
    EXPECT_R_FIELD(statcpp::odds_ratio(table).odds_ratio, Case, kOddsRatio);
    EXPECT_R_FIELD(statcpp::relative_risk(table).relative_risk, Case, kRelativeRisk);
    EXPECT_R_FIELD(statcpp::risk_difference(table).risk_difference, Case, kRiskDifference);
}

/// @brief Contingency table counts and margins against table().
TEST(RCategorical, ContingencyTable) {
    using Case = ref::Categorical;
    std::vector<std::size_t> rows, cols;
    for (const double v : Case::kRows) rows.push_back(static_cast<std::size_t>(v));
    for (const double v : Case::kCols) cols.push_back(static_cast<std::size_t>(v));
    const auto t = statcpp::contingency_table(rows, cols);
    std::vector<double> counts;
    for (const auto& row : t.table) {
        for (const auto v : row) counts.push_back(static_cast<double>(v));
    }
    EXPECT_R_RANGE(counts, Case, kTableCounts);
    std::vector<double> rt, ct;
    for (const auto v : t.row_totals) rt.push_back(static_cast<double>(v));
    for (const auto v : t.col_totals) ct.push_back(static_cast<double>(v));
    EXPECT_R_RANGE(rt, Case, kRowTotals);
    EXPECT_R_RANGE(ct, Case, kColTotals);
    EXPECT_R_FIELD(static_cast<double>(t.total), Case, kTotal);
}

// ============================================================================
// clustering.hpp
// ============================================================================

/// @brief Single-linkage clustering against hclust, cutree and cluster::silhouette.
///
/// Merge heights are compared as a sorted vector and cluster sizes as sorted
/// counts: statcpp numbers dendrogram nodes and clusters differently from
/// hclust, but a correct tree has the same merge distances and partition.
TEST(RClustering, HierarchicalAndSilhouette) {
    using Case = ref::Clustering;
    const auto P = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto a = AsVector(Case::kA);
    const auto b = AsVector(Case::kB);
    EXPECT_R_FIELD(statcpp::euclidean_distance(a, b), Case, kEuclideanDistance);
    EXPECT_R_FIELD(statcpp::manhattan_distance(a, b), Case, kManhattanDistance);

    const auto tree = statcpp::hierarchical_clustering(P, statcpp::linkage_type::single);
    std::vector<double> heights;
    for (const auto& node : tree) heights.push_back(node.distance);
    std::sort(heights.begin(), heights.end());
    EXPECT_R_RANGE(heights, Case, kMergeHeights);

    const auto labels = statcpp::cut_dendrogram(tree, P.size(), Case::kK);
    std::map<std::size_t, std::size_t> sizes;
    for (const auto l : labels) ++sizes[l];
    std::vector<double> counts;
    for (const auto& [label, count] : sizes) counts.push_back(static_cast<double>(count));
    std::sort(counts.begin(), counts.end());
    EXPECT_R_RANGE(counts, Case, kClusterSizes);

    EXPECT_R_FIELD(statcpp::silhouette_score(P, labels), Case, kSilhouetteScore);
}

}  // namespace
