/**
 * @file test_vs_r_regression.cpp
 * @brief Compare statcpp regression models against R 4.4.2 reference values.
 *
 * Covers linear_regression.hpp, glm.hpp and model_selection.hpp. Reference
 * values come from r_reference_regression.hpp, generated by
 * generate_r_reference.R.
 */

#include <cstddef>
#include <iterator>
#include <vector>

#include <gtest/gtest.h>

#include "statcpp/glm.hpp"
#include "statcpp/linear_regression.hpp"
#include "statcpp/model_selection.hpp"

#include "r_compare.hpp"
#include "r_reference_regression.hpp"

namespace {

namespace ref = statcpp_test::r_ref;
using statcpp_test::MakeMatrix;

/// @brief Copy a reference array into the vector type the statcpp API expects.
template <std::size_t N>
std::vector<double> AsVector(const double (&values)[N])
{
    return std::vector<double>(values, values + N);
}

// ============================================================================
// linear_regression.hpp
// ============================================================================

/// @brief Simple linear regression against lm(y ~ x) and summary(lm).
TEST(RLinearRegression, SimpleLinearRegression) {
    using Case = ref::SimpleLinearRegression;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::simple_linear_regression(x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_FIELD(m.intercept, Case, kIntercept);
    EXPECT_R_FIELD(m.slope, Case, kSlope);
    EXPECT_R_FIELD(m.intercept_se, Case, kInterceptSe);
    EXPECT_R_FIELD(m.slope_se, Case, kSlopeSe);
    EXPECT_R_FIELD(m.intercept_t, Case, kInterceptT);
    EXPECT_R_FIELD(m.slope_t, Case, kSlopeT);
    EXPECT_R_PVALUE(m.intercept_p, Case, kInterceptP);
    EXPECT_R_PVALUE(m.slope_p, Case, kSlopeP);
    EXPECT_R_FIELD(m.r_squared, Case, kRSquared);
    EXPECT_R_FIELD(m.adj_r_squared, Case, kAdjRSquared);
    EXPECT_R_FIELD(m.residual_se, Case, kResidualSe);
    EXPECT_R_FIELD(m.f_statistic, Case, kFStatistic);
    EXPECT_R_PVALUE(m.f_p_value, Case, kFPValue);
    EXPECT_R_FIELD(m.df_regression, Case, kDfRegression);
    EXPECT_R_FIELD(m.df_residual, Case, kDfResidual);
    EXPECT_R_FIELD(m.ss_total, Case, kSsTotal);
    EXPECT_R_FIELD(m.ss_regression, Case, kSsRegression);
    EXPECT_R_FIELD(m.ss_residual, Case, kSsResidual);
    EXPECT_R_FIELD(statcpp::predict(m, Case::kPredictAt), Case, kPredictValue);
    EXPECT_R_FIELD(statcpp::press_statistic(x.begin(), x.end(), y.begin(), y.end(), m), Case,
                   kPress);
    EXPECT_R_FIELD(statcpp::aic_linear(m, Case::kN), Case, kAicLinear);
    EXPECT_R_FIELD(statcpp::bic_linear(m, Case::kN), Case, kBicLinear);
}

/// @brief Standalone r_squared and adjusted_r_squared against summary(lm).
TEST(RLinearRegression, RSquaredHelpers) {
    using Case = ref::SimpleLinearRegression;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::simple_linear_regression(x.begin(), x.end(), y.begin(), y.end());
    std::vector<double> fitted;
    fitted.reserve(x.size());
    for (const double xi : x) fitted.push_back(statcpp::predict(m, xi));
    EXPECT_R_FIELD(statcpp::r_squared(y.begin(), y.end(), fitted.begin(), fitted.end()), Case,
                   kRSquaredFn);
    EXPECT_R_FIELD(
        statcpp::adjusted_r_squared(y.begin(), y.end(), fitted.begin(), fitted.end(), 1), Case,
        kAdjustedRSquaredFn);
}

/// @brief Confidence and prediction intervals against predict(lm, interval = ...).
TEST(RLinearRegression, Intervals) {
    using Case = ref::RegressionIntervals;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::simple_linear_regression(x.begin(), x.end(), y.begin(), y.end());
    const auto ci = statcpp::confidence_interval_mean(m, x.begin(), x.end(), Case::kXNew,
                                                       Case::kConfidence);
    EXPECT_R_FIELD(ci.prediction, Case, kCiFit);
    EXPECT_R_FIELD(ci.lower, Case, kCiLower);
    EXPECT_R_FIELD(ci.upper, Case, kCiUpper);
    const auto pi = statcpp::prediction_interval_simple(m, x.begin(), x.end(), Case::kXNew,
                                                         Case::kConfidence);
    EXPECT_R_FIELD(pi.prediction, Case, kPiFit);
    EXPECT_R_FIELD(pi.lower, Case, kPiLower);
    EXPECT_R_FIELD(pi.upper, Case, kPiUpper);
}

/// @brief Residual diagnostics against rstandard, rstudent, hatvalues and cooks.distance.
TEST(RLinearRegression, ResidualDiagnostics) {
    using Case = ref::ResidualDiagnostics;
    const auto x = AsVector(Case::kX);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::simple_linear_regression(x.begin(), x.end(), y.begin(), y.end());
    const auto d = statcpp::compute_residual_diagnostics(m, x.begin(), x.end(), y.begin(), y.end());
    EXPECT_R_RANGE(d.residuals, Case, kResiduals);
    // statcpp's standardized residual is e/sigma; its studentized residual is
    // the internally studentized form R calls rstandard.
    EXPECT_R_RANGE(d.standardized_residuals, Case, kStandardized);
    EXPECT_R_RANGE(d.studentized_residuals, Case, kStudentized);
    EXPECT_R_RANGE(d.hat_values, Case, kHatValues);
    EXPECT_R_RANGE(d.cooks_distance, Case, kCooks);
    EXPECT_R_FIELD(d.durbin_watson, Case, kDurbinWatson);
}

/// @brief Multiple linear regression against lm(y ~ x1 + x2).
TEST(RLinearRegression, MultipleLinearRegression) {
    using Case = ref::MultipleLinearRegression;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::multiple_linear_regression(X, y);
    EXPECT_R_RANGE(m.coefficients, Case, kCoefficients);
    EXPECT_R_RANGE(m.coefficient_se, Case, kCoefficientSe);
    EXPECT_R_RANGE(m.t_statistics, Case, kTStatistics);
    EXPECT_R_PVALUE_RANGE(m.p_values, Case, kPValues);
    EXPECT_R_FIELD(m.r_squared, Case, kRSquared);
    EXPECT_R_FIELD(m.adj_r_squared, Case, kAdjRSquared);
    EXPECT_R_FIELD(m.residual_se, Case, kResidualSe);
    EXPECT_R_FIELD(m.f_statistic, Case, kFStatistic);
    EXPECT_R_PVALUE(m.f_p_value, Case, kFPValue);
    EXPECT_R_FIELD(m.df_regression, Case, kDfRegression);
    EXPECT_R_FIELD(m.df_residual, Case, kDfResidual);
    EXPECT_R_FIELD(m.ss_total, Case, kSsTotal);
    EXPECT_R_FIELD(m.ss_regression, Case, kSsRegression);
    EXPECT_R_FIELD(m.ss_residual, Case, kSsResidual);
    EXPECT_R_FIELD(statcpp::predict(m, AsVector(Case::kXNew)), Case, kPredictValue);
    EXPECT_R_FIELD(statcpp::aic_linear(m, Case::kN), Case, kAicLinear);
    EXPECT_R_FIELD(statcpp::bic_linear(m, Case::kN), Case, kBicLinear);
    EXPECT_R_FIELD(statcpp::loocv_linear(X, y).mean_error, Case, kLoocvMse);
}

/// @brief Variance inflation factors and the correlation-matrix determinant.
TEST(RLinearRegression, Multicollinearity) {
    using Case = ref::Multicollinearity;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    EXPECT_R_RANGE(statcpp::compute_vif(X), Case, kVif);
    EXPECT_R_FIELD(statcpp::correlation_matrix_determinant(X), Case, kDeterminant);
    EXPECT_R_FIELD(statcpp::multicollinearity_score(X), Case, kScore);
}

// ============================================================================
// glm.hpp
// ============================================================================

/// @brief Logistic regression against glm(family = binomial()).
TEST(RGlm, LogisticRegression) {
    using Case = ref::LogisticRegression;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::logistic_regression(X, y);
    ASSERT_TRUE(m.converged);
    // Tight tier: quantities that agree to about 1e-8 or better.
    EXPECT_R_RANGE(m.coefficients, Case, kCoefficients);
    EXPECT_R_RANGE(m.coefficients, Case, kCoefficients);
    EXPECT_R_FIELD(m.null_deviance, Case, kNullDeviance);
    EXPECT_R_FIELD(m.residual_deviance, Case, kResidualDeviance);
    EXPECT_R_FIELD(m.df_null, Case, kDfNull);
    EXPECT_R_FIELD(m.df_residual, Case, kDfResidual);
    EXPECT_R_FIELD(m.aic, Case, kAic);
    EXPECT_R_FIELD(m.log_likelihood, Case, kLogLikelihood);
    EXPECT_R_FIELD(m.null_log_likelihood, Case, kNullLogLikelihood);
    EXPECT_R_RANGE(statcpp::odds_ratios(m), Case, kOddsRatios);
    // Loose tier: standard errors and everything derived from them.
    EXPECT_R_PVALUE_RANGE(m.coefficient_se, Case, kCoefficientSe);
    EXPECT_R_PVALUE_RANGE(m.z_statistics, Case, kZStatistics);
    EXPECT_R_PVALUE_RANGE(m.p_values, Case, kPValues);

    const auto ci = statcpp::odds_ratios_ci(m, 0.95);
    std::vector<double> lower, upper;
    for (const auto& [lo, hi] : ci) { lower.push_back(lo); upper.push_back(hi); }
    EXPECT_R_PVALUE_RANGE(lower, Case, kOrCiLower);
    EXPECT_R_PVALUE_RANGE(upper, Case, kOrCiUpper);

    EXPECT_R_FIELD(statcpp::predict_probability(m, AsVector(Case::kXNew)), Case,
                   kPredictProbability);
    EXPECT_R_FIELD(statcpp::pseudo_r_squared_mcfadden(m), Case, kMcfadden);
    EXPECT_R_PVALUE(statcpp::pseudo_r_squared_nagelkerke(m, y, y.size()), Case, kNagelkerke);

    const auto r = statcpp::compute_glm_residuals(m, X, y);
    EXPECT_R_PVALUE_RANGE(r.deviance, Case, kDevianceResiduals);
    EXPECT_R_PVALUE_RANGE(r.pearson, Case, kPearsonResiduals);
    EXPECT_R_PVALUE_RANGE(r.response, Case, kResponseResiduals);
}

/// @brief Poisson regression against glm(family = poisson()).
TEST(RGlm, PoissonRegression) {
    using Case = ref::PoissonRegression;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::poisson_regression(X, y);
    ASSERT_TRUE(m.converged);
    EXPECT_R_PVALUE_RANGE(m.coefficients, Case, kCoefficients);
    EXPECT_R_PVALUE_RANGE(m.coefficient_se, Case, kCoefficientSe);
    EXPECT_R_PVALUE_RANGE(m.z_statistics, Case, kZStatistics);
    // The intercept p-value here is about 1e-117; it is compared like any other
    // now that the upper tail is formed through norm_sf.
    EXPECT_R_PVALUE_RANGE(m.p_values, Case, kPValues);
    EXPECT_R_PVALUE(m.null_deviance, Case, kNullDeviance);
    EXPECT_R_PVALUE(m.residual_deviance, Case, kResidualDeviance);
    EXPECT_R_FIELD(m.df_null, Case, kDfNull);
    EXPECT_R_FIELD(m.df_residual, Case, kDfResidual);
    EXPECT_R_PVALUE(m.aic, Case, kAic);
    EXPECT_R_PVALUE(m.log_likelihood, Case, kLogLikelihood);
    EXPECT_R_PVALUE(m.null_log_likelihood, Case, kNullLogLikelihood);
    EXPECT_R_PVALUE_RANGE(statcpp::incidence_rate_ratios(m), Case, kIncidenceRateRatios);
    EXPECT_R_PVALUE(statcpp::predict_count(m, AsVector(Case::kXNew)), Case, kPredictCount);
    EXPECT_R_PVALUE(statcpp::pseudo_r_squared_mcfadden(m), Case, kMcfadden);
    EXPECT_R_PVALUE(statcpp::overdispersion_test(m, X, y), Case, kOverdispersion);
}

/// @brief glm_fit reaches the same solution as the logistic_regression wrapper.
TEST(RGlm, GlmFitMatchesWrapper) {
    using Case = ref::LogisticRegression;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::glm_fit(X, y, statcpp::distribution_family::binomial,
                                     statcpp::link_function::logit);
    ASSERT_TRUE(m.converged);
    EXPECT_R_PVALUE_RANGE(m.coefficients, Case, kCoefficients);
}

// ============================================================================
// model_selection.hpp
// ============================================================================

/// @brief Information criteria against their closed forms.
TEST(RModelSelection, InformationCriteria) {
    using Case = ref::InformationCriteria;
    EXPECT_R_FIELD(statcpp::aic(Case::kLogLikelihood, Case::kK), Case, kAic);
    EXPECT_R_FIELD(statcpp::bic(Case::kLogLikelihood, Case::kN, Case::kK), Case, kBic);
    EXPECT_R_FIELD(statcpp::aicc(Case::kLogLikelihood, Case::kN, Case::kK), Case, kAicc);
}

/// @brief Ridge regression against the closed form statcpp's estimator defines.
TEST(RModelSelection, RidgeRegression) {
    using Case = ref::RidgeRegression;
    const auto X = MakeMatrix(Case::kXFlat, Case::kXRows, Case::kXCols);
    const auto y = AsVector(Case::kY);
    const auto m = statcpp::ridge_regression(X, y, Case::kLambda);
    ASSERT_TRUE(m.converged);
    EXPECT_R_PVALUE_RANGE(m.coefficients, Case, kCoefficients);
    EXPECT_R_PVALUE(m.mse, Case, kMse);
}

}  // namespace
